/**
 * ScriptType for 05-functional-effects-hkt/effect/packages/effect/src/unstable/rpc/RpcGroup.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 5 type-level aliases: 5 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { Dequeue } from '../../../../../../../../05-functional-effects-hkt/effect/packages/effect/src/Queue.js'
import type { ExcludeProvides, ExtractRequires, IsStream, ToHandlerFn, Wrapper } from '../../../../../../../../05-functional-effects-hkt/effect/packages/effect/src/unstable/rpc/Rpc.js'
import type { Any, RpcGroup } from '../../../../../../../../05-functional-effects-hkt/effect/packages/effect/src/unstable/rpc/RpcGroup.js'
declare namespace Cause {
  export type Done<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Effect {
  export type Effect<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Queue {
  export type Dequeue<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Rpc {
  export type Any<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type ExcludeProvides<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type ExtractRequires<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type IsStream<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type ToHandlerFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Wrapper<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Stream {
  export type Stream<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m1 {
  export type Current<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type K<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type R<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type _R<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m2 {
  export type _R<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const Any: any
declare const Cause: any
declare const Dequeue: any
declare const Done: any
declare const Effect: any
declare const ExcludeProvides: any
declare const ExtractRequires: any
declare const IsStream: any
declare const Queue: any
declare const R: any
declare const RpcGroup: any
declare const Scope: any
declare const Stream: any
declare const ToHandlerFn: any
declare const Wrapper: any
declare const _R: any
type Cause<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Done<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Effect<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Queue<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type R<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Scope<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Stream<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type _R<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ HandlersFrom: verified type-identical to the original
/* @scripttype preserveParamNames */
/**
 * @param {Rpc.Any} Rpc
 */
export function HandlersFrom(Rpc): any {
  const out = emptyObject
  for (const Current in keySet(Rpc)) {
    out[Current['_tag']] = readonlyProp(t<Rpc.ToHandlerFn<typeof Current>>())
  }
  return out
}
/* compiles to:
 * export type HandlersFrom<Rpc extends Rpc.Any> = {
 *   readonly [Current in Rpc as Current['_tag']]: Rpc.ToHandlerFn<Current>
 * }
 */

// ✓ HandlerFrom: verified type-identical to the original
/* @scripttype preserveParamNames */
/**
 * @param {Rpc.Any} Rpc
 * @param {(typeof Rpc)["_tag"]} Tag
 */
export function HandlerFrom(Rpc, Tag): any {
  const m1 = matches<Hole<"Current">>(Extract(Rpc, { _tag: readonlyProp(Tag) }))
  if (m1) {
    if (matches<Rpc.Any>(m1.Current)) {
      return t<Rpc.ToHandlerFn<typeof m1.Current>>()
    }
    return never
  }
  return never
}
/* compiles to:
 * export type HandlerFrom<Rpc extends Rpc.Any, Tag extends Rpc['_tag']> =
 *   Extract<Rpc, { readonly _tag: Tag }> extends infer Current
 *     ? Current extends Rpc.Any ? Rpc.ToHandlerFn<Current> : never
 *     : never
 */

// ✓ HandlersServices: verified type-identical to the original
/* @scripttype preserveParamNames */
export function HandlersServices(Rpcs: Rpc.Any, Handlers): any {
  const m1 = matches<Hole<"K">>(keyof(Handlers))
  if (m1) {
    if (matches<keyof typeof Handlers & string>(m1.K)) {
      return HandlerServices(Rpcs, m1.K, Handlers[m1.K])
    }
    return never
  }
  return never
}
/* compiles to:
 * export type HandlersServices<Rpcs extends Rpc.Any, Handlers> =
 *   keyof Handlers extends infer K
 *     ? K extends keyof Handlers & string ? HandlerServices<Rpcs, K, Handlers[K]> : never
 *     : never
 */

// ✓ HandlerServices: verified type-identical to the original
/* @scripttype preserveParamNames */
/**
 * @param {Rpc.Any} Rpcs
 * @param {(typeof Rpcs)["_tag"]} K
 */
export function HandlerServices(Rpcs, K, Handler): any {
  if (matches<Rpc.IsStream<typeof Rpcs, typeof K>>(true)) {
    const m1 = matches<(...args: any) => Stream.Stream<Hole<"_A">, Hole<"_E">, Hole<"_R">> | Rpc.Wrapper<Stream.Stream<Hole<"_A">, Hole<"_E">, Hole<"_R">>> | Effect.Effect<Queue.Dequeue<Hole<"_A">, Hole<"_E"> | Cause.Done>, Hole<"_EX">, Hole<"_R">> | Rpc.Wrapper<Effect.Effect<Queue.Dequeue<Hole<"_A">, Hole<"_E"> | Cause.Done>, Hole<"_EX">, Hole<"_R">>>>(Handler)
    if (m1) {
      return Exclude(t<Rpc.ExcludeProvides<typeof m1._R, typeof Rpcs, typeof K>>(), Scope) | t<Rpc.ExtractRequires<typeof Rpcs, typeof K>>()
    }
    return never
  }
  const m2 = matches<(...args: any) => Effect.Effect<Hole<"_A">, Hole<"_E">, Hole<"_R">> | Rpc.Wrapper<Effect.Effect<Hole<"_A">, Hole<"_E">, Hole<"_R">>>>(Handler)
  if (m2) {
    return Exclude(t<Rpc.ExcludeProvides<typeof m2._R, typeof Rpcs, typeof K>>(), Scope) | t<Rpc.ExtractRequires<typeof Rpcs, typeof K>>()
  }
  return never
}
/* compiles to:
 * export type HandlerServices<Rpcs extends Rpc.Any, K extends Rpcs['_tag'], Handler> =
 *   true extends Rpc.IsStream<Rpcs, K>
 *     ? Handler extends (...args: any) => Stream.Stream<infer _A, infer _E, infer _R> | Rpc.Wrapper<Stream.Stream<infer _A, infer _E, infer _R>> | Effect.Effect<Queue.Dequeue<infer _A, infer _E | Cause.Done>, infer _EX, infer _R> | Rpc.Wrapper<Effect.Effect<Queue.Dequeue<infer _A, infer _E | Cause.Done>, infer _EX, infer _R>>
 *       ? Exclude<Rpc.ExcludeProvides<_R, Rpcs, K>, Scope> | Rpc.ExtractRequires<Rpcs, K>
 *       : never
 *   : Handler extends (...args: any) => Effect.Effect<infer _A, infer _E, infer _R> | Rpc.Wrapper<Effect.Effect<infer _A, infer _E, infer _R>>
 *     ? Exclude<Rpc.ExcludeProvides<_R, Rpcs, K>, Scope> | Rpc.ExtractRequires<Rpcs, K>
 *   : never
 */

// ✓ Rpcs: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Rpcs(Group): any {
  const m1 = matches<RpcGroup<Hole<"R">>>(Group)
  if (m1) {
    if (matches<(typeof m1.R)["_tag"]>(string)) {
      return never
    }
    return m1.R
  }
  return never
}
/* compiles to:
 * export type Rpcs<Group> =
 *   Group extends RpcGroup<infer R> ? string extends R['_tag'] ? never : R : never
 */
