/**
 * ScriptType for 02-inference-at-scale/tanstack-router/packages/router-generator/src/generator.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const GeneratorCacheEntry: any
type GeneratorCacheEntry<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ FileCacheChange: verified type-identical to the original
/* @scripttype preserveParamNames */
export function FileCacheChange(TCacheEntry: GeneratorCacheEntry) {
  return anyOf({ result: false, cacheEntry: TCacheEntry }, { result: true, mtimeMs: bigint, cacheEntry: TCacheEntry }, { result: 'file-not-in-cache' }, { result: 'cannot-stat-file' })
}
/* compiles to:
 * export type FileCacheChange<TCacheEntry extends GeneratorCacheEntry> =
 *   | { result: false; cacheEntry: TCacheEntry }
 *   | { result: true; mtimeMs: bigint; cacheEntry: TCacheEntry }
 *   | { result: 'file-not-in-cache' }
 *   | { result: 'cannot-stat-file' }
 */
