/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/types/array.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const StaticDirection: any
declare const StaticType: any
declare const TImmutable: any
declare const TProperties: any
declare const TSchema: any
type StaticDirection<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type StaticType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TImmutable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TProperties<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TSchema<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ StaticArray: verified type-identical to the original
/* @scripttype preserveParamNames */
export function StaticArray(Stack: string[], Direction: StaticDirection, Context: TProperties, This: TProperties, Array: TSchema, Item: TSchema, Result: readonly unknown[] = matches<TImmutable>(t<typeof Array>()) ? readonlyArrayOf(StaticType(Stack, Direction, Context, This, Item)) : arrayOf(StaticType(Stack, Direction, Context, This, Item))) {
  return Result
}
/* compiles to:
 * export type StaticArray<Stack extends string[], Direction extends StaticDirection, Context extends TProperties, This extends TProperties, Array extends TSchema, Item extends TSchema, Result extends readonly unknown[] = Array extends TImmutable ? readonly StaticType<Stack, Direction, Context, This, Item>[] : StaticType<Stack, Direction, Context, This, Item>[]> = Result
 */
