/**
 * ScriptType for 01-type-level-programming/type-fest/source/exact.d.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const ArrayElement: any
declare const IsEqual: any
declare const IsUnknown: any
declare const KeysOfUnion: any
declare const ObjectValue: any
declare const Primitive: any
type ArrayElement<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type IsEqual<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type IsUnknown<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type KeysOfUnion<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ObjectValue<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Primitive<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ ExactObject: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ExactObject(ParameterType, InputType): any {
  const out = emptyObject
  for (const Key in keyof(ParameterType)) {
    out[Key] = Exact(ParameterType[Key], ObjectValue(InputType, Key))
  }
  return out & Record(Exclude(keyof(InputType), KeysOfUnion(ParameterType)), never)
}
/* compiles to:
 * export type ExactObject<ParameterType, InputType> =
 *   & { [Key in keyof ParameterType]: Exact<ParameterType[Key], ObjectValue<InputType, Key>> }
 *   & Record<Exclude<keyof InputType, KeysOfUnion<ParameterType>>, never>
 */

// ✓ Exact: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Exact(ParameterType, InputType): any {
  if (matches<true>(IsEqual(ParameterType, InputType))) {
    return ParameterType
  }
  if (matches<Primitive>(ParameterType)) {
    return ParameterType
  }
  if (matches<true>(IsUnknown(ParameterType))) {
    return unknown
  }
  if (matches<Function>(ParameterType)) {
    return ParameterType
  }
  if (matches<unknown[]>(ParameterType)) {
    return arrayOf(Exact(ArrayElement(ParameterType), ArrayElement(InputType)))
  }
  if (matches<readonly unknown[]>(ParameterType)) {
    return readonlyArrayOf(Exact(ArrayElement(ParameterType), ArrayElement(InputType)))
  }
  return ExactObject(ParameterType, InputType)
}
/* compiles to:
 * export type Exact<ParameterType, InputType> =
 *   IsEqual<ParameterType, InputType> extends true ? ParameterType
 *   : ParameterType extends Primitive ? ParameterType
 *   : IsUnknown<ParameterType> extends true ? unknown
 *   : ParameterType extends Function ? ParameterType
 *   : ParameterType extends unknown[]
 *     ? Exact<ArrayElement<ParameterType>, ArrayElement<InputType>>[]
 *   : ParameterType extends readonly unknown[]
 *     ? readonly Exact<ArrayElement<ParameterType>, ArrayElement<InputType>>[]
 *   : ExactObject<ParameterType, InputType>
 */
