/**
 * ScriptType for 01-type-level-programming/type-fest/source/is-tuple.d.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const ApplyDefaultOptions: any
declare const DefaultIsTupleOptions: any
declare const If: any
declare const IsAny: any
declare const IsNever: any
declare const IsTupleOptions: any
declare const UnknownArray: any
type ApplyDefaultOptions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type DefaultIsTupleOptions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type If<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type IsAny<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type IsNever<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type IsTupleOptions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type UnknownArray<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ IsTuple: verified type-identical to the original
/* @scripttype preserveParamNames */
export function IsTuple(TArray: UnknownArray, Options: IsTupleOptions = {}) {
  return _IsTuple(TArray, ApplyDefaultOptions(IsTupleOptions, DefaultIsTupleOptions, Options))
}
/* compiles to:
 * export type IsTuple<TArray extends UnknownArray, Options extends IsTupleOptions = {}> = _IsTuple<
 *   TArray,
 *   ApplyDefaultOptions<IsTupleOptions, DefaultIsTupleOptions, Options>
 * >
 */

// ✓ _IsTuple: verified type-identical to the original
/* @scripttype preserveParamNames */
export function _IsTuple(TArray: UnknownArray, Options: Required<IsTupleOptions>) {
  return If(IsAny(TArray), boolean, If(IsNever(TArray), false, matches<unknown>(TArray) ? (matches<(typeof TArray)['length']>(number) ? (matches<false>(Options['fixedLengthOnly']) ? If(IsNever(merge(keyof(TArray), `${number}`)), matches<readonly [ ...any, any ]>(TArray) ? true : false, true) : false) : true) : false))
}
/* compiles to:
 * export type _IsTuple<TArray extends UnknownArray, Options extends Required<IsTupleOptions>> = If<
 *   IsAny<TArray>,
 *   boolean,
 *   If<
 *     IsNever<TArray>,
 *     false,
 *     TArray extends unknown
 *       ? number extends TArray['length']
 *         ? Options['fixedLengthOnly'] extends false
 *           ? If<
 *             IsNever<keyof TArray & `${number}`>,
 *             TArray extends readonly [...any, any] ? true : false,
 *             true
 *           >
 *           : false
 *         : true
 *       : false
 *   >
 * >
 */
