/**
 * ScriptType for 01-type-level-programming/type-fest/source/set-non-nullable-deep.d.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 3 type-level aliases: 3 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const IsAny: any
declare const NonNullableDeep: any
declare const NonRecursiveType: any
declare const Paths: any
declare const SetNonNullable: any
declare const Simplify: any
declare const StringToNumber: any
declare const UnionToTuple: any
declare const UnknownArray: any
type IsAny<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type NonNullableDeep<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type NonRecursiveType<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Paths<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type SetNonNullable<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Simplify<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type StringToNumber<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type UnionToTuple<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type UnknownArray<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ SetNonNullableDeep: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SetNonNullableDeep(BaseType, KeyPaths: Paths<typeof BaseType>) {
  if (matches<true>(IsAny(KeyPaths))) {
    return NonNullableDeep(BaseType)
  }
  return SetNonNullableDeepHelper(BaseType, UnionToTuple(KeyPaths))
}
/* compiles to:
 * export type SetNonNullableDeep<BaseType, KeyPaths extends Paths<BaseType>> =
 *   IsAny<KeyPaths> extends true
 *     ? NonNullableDeep<BaseType>
 *     : SetNonNullableDeepHelper<BaseType, UnionToTuple<KeyPaths>>
 */

// ✓ SetNonNullableDeepHelper: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SetNonNullableDeepHelper(BaseType, KeyPathsTuple: UnknownArray) {
  let baseType = BaseType
  let keyPathsTuple = KeyPathsTuple
  while (true) {
    const m1 = matches<[ Hole<"KeyPath">, ...Hole<"RestPaths"> ]>(keyPathsTuple)
    if (!m1) {
      break
    }
    baseType = SetNonNullableDeepSinglePath(baseType, m1.KeyPath)
    keyPathsTuple = m1.RestPaths
  }
  return baseType
}
/* compiles to:
 * export type SetNonNullableDeepHelper<BaseType, KeyPathsTuple extends UnknownArray> = SetNonNullableDeepHelper__loop<
 *   BaseType,
 *   KeyPathsTuple
 * >
 * type SetNonNullableDeepHelper__loop<BaseType, KeyPathsTuple extends UnknownArray> =
 *   KeyPathsTuple extends [infer KeyPath, ...infer RestPaths]
 *     ? SetNonNullableDeepHelper__loop<SetNonNullableDeepSinglePath<BaseType, KeyPath>, RestPaths>
 *     : BaseType
 */

// ✓ SetNonNullableDeepSinglePath: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SetNonNullableDeepSinglePath(BaseType, KeyPath) {
  if (matches<NonRecursiveType | ReadonlySet<unknown> | ReadonlyMap<unknown, unknown>>(BaseType)) {
    return BaseType
  }
  const m1 = matches<`${Hole<"Property">}.${Hole<"RestPath">}`>(KeyPath)
  if (m1) {
    const out = emptyObject
    for (const Key in keyof(BaseType)) {
      out[Key] = matches<`${typeof Key & (string | number)}`>(m1.Property) ? SetNonNullableDeepSinglePath(BaseType[Key], m1.RestPath) : BaseType[Key]
    }
    return out
  }
  return Simplify(SetNonNullable(BaseType, merge(KeyPath | StringToNumber(KeyPath & string), keyof(BaseType))))
}
/* compiles to:
 * export type SetNonNullableDeepSinglePath<BaseType, KeyPath> =
 *   BaseType extends NonRecursiveType | ReadonlySet<unknown> | ReadonlyMap<unknown, unknown>
 *     ? BaseType
 *   : KeyPath extends `${infer Property}.${infer RestPath}`
 *     ? {
 *       [Key in keyof BaseType]: Property extends `${Key & (string | number)}`
 *         ? SetNonNullableDeepSinglePath<BaseType[Key], RestPath>
 *         : BaseType[Key]
 *     }
 *   : Simplify<
 *     SetNonNullable<BaseType, (KeyPath | StringToNumber<KeyPath & string>) & keyof BaseType>
 *   >
 */
