/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/Union/Merge.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const At: any
declare const ComputeRaw: any
declare const IntersectOf: any
declare const Overwrite: any
declare const Strict: any
type At<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type ComputeRaw<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type IntersectOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Overwrite<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Strict<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ _Merge: verified type-identical to the original
/* @scripttype preserveParamNames */
export function _Merge(U: object) {
  const out = emptyObject
  for (const K in keyof(U)) {
    out[K] = required(At(U, K))
  }
  return IntersectOf(Overwrite(U, out))
}
/* compiles to:
 * export type _Merge<U extends object> = IntersectOf<Overwrite<U, { [K in keyof U]-?: At<U, K> }>>
 */

// ✓ Merge: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Merge(U: object) {
  return ComputeRaw(_Merge(Strict(U)))
}
/* compiles to:
 * export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>
 */
