/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/Union/Select.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 compile-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Is: any
declare const Match: any
type Is<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Match<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ Select: does not compile yet
//   Type 'Is<U, M, match>' cannot be used to index type '{ '1': U & M; '0': never; }'.
/* @scripttype preserveParamNames */
export function Select(U: any, M: any, match: Match = 'default') {
  if (matches<unknown>(U)) {
    return { 1: merge(U, M), 0: never }[Is(U, M, match)]
  }
  return never
}
/* compiles to:
 * export type Select<U extends any, M extends any, match extends Match = 'default'> = U extends unknown ? { '1': U & M; '0': never }[Is<U, M, match>] : never
 */
