/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/Any/Contains.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Extends: any
type Extends<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ Contains: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Contains(A1: any, A2: any) {
  if (matches<1>(Extends(A1, A2))) {
    return 1
  }
  return 0
}
/* compiles to:
 * export type Contains<A1 extends any, A2 extends any> = Extends<A1, A2> extends 1 ? 1 : 0
 */
