/**
 * ScriptType for 02-inference-at-scale/tanstack-query/packages/vue-query/src/types.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 8 type-level aliases: 7 covered, 1 raw
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const ComputedRef: any
declare const DefaultError: any
declare const MutationObserverOptions: any
declare const OmitKeyof: any
declare const Ref: any
declare const ShallowOption: any
declare const UnwrapLeaf: any
declare const UnwrapRef: any
type ComputedRef<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type DefaultError<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type MutationObserverOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type OmitKeyof<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Ref<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type ShallowOption<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type UnwrapLeaf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type UnwrapRef<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ MaybeGetter: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MaybeGetter(T) {
  return T | fnType([], T)
}
/* compiles to:
 * export type MaybeGetter<T> = T | (() => T)
 */

// ✓ MaybeRef: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MaybeRef(T) {
  return Ref(T) | ComputedRef(T) | T
}
/* compiles to:
 * export type MaybeRef<T> = Ref<T> | ComputedRef<T> | T
 */

// ✓ MaybeRefOrGetter: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MaybeRefOrGetter(T) {
  return MaybeRef(T) | fnType([], T)
}
/* compiles to:
 * export type MaybeRefOrGetter<T> = MaybeRef<T> | (() => T)
 */

// ✓ MaybeRefDeep: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MaybeRefDeep(T) {
  const out = emptyObject
  for (const Property in keyof(T)) {
    out[Property] = MaybeRefDeep(T[Property])
  }
  return MaybeRef(matches<Function>(T) ? T : (matches<object>(T) ? out : T))
}
/* compiles to:
 * export type MaybeRefDeep<T> = MaybeRef<T extends Function ? T : T extends object ? { [Property in keyof T]: MaybeRefDeep<T[Property]> } : T>
 */

// ✓ NoUnknown: verified type-identical to the original
/* @scripttype preserveParamNames */
export function NoUnknown(T) {
  if (matches<true>(Equal(unknown, T))) {
    return never
  }
  return T
}
/* compiles to:
 * export type NoUnknown<T> = Equal<unknown, T> extends true ? never : T
 */

// ✗ Equal: uses raw() — language gap, does not count as covered
//   gap: generic function type
/* @scripttype preserveParamNames */
export function Equal(TTargetA, TTargetB) {
  if (matches<<T>() => T extends typeof TTargetB ? 1 : 2>(raw('<T>() => T extends TTargetA ? 1 : 2'))) {
    return true
  }
  return false
}

// ✓ DeepUnwrapRef: verified type-identical to the original
/* @scripttype preserveParamNames */
export function DeepUnwrapRef(T) {
  if (matches<UnwrapLeaf>(T)) {
    return T
  }
  const m1 = matches<Ref<Hole<"U">>>(T)
  if (m1) {
    return DeepUnwrapRef(m1.U)
  }
  if (matches<{}>(T)) {
    const out = emptyObject
    for (const Property in keyof(T)) {
      out[Property] = DeepUnwrapRef(T[Property])
    }
    return out
  }
  return UnwrapRef(T)
}
/* compiles to:
 * export type DeepUnwrapRef<T> = T extends UnwrapLeaf ? T : T extends Ref<infer U> ? DeepUnwrapRef<U> : T extends {} ? { [Property in keyof T]: DeepUnwrapRef<T[Property]> } : UnwrapRef<T>
 */

// ✓ MutationOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MutationOptions(TData = unknown, TError = DefaultError, TVariables = voidType(), TOnMutateResult = unknown) {
  return OmitKeyof(MutationObserverOptions(TData, TError, TVariables, TOnMutateResult), '_defaulted') & ShallowOption
}
/* compiles to:
 * export type MutationOptions<TData = unknown, TError = DefaultError, TVariables = void, TOnMutateResult = unknown> = OmitKeyof<MutationObserverOptions<TData, TError, TVariables, TOnMutateResult>, '_defaulted'> & ShallowOption
 */
