/**
 * ScriptType for 02-inference-at-scale/tanstack-query/packages/vue-query/src/useInfiniteQuery.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const DeepUnwrapRef: any
declare const DefaultError: any
declare const InfiniteQueryObserverOptions: any
declare const InfiniteQueryObserverResult: any
declare const MaybeRef: any
declare const MaybeRefDeep: any
declare const MaybeRefOrGetter: any
declare const QueryKey: any
declare const ShallowOption: any
declare const UseBaseQueryReturnType: any
type DeepUnwrapRef<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type DefaultError<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type InfiniteQueryObserverOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type InfiniteQueryObserverResult<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type MaybeRef<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type MaybeRefDeep<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type MaybeRefOrGetter<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type QueryKey<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type ShallowOption<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type UseBaseQueryReturnType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ UseInfiniteQueryOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryOptions(TQueryFnData = unknown, TError = DefaultError, TData = TQueryFnData, TQueryKey: QueryKey = QueryKey, TPageParam = unknown) {
  const out = emptyObject
  for (const Property in keyof(InfiniteQueryObserverOptions(TQueryFnData, TError, TData, TQueryKey, TPageParam))) {
    out[Property] = matches<'enabled'>(Property) ? MaybeRefOrGetter(InfiniteQueryObserverOptions(TQueryFnData, TError, TData, DeepUnwrapRef(TQueryKey), TPageParam)[Property]) : MaybeRefDeep(InfiniteQueryObserverOptions(TQueryFnData, TError, TData, DeepUnwrapRef(TQueryKey), TPageParam)[Property])
  }
  return MaybeRef(out & ShallowOption)
}
/* compiles to:
 * export type UseInfiniteQueryOptions<TQueryFnData = unknown, TError = DefaultError, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey, TPageParam = unknown> = MaybeRef<{ [Property in keyof InfiniteQueryObserverOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>]: Property extends 'enabled' ? MaybeRefOrGetter<InfiniteQueryObserverOptions<TQueryFnData, TError, TData, DeepUnwrapRef<TQueryKey>, TPageParam>[Property]> : MaybeRefDeep<InfiniteQueryObserverOptions<TQueryFnData, TError, TData, DeepUnwrapRef<TQueryKey>, TPageParam>[Property]> } & ShallowOption>
 */

// ✓ UseInfiniteQueryReturnType: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryReturnType(TData, TError) {
  return UseBaseQueryReturnType(TData, TError, InfiniteQueryObserverResult(TData, TError))
}
/* compiles to:
 * export type UseInfiniteQueryReturnType<TData, TError> = UseBaseQueryReturnType<TData, TError, InfiniteQueryObserverResult<TData, TError>>
 */
