/**
 * ScriptType for 02-inference-at-scale/hono/src/helper/websocket/index.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 mismatch
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Context: any
declare const Response: any
declare const WSEvents: any
type Context<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Response<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type WSEvents<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ WebSocketHelperDefineHandler: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function WebSocketHelperDefineHandler(T, U) {
  return fnType([Context, WSEvents(T), U], t<Promise<Response | void>>() | Response | voidType())
}
/* compiles to:
 * export type WebSocketHelperDefineHandler<T, U> = (a0: Context, a1: WSEvents<T>, a2: U) => Promise<Response | void> | Response | void
 */
