/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/engine/readonly_object/from_type.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const TArray: any
declare const TCyclic: any
declare const TDependent: any
declare const TFromArray: any
declare const TFromCyclic: any
declare const TFromDependent: any
declare const TFromIntersect: any
declare const TFromObject: any
declare const TFromTuple: any
declare const TFromUnion: any
declare const TIntersect: any
declare const TObject: any
declare const TProperties: any
declare const TSchema: any
declare const TTuple: any
declare const TUnion: any
type TArray<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TCyclic<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TDependent<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFromArray<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFromCyclic<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFromDependent<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFromIntersect<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFromObject<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFromTuple<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFromUnion<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TIntersect<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TObject<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TProperties<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TSchema<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TTuple<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TUnion<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ TFromType: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TFromType(Type: TSchema) {
  const m1 = matches<TArray<Hole<"Type", TSchema>>>(Type)
  if (m1) {
    return TFromArray(m1.Type)
  }
  const m2 = matches<TCyclic<Hole<"Defs", TProperties>, Hole<"Ref", string>>>(Type)
  if (m2) {
    return TFromCyclic(m2.Defs, m2.Ref)
  }
  const m3 = matches<TDependent<Hole<"If", TSchema>, Hole<"Then", TSchema>, Hole<"Else", TSchema>>>(Type)
  if (m3) {
    return TFromDependent(m3.If, m3.Then, m3.Else)
  }
  const m4 = matches<TIntersect<Hole<"Types", TSchema[]>>>(Type)
  if (m4) {
    return TFromIntersect(m4.Types)
  }
  const m5 = matches<TObject<Hole<"Properties", TProperties>>>(Type)
  if (m5) {
    return TFromObject(m5.Properties)
  }
  const m6 = matches<TTuple<Hole<"Types", TSchema[]>>>(Type)
  if (m6) {
    return TFromTuple(m6.Types)
  }
  const m7 = matches<TUnion<Hole<"Types", TSchema[]>>>(Type)
  if (m7) {
    return TFromUnion(m7.Types)
  }
  return Type
}
/* compiles to:
 * export type TFromType<Type extends TSchema> =
 *   Type extends TArray<infer Type extends TSchema> ? TFromArray<Type>
 *   : Type extends TCyclic<infer Defs extends TProperties, infer Ref extends string>
 *     ? TFromCyclic<Defs, Ref>
 *   : Type extends TDependent<infer If extends TSchema, infer Then extends TSchema, infer Else extends TSchema>
 *     ? TFromDependent<If, Then, Else>
 *   : Type extends TIntersect<infer Types extends TSchema[]> ? TFromIntersect<Types>
 *   : Type extends TObject<infer Properties extends TProperties> ? TFromObject<Properties>
 *   : Type extends TTuple<infer Types extends TSchema[]> ? TFromTuple<Types>
 *   : Type extends TUnion<infer Types extends TSchema[]> ? TFromUnion<Types>
 *   : Type
 */
