/**
 * ScriptType for 02-inference-at-scale/trpc/packages/server/src/unstable-core-do-not-import/middleware.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 1 covered, 1 raw
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const MiddlewareErrorResult: any
declare const MiddlewareOKResult: any
type MiddlewareErrorResult<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type MiddlewareOKResult<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ MiddlewareResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MiddlewareResult(_TContextOverride) {
  return MiddlewareErrorResult(_TContextOverride) | MiddlewareOKResult(_TContextOverride)
}
/* compiles to:
 * export type MiddlewareResult<_TContextOverride> = MiddlewareErrorResult<_TContextOverride> | MiddlewareOKResult<_TContextOverride>
 */

// ✗ MiddlewareFunction: uses raw() — language gap, does not count as covered
//   gap: object member CallSignature
/* @scripttype preserveParamNames */
export function MiddlewareFunction(TContext, TMeta, TContextOverridesIn, $ContextOverridesOut, TInputOut) {
  return raw('{ (opts: { ctx: Simplify<Overwrite<TContext, TContextOverridesIn>>; type: ProcedureType; path: string; input: TInputOut; getRawInput: GetRawInputFn; meta: TMeta | undefined; signal: AbortSignal | undefined; batchIndex: number; next: { (): Promise<MiddlewareResult<TContextOverridesIn>>; <$ContextOverride>(opts: { ctx?: $ContextOverride; input?: unknown; }): Promise<MiddlewareResult<$ContextOverride>>; (opts: { getRawInput: GetRawInputFn; }): Promise<MiddlewareResult<TContextOverridesIn>>; }; }): Promise<MiddlewareResult<$ContextOverridesOut>>; _type?: string | undefined; }')
}
