/**
 * ScriptType for 02-inference-at-scale/trpc/packages/server/src/unstable-core-do-not-import/router.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 13 type-level aliases: 7 covered, 3 typecheck-error, 2 raw, 1 mismatch
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const AbortSignal: any
declare const AnyProcedure: any
declare const AnyRootTypes: any
declare const AnyRouter: any
declare const CreateRouterOptions: any
declare const ErrorHandlerOptions: any
declare const LegacyObservableSubscriptionProcedure: any
declare const MaybePromise: any
declare const Observable: any
declare const Router: any
declare const RouterRecord: any
declare const TRPCError: any
declare const inferProcedureInput: any
declare const inferProcedureOutput: any
declare const lazyMarker: any
type AbortSignal<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type AnyProcedure<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type AnyRootTypes<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type AnyRouter<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type CreateRouterOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type ErrorHandlerOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type LegacyObservableSubscriptionProcedure<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type MaybePromise<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Observable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Router<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type RouterRecord<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TRPCError<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type inferProcedureInput<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type inferProcedureOutput<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type lazyMarker<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ DecorateProcedure: the ScriptType does not itself typecheck as TypeScript
//   DecorateProcedure.st.ts(3:52) TS2348: Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
/* @scripttype preserveParamNames */
export function DecorateProcedure(TProcedure: AnyProcedure) {
  return fnType([inferProcedureInput(TProcedure)], Promise(matches<'subscription'>(TProcedure['_def']['type']) ? (matches<LegacyObservableSubscriptionProcedure<any>>(TProcedure) ? Observable(inferProcedureOutput(TProcedure), TRPCError) : inferProcedureOutput(TProcedure)) : inferProcedureOutput(TProcedure)))
}
/* compiles to:
 * export type DecorateProcedure<TProcedure extends AnyProcedure> = (a0: inferProcedureInput<TProcedure>) => Promise<TProcedure['_def']['type'] extends 'subscription' ? TProcedure extends LegacyObservableSubscriptionProcedure<any> ? Observable<inferProcedureOutput<TProcedure>, TRPCError> : inferProcedureOutput<TProcedure> : inferProcedureOutput<TProcedure>>
 */

// ✗ DecorateRouterRecord: uses raw() — language gap, does not count as covered
//   gap: pattern bindings inside a mapped-type value
/* @scripttype preserveParamNames */
export function DecorateRouterRecord(TRecord: RouterRecord) {
  const out = emptyObject
  for (const TKey in keyof(TRecord)) {
    out[TKey] = raw('TRecord[TKey] extends infer $Value ? $Value extends AnyProcedure ? DecorateProcedure<$Value> : $Value extends RouterRecord ? DecorateRouterRecord<$Value> : never : never')
  }
  return out
}

// ✓ RouterCallerErrorHandler: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RouterCallerErrorHandler(TContext) {
  return fnType([ErrorHandlerOptions(TContext)], voidType())
}
/* compiles to:
 * export type RouterCallerErrorHandler<TContext> = (a0: ErrorHandlerOptions<TContext>) => void
 */

// ✗ RouterCaller: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function RouterCaller(TRoot: AnyRootTypes, TRecord: RouterRecord) {
  return fnType([TRoot['ctx'] | fnType([], MaybePromise(TRoot['ctx'])), { onError: optional(RouterCallerErrorHandler(TRoot['ctx'])), signal: optional(AbortSignal) }], DecorateRouterRecord(TRecord))
}
/* compiles to:
 * export type RouterCaller<TRoot extends AnyRootTypes, TRecord extends RouterRecord> = (a0: TRoot['ctx'] | (() => MaybePromise<TRoot['ctx']>), a1: { onError?: RouterCallerErrorHandler<TRoot['ctx']>; signal?: AbortSignal }) => DecorateRouterRecord<TRecord>
 */

// ✗ Lazy: the ScriptType does not itself typecheck as TypeScript
//   Lazy.st.ts(3:27) TS2348: Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
/* @scripttype preserveParamNames */
export function Lazy(TAny) {
  return merge(fnType([], Promise(TAny)), { [lazyMarker]: true })
}
/* compiles to:
 * export type Lazy<TAny> = (() => Promise<TAny>) & { [lazyMarker]: true }
 */

// ✗ LazyLoader: the ScriptType does not itself typecheck as TypeScript
//   LazyLoader.st.ts(3:29) TS2348: Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
/* @scripttype preserveParamNames */
export function LazyLoader(TAny) {
  return { load: fnType([], Promise(voidType())), ref: Lazy(TAny) }
}
/* compiles to:
 * export type LazyLoader<TAny> = { load: () => Promise<void>; ref: Lazy<TAny> }
 */

// ✓ BuiltRouter: verified type-identical to the original
/* @scripttype preserveParamNames */
export function BuiltRouter(TRoot: AnyRootTypes, TRecord: RouterRecord) {
  return merge(Router(TRoot, TRecord), TRecord)
}
/* compiles to:
 * export type BuiltRouter<TRoot extends AnyRootTypes, TRecord extends RouterRecord> = Router<TRoot, TRecord> & TRecord
 */

// ✓ inferRouterRootTypes: verified type-identical to the original
/* @scripttype preserveParamNames */
export function inferRouterRootTypes(TRouter: AnyRouter) {
  return TRouter['_def']['_config']['$types']
}
/* compiles to:
 * export type inferRouterRootTypes<TRouter extends AnyRouter> = TRouter['_def']['_config']['$types']
 */

// ✓ inferRouterContext: verified type-identical to the original
/* @scripttype preserveParamNames */
export function inferRouterContext(TRouter: AnyRouter) {
  return inferRouterRootTypes(TRouter)['ctx']
}
/* compiles to:
 * export type inferRouterContext<TRouter extends AnyRouter> = inferRouterRootTypes<TRouter>['ctx']
 */

// ✓ inferRouterError: verified type-identical to the original
/* @scripttype preserveParamNames */
export function inferRouterError(TRouter: AnyRouter) {
  return inferRouterRootTypes(TRouter)['errorShape']
}
/* compiles to:
 * export type inferRouterError<TRouter extends AnyRouter> = inferRouterRootTypes<TRouter>['errorShape']
 */

// ✓ inferRouterMeta: verified type-identical to the original
/* @scripttype preserveParamNames */
export function inferRouterMeta(TRouter: AnyRouter) {
  return inferRouterRootTypes(TRouter)['meta']
}
/* compiles to:
 * export type inferRouterMeta<TRouter extends AnyRouter> = inferRouterRootTypes<TRouter>['meta']
 */

// ✗ DecorateCreateRouterOptions: uses raw() — language gap, does not count as covered
//   gap: pattern bindings inside a mapped-type value
/* @scripttype preserveParamNames */
export function DecorateCreateRouterOptions(TRouterOptions: CreateRouterOptions) {
  const out = emptyObject
  for (const K in keyof(TRouterOptions)) {
    out[K] = raw('TRouterOptions[K] extends infer $Value ? $Value extends AnyProcedure ? $Value : $Value extends Router<any, infer TRecord> ? TRecord : $Value extends Lazy<Router<any, infer TRecord>> ? TRecord : $Value extends CreateRouterOptions ? DecorateCreateRouterOptions<$Value> : never : never')
  }
  return out
}

// ✓ MergeRouters: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MergeRouters(TRouters: AnyRouter[]) {
  let TRoot = TRouters[0]['_def']['_config']['$types']
  let TRecord = {}
  let tRouters = TRouters
  while (true) {
    const m1 = matches<[ Hole<"Head", AnyRouter>, ...Hole<"Tail", AnyRouter[]> ]>(tRouters)
    if (!m1) {
      break
    }
    tRouters = m1.Tail
    TRecord = merge(m1.Head['_def']['record'], TRecord)
  }
  return BuiltRouter(TRoot, TRecord)
}
/* compiles to:
 * export type MergeRouters<TRouters extends AnyRouter[]> = MergeRouters__loop<TRouters, {}>
 * type MergeRouters__loop<TRouters extends AnyRouter[], TRecord> = TRouters extends [infer Head extends AnyRouter, ...(infer Tail extends AnyRouter[])] ? MergeRouters__loop<Tail, Head['_def']['record'] & TRecord> : BuiltRouter<TRoot, TRecord>
 */
