/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/Object/P/Omit.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { Tail } from '../../../../../../01-type-level-programming/ts-toolbelt/sources/List/Tail.js'
import type { BuiltIn } from '../../../../../../01-type-level-programming/ts-toolbelt/sources/Misc/BuiltIn.js'
declare const BuiltIn: any
declare const Key: any
declare const List: any
declare const Tail: any
declare const _LOmit: any
declare const _OOmit: any
type Key<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type List<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type _LOmit<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type _OOmit<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ OmitAt: verified type-identical to the original
/* @scripttype preserveParamNames */
export function OmitAt(O, Path: List<Key>): any {
  if (matches<BuiltIn>(O)) {
    return O
  }
  if (matches<[ Key ]>(Path)) {
    if (matches<List>(O)) {
      return _LOmit(O, Path[0])
    }
    if (matches<object>(O)) {
      return _OOmit(O, Path[0])
    }
    return O
  }
  const out = emptyObject
  for (const K in keyof(O)) {
    out[K] = matches<(typeof Path)[0]>(K) ? OmitAt(O[K], Tail(Path)) : O[K]
  }
  return out
}
/* compiles to:
 * export type OmitAt<O, Path extends List<Key>> =
 *   O extends BuiltIn ? O
 *   : Path extends [Key]
 *     ? O extends List ? _LOmit<O, Path[0]> : O extends object ? _OOmit<O, Path[0]> : O
 *   : { [K in keyof O]: K extends Path[0] ? OmitAt<O[K], Tail<Path>> : O[K] }
 */

// ✓ Omit: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Omit(O: object, Path: List<Key>): any {
  if (matches<unknown>(Path)) {
    return OmitAt(O, Path)
  }
  return never
}
/* compiles to:
 * export type Omit<O extends object, Path extends List<Key>> =
 *   Path extends unknown ? OmitAt<O, Path> : never
 */
