/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/Object/Record.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Key: any
declare const Modx: any
type Key<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Modx<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ Record: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Record(K: Key, A: any = unknown, modx: Modx = ['!', 'W']) {
  const out = emptyObject
  for (const P in keySet(K)) {
    out[P] = readonlyProp(A)
  }
  const out2 = emptyObject
  for (const P in keySet(K)) {
    out2[P] = A
  }
  const out3 = emptyObject
  for (const P in keySet(K)) {
    out3[P] = readonlyProp(optional(A))
  }
  const out4 = emptyObject
  for (const P in keySet(K)) {
    out4[P] = optional(A)
  }
  return { '!': { 'R': out, 'W': out2 }, '?': { 'R': out3, 'W': out4 } }[modx[0]][modx[1]]
}
/* compiles to:
 * export type Record<K extends Key, A extends any = unknown, modx extends Modx = ['!', 'W']> = { '!': { R: { readonly [P in K]: A }; W: { [P1 in K]: A } }; '?': { R: { readonly [P2 in K]?: A }; W: { [P3 in K]?: A } } }[modx[0]][modx[1]]
 */
