/**
 * ScriptType for 01-type-level-programming/hotscript/src/internals/tuples/Tuples.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 51 type-level aliases: 25 compile-error, 15 covered, 9 mismatch, 2 typecheck-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { Call, Fn, PartialApply, _, args, unset } from '../../../../../../01-type-level-programming/hotscript/src/internals/core/Core.js'
import type { Prettify } from '../../../../../../01-type-level-programming/hotscript/src/internals/helpers.js'
import type { Add } from '../../../../../../01-type-level-programming/hotscript/src/internals/numbers/impl/addition.js'
declare namespace Iterator {
  export type Get<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Prev<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace NumberImpls {
  export type Max<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Min<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Numbers {
  export type Add<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Std {
  export type _Omit<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Tuples {
  export type Partition<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace acc_ {
  export type unshift<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m1 {
  export type first<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type head<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type last<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type rest<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type tail<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m2 {
  export type first<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type key<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type left<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type rest<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type right<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace output {
  export type push<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const Add: any
declare const AppendFn: any
declare const AtFn: any
declare const Call: any
declare const ConcatFn: any
declare const DropFn: any
declare const EveryFn: any
declare const FilterFn: any
declare const FindFn: any
declare const FlatMapFn: any
declare const Fn: any
declare const Get: any
declare const HeadFn: any
declare const IsEmptyFn: any
declare const Iterator: any
declare const JoinFn: any
declare const LastFn: any
declare const LengthFn: any
declare const MapFn: any
declare const MaxFn: any
declare const MinFn: any
declare const NumberImpls: any
declare const Numbers: any
declare const PartialApply: any
declare const PartitionFn: any
declare const PrependFn: any
declare const Prettify: any
declare const Prev: any
declare const PropertyKey: any
declare const RangeFn: any
declare const ReduceFn: any
declare const ReduceRightFn: any
declare const ReverseFn: any
declare const SomeFn: any
declare const SplitAtFn: any
declare const Std: any
declare const SumFn: any
declare const TailFn: any
declare const TakeFn: any
declare const TakeWhileFn: any
declare const ToIntersectionFn: any
declare const ToUnionFn: any
declare const Tuples: any
declare const ZipWithFn: any
declare const _: any
declare const _Omit: any
declare const args: any
declare const first: any
declare const head: any
declare const key: any
declare const tail: any
declare const unset: any
type AppendFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type AtFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ConcatFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type DropFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type EveryFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type FilterFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type FindFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type FlatMapFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Get<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type HeadFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type IsEmptyFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Iterator<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type JoinFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type LastFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type LengthFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type MapFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type MaxFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type MinFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type NumberImpls<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Numbers<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type PartitionFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type PrependFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Prev<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type PropertyKey<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type RangeFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ReduceFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ReduceRightFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ReverseFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type SomeFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type SplitAtFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Std<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type SumFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TailFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TakeFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TakeWhileFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ToIntersectionFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ToUnionFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Tuples<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ZipWithFn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type _Omit<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type first<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type head<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type key<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type tail<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✗ HeadImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function HeadImpl(xs): any {
  const m1 = matches<readonly [ Hole<"head">, ...any ]>(xs)
  if (m1) {
    return m1.head
  }
  return never
}
/* compiles to:
 * export type HeadImpl<xs> = xs extends readonly [infer head, ...any] ? head : never
 */

// ✗ At: does not compile yet
//   Cannot find name 'AtFn'.
/* @scripttype preserveParamNames */
export function At(index: number | _ | unset = unset, tuple = unset): any {
  return PartialApply(AtFn, [index, tuple])
}
/* compiles to:
 * export type At<index extends number | _ | unset = unset, tuple = unset> = PartialApply<
 *   AtFn,
 *   [index, tuple]
 * >
 */

// ✗ IsEmptyImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function IsEmptyImpl(tuple: unknown[]): any {
  if (matches<typeof tuple>([])) {
    return true
  }
  return false
}
/* compiles to:
 * export type IsEmptyImpl<tuple extends unknown[]> = [] extends tuple ? true : false
 */

// ✗ IsEmpty: does not compile yet
//   Cannot find name 'IsEmptyFn'. Did you mean 'IsEmpty'?
/* @scripttype preserveParamNames */
export function IsEmpty(tuple = unset): any {
  return PartialApply(IsEmptyFn, [tuple])
}
/* compiles to:
 * export type IsEmpty<tuple = unset> = PartialApply<IsEmptyFn, [tuple]>
 */

// ✗ ToUnion: does not compile yet
//   Cannot find name 'ToUnionFn'. Did you mean 'ToUnion'?
/* @scripttype preserveParamNames */
export function ToUnion(tuple: readonly any[] | _ | unset = unset): any {
  return PartialApply(ToUnionFn, [tuple])
}
/* compiles to:
 * export type ToUnion<tuple extends readonly any[] | _ | unset = unset> = PartialApply<
 *   ToUnionFn,
 *   [tuple]
 * >
 */

// ✗ ToIntersection: does not compile yet
//   Cannot find name 'ToIntersectionFn'. Did you mean 'ToIntersection'?
/* @scripttype preserveParamNames */
export function ToIntersection(tuple = unset): any {
  return PartialApply(ToIntersectionFn, [tuple])
}
/* compiles to:
 * export type ToIntersection<tuple = unset> = PartialApply<ToIntersectionFn, [tuple]>
 */

// ✗ Head: does not compile yet
//   Cannot find name 'HeadFn'. Did you mean 'Head'?
/* @scripttype preserveParamNames */
export function Head(tuple: readonly any[] | unset = unset): any {
  return PartialApply(HeadFn, [tuple])
}
/* compiles to:
 * export type Head<tuple extends readonly any[] | unset = unset> = PartialApply<HeadFn, [tuple]>
 */

// ✗ TailImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function TailImpl(xs): any {
  const m1 = matches<readonly [ any, ...Hole<"tail"> ]>(xs)
  if (m1) {
    return m1.tail
  }
  return []
}
/* compiles to:
 * export type TailImpl<xs> = xs extends readonly [any, ...infer tail] ? tail : []
 */

// ✓ Tail: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Tail(tuple: readonly any[] | unset = unset): any {
  return PartialApply(TailFn, [tuple])
}
/* compiles to:
 * export type Tail<tuple extends readonly any[] | unset = unset> = PartialApply<TailFn, [tuple]>
 */

// ✗ LastImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function LastImpl(xs): any {
  const m1 = matches<readonly [ ...any, Hole<"last"> ]>(xs)
  if (m1) {
    return m1.last
  }
  return never
}
/* compiles to:
 * export type LastImpl<xs> = xs extends readonly [...any, infer last] ? last : never
 */

// ✓ Last: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Last(tuple: readonly any[] | unset = unset): any {
  return PartialApply(LastFn, [tuple])
}
/* compiles to:
 * export type Last<tuple extends readonly any[] | unset = unset> = PartialApply<LastFn, [tuple]>
 */

// ✗ Map: does not compile yet
//   Cannot find name 'MapFn'. Did you mean 'Map'?
/* @scripttype preserveParamNames */
export function Map(fn: Fn | unset | _ = unset, tuple: readonly any[] | unset = unset): any {
  return PartialApply(MapFn, [fn, tuple])
}
/* compiles to:
 * export type Map<
 *   fn extends Fn | unset | _ = unset,
 *   tuple extends readonly any[] | unset = unset
 * > =
 *   PartialApply<MapFn, [fn, tuple]>
 */

// ✗ FlatMap: does not compile yet
//   Cannot find name 'FlatMapFn'. Did you mean 'FlatMap'?
/* @scripttype preserveParamNames */
export function FlatMap(fn: Fn, tuple: readonly any[] | unset = unset): any {
  return PartialApply(FlatMapFn, [fn, tuple])
}
/* compiles to:
 * export type FlatMap<fn extends Fn, tuple extends readonly any[] | unset = unset> = PartialApply<
 *   FlatMapFn,
 *   [fn, tuple]
 * >
 */

// ✓ ReduceImpl: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ReduceImpl(fn: Fn, acc, xs): any {
  let acc_ = acc
  let xs_ = xs
  while (true) {
    const m1 = matches<[ Hole<"first">, ...Hole<"rest"> ]>(xs_)
    if (!m1) {
      break
    }
    acc_ = Call(fn, acc_, m1.first)
    xs_ = m1.rest
  }
  const m2 = matches<readonly [ Hole<"first">, ...Hole<"rest"> ]>(xs_)
  return m2 ? ReduceImpl(fn, Call(fn, acc_, m2.first), m2.rest) : acc_
}
/* compiles to:
 * export type ReduceImpl<fn extends Fn, acc, xs> = ReduceImpl__loop<acc, xs, fn>
 * type ReduceImpl__loop<Acc_, Xs_, Fn extends Fn> =
 *   Xs_ extends [infer first, ...infer rest] ? ReduceImpl__loop<Call<Fn, Acc_, first>, rest, Fn>
 *   : Xs_ extends readonly [infer first, ...infer rest]
 *     ? ReduceImpl<Fn, Call<Fn, Acc_, first>, rest>
 *   : Acc_
 */

// ✗ Reduce: does not compile yet
//   Cannot find name 'ReduceFn'. Did you mean 'Reduce'?
/* @scripttype preserveParamNames */
export function Reduce(fn: Fn, init = unset, tuple: readonly any[] | unset = unset): any {
  return PartialApply(ReduceFn, [fn, init, tuple])
}
/* compiles to:
 * export type Reduce<fn extends Fn, init = unset, tuple extends readonly any[] | unset = unset> = PartialApply<
 *   ReduceFn,
 *   [fn, init, tuple]
 * >
 */

// ✗ ReverseImpl: does not compile yet
//   Cannot find name 'ReverseRecImpl'.
/* @scripttype preserveParamNames */
export function ReverseImpl(tuple): any {
  if (matches<typeof tuple>(arrayOf(any))) {
    return tuple
  }
  return ReverseRecImpl(tuple, [])
}
/* compiles to:
 * export type ReverseImpl<tuple> = any[] extends tuple ? tuple : ReverseRecImpl<tuple, []>
 */

// ✗ ReverseRecImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function ReverseRecImpl(tuple, acc: unknown[]): any {
  let tuple_ = tuple
  let acc_ = acc
  while (true) {
    const m1 = matches<[ Hole<"first">, ...Hole<"rest"> ]>(tuple_)
    if (!m1) {
      break
    }
    tuple_ = m1.rest
    acc_.unshift(m1.first)
  }
  return acc_
}
/* compiles to:
 * export type ReverseRecImpl<tuple, acc extends unknown[]> = ReverseRecImpl__loop<tuple, acc>
 * type ReverseRecImpl__loop<Tuple_, Acc_ extends unknown[]> =
 *   Tuple_ extends [infer first, ...infer rest]
 *     ? ReverseRecImpl__loop<rest, [first, ...Acc_]>
 *     : Acc_
 */

// ✗ Reverse: does not compile yet
//   Cannot find name 'ReverseFn'. Did you mean 'Reverse'?
/* @scripttype preserveParamNames */
export function Reverse(tuple: readonly unknown[] | unset = unset): any {
  return PartialApply(ReverseFn, [tuple])
}
/* compiles to:
 * export type Reverse<tuple extends readonly unknown[] | unset = unset> = PartialApply<
 *   ReverseFn,
 *   [tuple]
 * >
 */

// ✓ ReduceRightImpl: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ReduceRightImpl(xs, acc, fn: Fn): any {
  let xs_ = xs
  let acc_ = acc
  while (true) {
    const m1 = matches<[ ...Hole<"rest">, Hole<"last"> ]>(xs_)
    if (!m1) {
      break
    }
    xs_ = m1.rest
    acc_ = Call(fn, acc_, m1.last)
  }
  return acc_
}
/* compiles to:
 * export type ReduceRightImpl<xs, acc, fn extends Fn> = ReduceRightImpl__loop<xs, acc, fn>
 * type ReduceRightImpl__loop<Xs_, Acc_, Fn extends Fn> =
 *   Xs_ extends [...infer rest, infer last]
 *     ? ReduceRightImpl__loop<rest, Call<Fn, Acc_, last>, Fn>
 *     : Acc_
 */

// ✗ ReduceRight: does not compile yet
//   Cannot find name 'ReduceRightFn'.
/* @scripttype preserveParamNames */
export function ReduceRight(fn: Fn, init = unset, tuple: readonly any[] | unset = unset): any {
  return PartialApply(ReduceRightFn, [fn, init, tuple])
}
/* compiles to:
 * export type ReduceRight<
 *   fn extends Fn,
 *   init = unset,
 *   tuple extends readonly any[] | unset = unset
 * > =
 *   PartialApply<ReduceRightFn, [fn, init, tuple]>
 */

// ✓ Filter: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Filter(fn: Fn, tuple: readonly any[] | unset = unset): any {
  return PartialApply(FilterFn, [fn, tuple])
}
/* compiles to:
 * export type Filter<fn extends Fn, tuple extends readonly any[] | unset = unset> = PartialApply<
 *   FilterFn,
 *   [fn, tuple]
 * >
 */

// ✗ FindImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function FindImpl(xs, fn: Fn, index: any[] = []): any {
  const m1 = matches<[ Hole<"first">, ...Hole<"rest"> ]>(xs)
  if (m1) {
    if (matches<true>(Call(fn, m1.first, index['length']))) {
      return m1.first
    }
    return FindImpl(m1.rest, fn, [...index, any])
  }
  return never
}
/* compiles to:
 * export type FindImpl<xs, fn extends Fn, index extends any[] = []> =
 *   xs extends [infer first, ...infer rest]
 *     ? Call<fn, first, index['length']> extends true
 *       ? first
 *       : FindImpl<rest, fn, [...index, any]>
 *     : never
 */

// ✓ Find: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Find(fn: Fn, tuple: readonly any[] | unset = unset): any {
  return PartialApply(FindFn, [fn, tuple])
}
/* compiles to:
 * export type Find<fn extends Fn, tuple extends readonly any[] | unset = unset> = PartialApply<
 *   FindFn,
 *   [fn, tuple]
 * >
 */

// ✗ Sum: does not compile yet
//   Cannot find name 'SumFn'.
/* @scripttype preserveParamNames */
export function Sum(tuple: readonly any[] | unset = unset): any {
  return PartialApply(SumFn, [tuple])
}
/* compiles to:
 * export type Sum<tuple extends readonly any[] | unset = unset> = PartialApply<SumFn, [tuple]>
 */

// ✗ DropImpl: the ScriptType does not itself typecheck as TypeScript
//   DropImpl.st.ts(3:20) TS2702: 'Iterator' only refers to a type, but is being used as a namespace here.
/* @scripttype preserveParamNames */
export function DropImpl(xs: readonly any[], n: any[]): any {
  if (matches<0>(t<Iterator.Get<typeof n>>())) {
    return xs
  }
  const m1 = matches<readonly [ any, ...Hole<"tail"> ]>(xs)
  if (m1) {
    return DropImpl(m1.tail, t<Iterator.Prev<typeof n>>())
  }
  return []
}
/* compiles to:
 * export type DropImpl<xs extends readonly any[], n extends any[]> =
 *   Iterator.Get<n> extends 0 ? xs
 *   : xs extends readonly [any, ...infer tail] ? DropImpl<tail, Iterator.Prev<n>>
 *   : []
 */

// ✓ Drop: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Drop(n: number | unset | _ = unset, tuple = unset): any {
  return PartialApply(DropFn, [n, tuple])
}
/* compiles to:
 * export type Drop<n extends number | unset | _ = unset, tuple = unset> = PartialApply<
 *   DropFn,
 *   [n, tuple]
 * >
 */

// ✗ TakeImpl: the ScriptType does not itself typecheck as TypeScript
//   TakeImpl.st.ts(3:20) TS2702: 'Iterator' only refers to a type, but is being used as a namespace here.
/* @scripttype preserveParamNames */
export function TakeImpl(xs: readonly any[], it: any[], output: any[] = []): any {
  if (matches<0>(t<Iterator.Get<typeof it>>())) {
    return output
  }
  const m1 = matches<readonly [ Hole<"head">, ...Hole<"tail"> ]>(xs)
  if (m1) {
    return TakeImpl(m1.tail, t<Iterator.Prev<typeof it>>(), [...output, m1.head])
  }
  return output
}
/* compiles to:
 * export type TakeImpl<xs extends readonly any[], it extends any[], output extends any[] = []> =
 *   Iterator.Get<it> extends 0 ? output
 *   : xs extends readonly [infer head, ...infer tail]
 *     ? TakeImpl<tail, Iterator.Prev<it>, [...output, head]>
 *   : output
 */

// ✗ Take: does not compile yet
//   Cannot find name 'TakeFn'.
/* @scripttype preserveParamNames */
export function Take(n: number | unset | _ = unset, tuple = unset): any {
  return PartialApply(TakeFn, [n, tuple])
}
/* compiles to:
 * export type Take<n extends number | unset | _ = unset, tuple = unset> = PartialApply<
 *   TakeFn,
 *   [n, tuple]
 * >
 */

// ✗ TakeWhileImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function TakeWhileImpl(xs: readonly any[], fn: Fn, index: any[] = [], output: any[] = []): any {
  const m1 = matches<readonly [ Hole<"head">, ...Hole<"tail"> ]>(xs)
  if (m1) {
    if (matches<true>(Call(fn, m1.head, index['length']))) {
      return TakeWhileImpl(m1.tail, fn, [...index, any], [...output, m1.head])
    }
    return output
  }
  return output
}
/* compiles to:
 * export type TakeWhileImpl<
 *   xs extends readonly any[],
 *   fn extends Fn,
 *   index extends any[] = [],
 *   output extends any[] = []
 * > =
 *   xs extends readonly [infer head, ...infer tail]
 *     ? Call<fn, head, index['length']> extends true
 *       ? TakeWhileImpl<tail, fn, [...index, any], [...output, head]>
 *       : output
 *     : output
 */

// ✓ TakeWhile: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TakeWhile(fn: Fn, tuple = unset): any {
  return PartialApply(TakeWhileFn, [fn, tuple])
}
/* compiles to:
 * export type TakeWhile<fn extends Fn, tuple = unset> = PartialApply<TakeWhileFn, [fn, tuple]>
 */

// ✓ Some: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Some(fn: Fn, tuple = unset): any {
  return PartialApply(SomeFn, [fn, tuple])
}
/* compiles to:
 * export type Some<fn extends Fn, tuple = unset> = PartialApply<SomeFn, [fn, tuple]>
 */

// ✓ Every: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Every(fn: Fn, tuple = unset): any {
  return PartialApply(EveryFn, [fn, tuple])
}
/* compiles to:
 * export type Every<fn extends Fn, tuple = unset> = PartialApply<EveryFn, [fn, tuple]>
 */

// ✗ SortImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function SortImpl(xs: any[], predicateFn: Fn): any {
  const m1 = matches<[ Hole<"head">, ...Hole<"tail"> ]>(xs)
  if (m1) {
    const m2 = matches<[ Hole<"left", any[]>, Hole<"right", any[]> ]>(Call(t<Tuples.Partition<PartialApply<typeof predicateFn, [ _, typeof m1.head ]>, typeof m1.tail>>()))
    if (m2) {
      return [...SortImpl(m2.left, predicateFn), m1.head, ...SortImpl(m2.right, predicateFn)]
    }
    return never
  }
  return []
}
/* compiles to:
 * export type SortImpl<xs extends any[], predicateFn extends Fn> =
 *   xs extends [infer head, ...infer tail]
 *     ? Call<Tuples.Partition<PartialApply<predicateFn, [_, head]>, tail>> extends [infer left extends any[], infer right extends any[]]
 *       ? [...SortImpl<left, predicateFn>, head, ...SortImpl<right, predicateFn>]
 *       : never
 *     : []
 */

// ✗ Join: does not compile yet
//   Cannot find name 'JoinFn'.
/* @scripttype preserveParamNames */
export function Join(Sep: string | _ | unset = unset, Tuple = unset): any {
  return PartialApply(JoinFn, [Sep, Tuple])
}
/* compiles to:
 * export type Join<Sep extends string | _ | unset = unset, Tuple = unset> = PartialApply<
 *   JoinFn,
 *   [Sep, Tuple]
 * >
 */

// ✗ Prepend: does not compile yet
//   Cannot find name 'PrependFn'.
/* @scripttype preserveParamNames */
export function Prepend(element = unset, tuple = unset): any {
  return PartialApply(PrependFn, [element, tuple])
}
/* compiles to:
 * export type Prepend<element = unset, tuple = unset> = PartialApply<PrependFn, [element, tuple]>
 */

// ✗ Append: does not compile yet
//   Cannot find name 'AppendFn'.
/* @scripttype preserveParamNames */
export function Append(element = unset, tuple = unset): any {
  return PartialApply(AppendFn, [element, tuple])
}
/* compiles to:
 * export type Append<element = unset, tuple = unset> = PartialApply<AppendFn, [element, tuple]>
 */

// ✗ Concat: does not compile yet
//   Cannot find name 'ConcatFn'.
/* @scripttype preserveParamNames */
export function Concat(tuple1 = unset, tuple2 = unset): any {
  return PartialApply(ConcatFn, [tuple1, tuple2])
}
/* compiles to:
 * export type Concat<tuple1 = unset, tuple2 = unset> = PartialApply<ConcatFn, [tuple1, tuple2]>
 */

// ✗ Partition: does not compile yet
//   Cannot find name 'PartitionFn'.
/* @scripttype preserveParamNames */
export function Partition(fn: Fn, tuple = unset): any {
  return PartialApply(PartitionFn, [fn, tuple])
}
/* compiles to:
 * export type Partition<fn extends Fn, tuple = unset> = PartialApply<PartitionFn, [fn, tuple]>
 */

// ✗ PartitionImpl: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function PartitionImpl(fn: Fn, tuple: any[], left: any[] = [], right: any[] = []): any {
  const m1 = matches<[ Hole<"first">, ...Hole<"rest"> ]>(tuple)
  if (m1) {
    if (matches<true>(Call(fn, m1.first))) {
      return PartitionImpl(fn, m1.rest, [...left, m1.first], right)
    }
    return PartitionImpl(fn, m1.rest, left, [...right, m1.first])
  }
  return [left, right]
}
/* compiles to:
 * export type PartitionImpl<
 *   fn extends Fn,
 *   tuple extends any[],
 *   left extends any[] = [],
 *   right extends any[] = []
 * > =
 *   tuple extends [infer first, ...infer rest]
 *     ? Call<fn, first> extends true
 *       ? PartitionImpl<fn, rest, [...left, first], right>
 *       : PartitionImpl<fn, rest, left, [...right, first]>
 *     : [left, right]
 */

// ✓ SplitAt: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SplitAt(index: number | unset | _ = unset, tuple: unknown[] | unset | _ = unset): any {
  return PartialApply(SplitAtFn, [index, tuple])
}
/* compiles to:
 * export type SplitAt<
 *   index extends number | unset | _ = unset,
 *   tuple extends unknown[] | unset | _ = unset
 * > =
 *   PartialApply<SplitAtFn, [index, tuple]>
 */

// ✗ Zip: does not compile yet
//   Cannot find name 'ZipWithFn'.
/* @scripttype preserveParamNames */
export function Zip(arr0: unknown[] | _ | unset = unset, arr1: unknown[] | _ | unset = unset, arr2: unknown[] | _ | unset = unset, arr3: unknown[] | _ | unset = unset, arr4: unknown[] | _ | unset = unset, arr5: unknown[] | _ | unset = unset, arr6: unknown[] | _ | unset = unset, arr7: unknown[] | _ | unset = unset, arr8: unknown[] | _ | unset = unset, arr9: unknown[] | _ | unset = unset): any {
  return PartialApply(ZipWithFn(args), [arr0, arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8, arr9])
}
/* compiles to:
 * export type Zip<
 *   arr0 extends unknown[] | _ | unset = unset,
 *   arr1 extends unknown[] | _ | unset = unset,
 *   arr2 extends unknown[] | _ | unset = unset,
 *   arr3 extends unknown[] | _ | unset = unset,
 *   arr4 extends unknown[] | _ | unset = unset,
 *   arr5 extends unknown[] | _ | unset = unset,
 *   arr6 extends unknown[] | _ | unset = unset,
 *   arr7 extends unknown[] | _ | unset = unset,
 *   arr8 extends unknown[] | _ | unset = unset,
 *   arr9 extends unknown[] | _ | unset = unset
 * > =
 *   PartialApply<ZipWithFn<args>, [arr0, arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8, arr9]>
 */

// ✗ ZipWith: does not compile yet
//   Cannot find name 'ZipWithFn'.
/* @scripttype preserveParamNames */
export function ZipWith(fn: Fn, arr0: unknown[] | _ | unset = unset, arr1: unknown[] | _ | unset = unset, arr2: unknown[] | _ | unset = unset, arr3: unknown[] | _ | unset = unset, arr4: unknown[] | _ | unset = unset, arr5: unknown[] | _ | unset = unset, arr6: unknown[] | _ | unset = unset, arr7: unknown[] | _ | unset = unset, arr8: unknown[] | _ | unset = unset, arr9: unknown[] | _ | unset = unset): any {
  return PartialApply(ZipWithFn(fn), [arr0, arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8, arr9])
}
/* compiles to:
 * export type ZipWith<
 *   fn extends Fn,
 *   arr0 extends unknown[] | _ | unset = unset,
 *   arr1 extends unknown[] | _ | unset = unset,
 *   arr2 extends unknown[] | _ | unset = unset,
 *   arr3 extends unknown[] | _ | unset = unset,
 *   arr4 extends unknown[] | _ | unset = unset,
 *   arr5 extends unknown[] | _ | unset = unset,
 *   arr6 extends unknown[] | _ | unset = unset,
 *   arr7 extends unknown[] | _ | unset = unset,
 *   arr8 extends unknown[] | _ | unset = unset,
 *   arr9 extends unknown[] | _ | unset = unset
 * > =
 *   PartialApply<ZipWithFn<fn>, [arr0, arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8, arr9]>
 */

// ✓ GroupByImplRec: verified type-identical to the original
/* @scripttype preserveParamNames */
export function GroupByImplRec(xs, fn: Fn, acc = {}): any {
  const m1 = matches<[ Hole<"first">, ...Hole<"rest"> ]>(xs)
  if (m1) {
    const m2 = matches<Hole<"key", PropertyKey>>(Call(fn, m1.first))
    if (m2) {
      const out = emptyObject
      for (const K in keySet(m2.key)) {
        out[K] = [...m2.key in acc ? Extract(acc[m2.key], readonlyArrayOf(any)) : [], m1.first]
      }
      return GroupByImplRec(m1.rest, fn, merge(t<Std._Omit<typeof acc, typeof m2.key>>(), out))
    }
    return never
  }
  return acc
}
/* compiles to:
 * export type GroupByImplRec<xs, fn extends Fn, acc = {}> =
 *   xs extends [infer first, ...infer rest]
 *     ? Call<fn, first> extends (infer key extends PropertyKey)
 *       ? GroupByImplRec<
 *         rest,
 *         fn,
 *         & Std._Omit<acc, key>
 *         & {
 *             [K in key]: [
 *               ...(key extends keyof acc ? Extract<acc[key], readonly any[]> : []),
 *               first
 *             ]
 *           }
 *       >
 *       : never
 *     : acc
 */

// ✗ GroupByImpl: does not compile yet
//   Cannot find name 'GroupByImplRec'.
/* @scripttype preserveParamNames */
export function GroupByImpl(xs, fn: Fn): any {
  return Prettify(GroupByImplRec(xs, fn))
}
/* compiles to:
 * export type GroupByImpl<xs, fn extends Fn> = Prettify<GroupByImplRec<xs, fn>>
 */

// ✗ Range: does not compile yet
//   Cannot find name 'RangeFn'.
/* @scripttype preserveParamNames */
export function Range(start: number | _ | unset = unset, end: number | _ | unset = unset): any {
  return PartialApply(RangeFn, [start, end])
}
/* compiles to:
 * export type Range<
 *   start extends number | _ | unset = unset,
 *   end extends number | _ | unset = unset
 * > =
 *   PartialApply<RangeFn, [start, end]>
 */

// ✓ RangeImpl: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RangeImpl(start: number, length: number): any {
  let output: any[] = []
  while (true) {
    if (matches<typeof length>(output['length'])) {
      break
    }
    output.push(Call(t<Numbers.Add<typeof start, (typeof output)["length"]>>()))
  }
  return output
}
/* compiles to:
 * export type RangeImpl<start extends number, length extends number> = RangeImpl__loop<
 *   [],
 *   length,
 *   start
 * >
 * type RangeImpl__loop<Output extends any[], Length extends number, Start extends number> =
 *   Output['length'] extends Length
 *     ? Output
 *     : RangeImpl__loop<[...Output, Call<Numbers.Add<Start, Output['length']>>], Length, Start>
 */

// ✗ Length: does not compile yet
//   Cannot find name 'LengthFn'.
/* @scripttype preserveParamNames */
export function Length(tuple: readonly any[] | _ | unset = unset): any {
  return PartialApply(LengthFn, [tuple])
}
/* compiles to:
 * export type Length<tuple extends readonly any[] | _ | unset = unset> = PartialApply<
 *   LengthFn,
 *   [tuple]
 * >
 */

// ✗ Min: does not compile yet
//   Cannot find name 'MinFn'.
/* @scripttype preserveParamNames */
export function Min(tuple: readonly any[] | _ | unset = unset): any {
  return PartialApply(MinFn, [tuple])
}
/* compiles to:
 * export type Min<tuple extends readonly any[] | _ | unset = unset> = PartialApply<MinFn, [tuple]>
 */

// ✓ MinImpl: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MinImpl(xs): any {
  let min = never
  let xs_ = xs
  while (true) {
    const m1 = matches<[ Hole<"first", number | bigint>, ...Hole<"rest"> ]>(xs_)
    if (!m1) {
      break
    }
    xs_ = m1.rest
    min = matches<[ never ]>([min]) ? m1.first : t<NumberImpls.Min<typeof m1.first, typeof min>>()
  }
  return min
}
/* compiles to:
 * export type MinImpl<xs> = MinImpl__loop<xs, never>
 * type MinImpl__loop<Xs_, Min> =
 *   Xs_ extends [infer first extends number | bigint, ...infer rest]
 *     ? MinImpl__loop<rest, [Min] extends [never] ? first : NumberImpls.Min<first, Min>>
 *     : Min
 */

// ✗ Max: does not compile yet
//   Cannot find name 'MaxFn'.
/* @scripttype preserveParamNames */
export function Max(tuple: readonly any[] | _ | unset = unset): any {
  return PartialApply(MaxFn, [tuple])
}
/* compiles to:
 * export type Max<tuple extends readonly any[] | _ | unset = unset> = PartialApply<MaxFn, [tuple]>
 */

// ✓ MaxImpl: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MaxImpl(xs): any {
  let min = never
  let xs_ = xs
  while (true) {
    const m1 = matches<[ Hole<"first", number | bigint>, ...Hole<"rest"> ]>(xs_)
    if (!m1) {
      break
    }
    xs_ = m1.rest
    min = matches<[ never ]>([min]) ? m1.first : t<NumberImpls.Max<typeof m1.first, typeof min>>()
  }
  return min
}
/* compiles to:
 * export type MaxImpl<xs> = MaxImpl__loop<xs, never>
 * type MaxImpl__loop<Xs_, Min> =
 *   Xs_ extends [infer first extends number | bigint, ...infer rest]
 *     ? MaxImpl__loop<rest, [Min] extends [never] ? first : NumberImpls.Max<first, Min>>
 *     : Min
 */
