/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/Function/Compose.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const ComposeListAsync: any
declare const ComposeListSync: any
declare const ComposeMultiAsync: any
declare const ComposeMultiSync: any
declare const Input: any
declare const IntersectOf: any
declare const Mode: any
type ComposeListAsync<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ComposeListSync<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ComposeMultiAsync<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ComposeMultiSync<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Input<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type IntersectOf<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Mode<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ Compose: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Compose(mode: Mode = 'sync', input: Input = 'multi') {
  return IntersectOf({ 'sync': { 'multi': ComposeMultiSync, 'list': ComposeListSync }, 'async': { 'multi': ComposeMultiAsync, 'list': ComposeListAsync } }[mode][input])
}
/* compiles to:
 * export type Compose<mode extends Mode = 'sync', input extends Input = 'multi'> = IntersectOf<
 *   {
 *     sync: { multi: ComposeMultiSync; list: ComposeListSync }
 *     async: { multi: ComposeMultiAsync; list: ComposeListAsync }
 *   }[mode][input]
 * >
 */
