/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/Function/Narrow.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Narrowable: any
declare const Try: any
type Narrowable<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Try<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ NarrowRaw: verified type-identical to the original
/* @scripttype preserveParamNames */
export function NarrowRaw(A) {
  const out = emptyObject
  for (const K in keyof(A)) {
    out[K] = matches<Function>(A[K]) ? A[K] : NarrowRaw(A[K])
  }
  return (matches<[ ]>(A) ? [] : never) | (matches<Narrowable>(A) ? A : never) | out
}
/* compiles to:
 * export type NarrowRaw<A> =
 *   | (A extends [] ? [] : never)
 *   | (A extends Narrowable ? A : never)
 *   | { [K in keyof A]: A[K] extends Function ? A[K] : NarrowRaw<A[K]> }
 */

// ✓ Narrow: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Narrow(A: any) {
  return Try(A, [], NarrowRaw(A))
}
/* compiles to:
 * export type Narrow<A extends any> = Try<A, [], NarrowRaw<A>>
 */
