/**
 * ScriptType for 03-schema-and-type-level-parsers/arktype/ark/schema/shared/disjoint.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ writeUnsatisfiableExpressionError: verified type-identical to the original
/* @scripttype preserveParamNames */
export function writeUnsatisfiableExpressionError(expression: string) {
  return `${expression} results in an unsatisfiable type`
}
/* compiles to:
 * export type writeUnsatisfiableExpressionError<expression extends string> = `${expression} results in an unsatisfiable type`
 */
