/**
 * ScriptType for 02-inference-at-scale/hono/src/helper/factory/index.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Env: any
declare const Hono: any
type Env<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Hono<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ InitApp: verified type-identical to the original
/* @scripttype preserveParamNames */
export function InitApp(E: Env = Env) {
  return fnType([Hono(E)], voidType())
}
/* compiles to:
 * export type InitApp<E extends Env = Env> = (a0: Hono<E>) => void
 */
