/**
 * ScriptType for 03-schema-and-type-level-parsers/arktype/ark/type/parser/shift/tokens.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 compile-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { TerminatingChar } from '../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/parser/shift/tokens.js'
declare namespace Scanner {
  export type skipWhitespace<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m1 {
  export type nextUnscanned<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const Scanner: any
declare const TerminatingChar: any
declare const skipWhitespace: any
type Scanner<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type skipWhitespace<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✗ lookaheadIsFinalizing: does not compile yet
//   Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.   Type 'symbol' is not assignable to type 'st
/* @scripttype preserveParamNames */
export function lookaheadIsFinalizing(lookahead: string, unscanned: string): any {
  if (matches<">">(lookahead)) {
    const m1 = matches<`=${Hole<"nextUnscanned">}`>(unscanned)
    if (m1) {
      if (matches<`=${string}`>(m1.nextUnscanned)) {
        return true
      }
      return false
    }
    if (matches<("" | `${TerminatingChar}${string}`)>(t<Scanner.skipWhitespace<typeof unscanned>>())) {
      return true
    }
    return false
  }
  if (matches<"=">(lookahead)) {
    if (matches<`=${string}`>(unscanned)) {
      return false
    }
    return true
  }
  if (matches<"," | "?">(lookahead)) {
    return true
  }
  return false
}
/* compiles to:
 * export type lookaheadIsFinalizing<lookahead extends string, unscanned extends string> =
 *   lookahead extends '>'
 *     ? unscanned extends `=${infer nextUnscanned}`
 *       ? nextUnscanned extends `=${string}` ? true : false
 *     : Scanner.skipWhitespace<unscanned> extends '' | `${TerminatingChar}${string}` ? true
 *     : false
 *   : lookahead extends '=' ? unscanned extends `=${string}` ? false : true
 *   : lookahead extends ',' | '?' ? true
 *   : false
 */
