/**
 * ScriptType for 02-inference-at-scale/trpc/packages/client/src/links/internals/httpUtils.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const AnyClientTypes: any
declare const FetchEsque: any
declare const TransformerOptions: any
declare const URL: any
type AnyClientTypes<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type FetchEsque<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TransformerOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type URL<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ HTTPLinkBaseOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function HTTPLinkBaseOptions(TRoot: Pick<AnyClientTypes, 'transformer'>) {
  return merge({ url: string | URL, fetch: optional(FetchEsque), methodOverride: optional('POST') }, TransformerOptions(TRoot))
}
/* compiles to:
 * export type HTTPLinkBaseOptions<TRoot extends Pick<AnyClientTypes, 'transformer'>> = { url: string | URL; fetch?: FetchEsque; methodOverride?: 'POST' } & TransformerOptions<TRoot>
 */
