/**
 * ScriptType for 02-inference-at-scale/trpc/packages/client/src/links/internals/urlWithConnectionParams.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 typecheck-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✗ CallbackOrValue: the ScriptType does not itself typecheck as TypeScript
//   CallbackOrValue.st.ts(3:29) TS2348: Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
/* @scripttype preserveParamNames */
export function CallbackOrValue(T) {
  return T | fnType([], T | Promise(T))
}
/* compiles to:
 * export type CallbackOrValue<T> = T | (() => T | Promise<T>)
 */
