/**
 * ScriptType for 06-state-and-forms/redux-toolkit/packages/toolkit/src/configureStore.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Action: any
declare const Enhancers: any
declare const ExtractStateExtensions: any
declare const ExtractStoreExtensions: any
declare const Middleware: any
declare const Store: any
declare const UnknownAction: any
declare const UnknownIfNonSpecific: any
type Action<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Enhancers<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ExtractStateExtensions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ExtractStoreExtensions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Middleware<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Store<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type UnknownAction<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type UnknownIfNonSpecific<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ Middlewares: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Middlewares(S) {
  return readonlyArrayOf(Middleware({}, S))
}
/* compiles to:
 * export type Middlewares<S> = readonly Middleware<{}, S>[]
 */

// ✓ EnhancedStore: verified type-identical to the original
/* @scripttype preserveParamNames */
export function EnhancedStore(S = any, A: Action = UnknownAction, E: Enhancers = Enhancers) {
  return ExtractStoreExtensions(E) & Store(S, A, UnknownIfNonSpecific(ExtractStateExtensions(E)))
}
/* compiles to:
 * export type EnhancedStore<
 *   S = any,
 *   A extends Action = UnknownAction,
 *   E extends Enhancers = Enhancers
 * > =
 *   ExtractStoreExtensions<E> & Store<S, A, UnknownIfNonSpecific<ExtractStateExtensions<E>>>
 */
