/**
 * ScriptType for 01-type-level-programming/hotscript/src/internals/numbers/impl/absolute.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ Abs: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Abs(T: number | bigint) {
  const m1 = matches<`-${Hole<"U", number | bigint>}`>(`${T}`)
  if (m1) {
    return m1.U
  }
  return T
}
/* compiles to:
 * export type Abs<T extends number | bigint> = `${T}` extends `-${infer U extends number | bigint}` ? U : T
 */
