/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/script/token/internal/take.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ TTakeVariant: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TTakeVariant(Variant: string, Input: string) {
  const m1 = matches<`${typeof Variant}${Hole<"Rest", string>}`>(Input)
  if (m1) {
    return [Variant, m1.Rest]
  }
  return []
}
/* compiles to:
 * export type TTakeVariant<Variant extends string, Input extends string> = Input extends `${Variant}${infer Rest extends string}` ? [Variant, Rest] : []
 */

// ✓ TTake: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TTake(Variants: string[], Input: string) {
  const m1 = matches<[ Hole<"ValueLeft", string>, ...Hole<"ValueRight", string[]> ]>(Variants)
  if (m1) {
    const m2 = matches<[ Hole<"Take", string>, Hole<"Rest", string> ]>(TTakeVariant(m1.ValueLeft, Input))
    if (m2) {
      return [m2.Take, m2.Rest]
    }
    return TTake(m1.ValueRight, Input)
  }
  return []
}
/* compiles to:
 * export type TTake<Variants extends string[], Input extends string> = Variants extends [infer ValueLeft extends string, ...(infer ValueRight extends string[])] ? TTakeVariant<ValueLeft, Input> extends [infer Take extends string, infer Rest extends string] ? [Take, Rest] : TTake<ValueRight, Input> : []
 */
