/**
 * ScriptType for 04-query-builders-orm/kysely/src/query-builder/cte-builder.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 raw
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const CTEBuilder: any
type CTEBuilder<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ CTEBuilderCallback: uses raw() — language gap, does not count as covered
//   gap: generic function type
/* @scripttype preserveParamNames */
export function CTEBuilderCallback(N: string) {
  return fnType([raw('<N2 extends string>(name: N2) => CTEBuilder<N2>')], CTEBuilder(N))
}
