/**
 * ScriptType for 04-query-builders-orm/drizzle-orm/drizzle-orm/src/mysql-core/columns/double.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const MySqlDoubleBuilder: any
type MySqlDoubleBuilder<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ MySqlDoubleBuilderInitial: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MySqlDoubleBuilderInitial(TName: string) {
  return MySqlDoubleBuilder({ name: TName, dataType: 'number', columnType: 'MySqlDouble', data: number, driverParam: number | string, enumValues: Undefined })
}
/* compiles to:
 * export type MySqlDoubleBuilderInitial<TName extends string> = MySqlDoubleBuilder<
 *   {
 *     name: TName
 *     dataType: 'number'
 *     columnType: 'MySqlDouble'
 *     data: number
 *     driverParam: number | string
 *     enumValues: undefined
 *   }
 * >
 */
