/**
 * ScriptType for 03-schema-and-type-level-parsers/arktype/ark/type/parser/shift/operand/unenclosed.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 10 type-level aliases: 7 covered, 2 compile-error, 1 mismatch
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { GenericAst, genericParamNames } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/schema/generic.js'
import type { resolvableReferenceIn } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/schema/scope.js'
import type { GenericInstantiationAst } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/parser/ast/generic.js'
import type { InferredAst } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/parser/ast/infer.js'
import type { StaticState } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/parser/reduce/static.js'
import type { ParsedArgs } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/parser/shift/operand/genericArgs.js'
import type { TerminatingChar } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/parser/shift/tokens.js'
import type { BaseCompletions } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/parser/string.js'
import type { resolutionToAst } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/type/scope.js'
import type { lastOf } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/util/arrays.js'
import type { BigintLiteral, NumberLiteral } from '../../../../../../../../03-schema-and-type-level-parsers/arktype/ark/util/numbers.js'
declare namespace ArkAmbient {
  export type $<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace Scanner {
  export type shift<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type shiftResult<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type shiftUntil<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type skipWhitespace<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m1 {
  export type ast<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type n<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type nestedReference<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type nestedSubmodule<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type token<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type unscanned<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m2 {
  export type name<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type reference<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type result<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type s<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type submodule<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m3 {
  export type argAsts<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type nextUnscanned<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type reference<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type submodule<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m4 {
  export type b<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace s {
  export type addPrefix<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type completion<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type error<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type from<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type scanTo<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type setRoot<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const ArkAmbient: any
declare const BaseCompletions: any
declare const BigintLiteral: any
declare const GenericAst: any
declare const GenericInstantiationAst: any
declare const InferredAst: any
declare const NumberLiteral: any
declare const ParsedArgs: any
declare const Scanner: any
declare const StaticState: any
declare const TerminatingChar: any
declare const addPrefix: any
declare const argAsts: any
declare const arkKind: any
declare const ast: any
declare const b: any
declare const completion: any
declare const from: any
declare const genericParamNames: any
declare const lastOf: any
declare const n: any
declare const nextUnscanned: any
declare const parseGenericArgs: any
declare const resolutionToAst: any
declare const resolvableReferenceIn: any
declare const scanTo: any
declare const setRoot: any
declare const shift: any
declare const shiftResult: any
declare const shiftUntil: any
declare const skipWhitespace: any
declare const writeInvalidGenericArgCountMessage: any
declare const writeNonSubmoduleDotMessage: any
declare const writePrefixedPrivateReferenceMessage: any
declare const writeUnresolvableMessage: any
type ArkAmbient<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Scanner<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type addPrefix<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type argAsts<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type arkKind<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ast<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type b<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type completion<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type from<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type n<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type nextUnscanned<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type parseGenericArgs<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type qualifiedReference<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type scanTo<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type setRoot<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type shift<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type shiftResult<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type shiftUntil<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type skipWhitespace<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type validReferenceFromToken<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type writeInvalidGenericArgCountMessage<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type writeNonSubmoduleDotMessage<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type writePrefixedPrivateReferenceMessage<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type writeUnresolvableMessage<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✗ parseUnenclosed: does not compile yet
//   Type 'unscanned' does not satisfy the constraint 'string'.
/* @scripttype preserveParamNames */
export function parseUnenclosed(s: StaticState, $, args): any {
  const m1 = matches<(Scanner.shiftResult<Hole<"token">, Hole<"unscanned">>)>(t<Scanner.shiftUntil<(typeof s)["unscanned"], TerminatingChar>>())
  if (m1) {
    const m2 = matches<s.from<Hole<"s">>>(tryResolve(s, m1.unscanned, m1.token, $, args))
    if (m2) {
      return m2.s
    }
    return never
  }
  return never
}
/* compiles to:
 * export type parseUnenclosed<s extends StaticState, $, args> =
 *   Scanner.shiftUntil<s['unscanned'], TerminatingChar> extends Scanner.shiftResult<infer token, infer unscanned>
 *     ? tryResolve<s, unscanned, token, $, args> extends s.from<infer s> ? s : never
 *     : never
 */

// ✓ parseResolution: verified type-identical to the original
/* @scripttype preserveParamNames */
export function parseResolution(s: StaticState, unscanned: string, alias: string, resolution, $, args): any {
  const m1 = matches<Hole<"ast">>(resolutionToAst(alias, resolution))
  if (m1) {
    if (matches<GenericAst>(m1.ast)) {
      return parseGenericInstantiation(alias, m1.ast, t<s.scanTo<typeof s, typeof unscanned>>(), $, args)
    }
    return t<s.setRoot<typeof s, typeof m1.ast, typeof unscanned>>()
  }
  return never
}
/* compiles to:
 * export type parseResolution<
 *   s extends StaticState,
 *   unscanned extends string,
 *   alias extends string,
 *   resolution,
 *   $,
 *   args
 * > =
 *   resolutionToAst<alias, resolution> extends infer ast
 *     ? ast extends GenericAst
 *       ? parseGenericInstantiation<alias, ast, s.scanTo<s, unscanned>, $, args>
 *       : s.setRoot<s, ast, unscanned>
 *     : never
 */

// ✓ parseGenericInstantiation: verified type-identical to the original
/* @scripttype preserveParamNames */
export function parseGenericInstantiation(name: string, g: GenericAst, s: StaticState, $, args): any {
  const m1 = matches<`<${Hole<"unscanned">}`>(t<Scanner.skipWhitespace<(typeof s)["unscanned"]>>())
  if (m1) {
    const m2 = matches<Hole<"result">>(parseGenericArgs(name, g, m1.unscanned, $, args))
    if (m2) {
      const m3 = matches<ParsedArgs<Hole<"argAsts">, Hole<"nextUnscanned">>>(m2.result)
      if (m3) {
        return t<s.setRoot<typeof s, GenericInstantiationAst<typeof g, typeof m3.argAsts>, typeof m3.nextUnscanned>>()
      }
      return m2.result
    }
    return never
  }
  return t<s.error<writeInvalidGenericArgCountMessage<typeof name, genericParamNames<(typeof g)["paramsAst"]>, [ ]>>>()
}
/* compiles to:
 * export type parseGenericInstantiation<
 *   name extends string,
 *   g extends GenericAst,
 *   s extends StaticState,
 *   $,
 *   args
 * > =
 *   Scanner.skipWhitespace<s['unscanned']> extends `<${infer unscanned}`
 *     ? parseGenericArgs<name, g, unscanned, $, args> extends infer result
 *       ? result extends ParsedArgs<infer argAsts, infer nextUnscanned>
 *         ? s.setRoot<s, GenericInstantiationAst<g, argAsts>, nextUnscanned>
 *         : result
 *       : never
 *     : s.error<writeInvalidGenericArgCountMessage<name, genericParamNames<g['paramsAst']>, []>>
 */

// ✓ tryResolve: verified type-identical to the original
/* @scripttype preserveParamNames */
export function tryResolve(s: StaticState, unscanned: string, token: string, $, args): any {
  if (token in args) {
    return parseResolution(s, unscanned, token, args[token], $, args)
  }
  if (token in $) {
    return parseResolution(s, unscanned, token, $[token], $, args)
  }
  if (token in t<ArkAmbient.$>()) {
    return parseResolution(s, unscanned, token, t<ArkAmbient.$>()[token], $, args)
  }
  if (`#${token}` in $) {
    return parseResolution(s, unscanned, token, $[`#${token}`], $, args)
  }
  const m1 = matches<NumberLiteral<Hole<"n">>>(token)
  if (m1) {
    return t<s.setRoot<typeof s, InferredAst<typeof m1.n, typeof token>, typeof unscanned>>()
  }
  const m2 = matches<(`${Hole<"submodule", keyof typeof $ & string>}.${Hole<"reference">}`)>(token)
  if (m2) {
    return tryResolveSubmodule(token, $[m2.submodule], m2.reference, s, unscanned, $, args, [m2.submodule])
  }
  const m3 = matches<(`${Hole<"submodule", keyof ArkAmbient.$ & string>}.${Hole<"reference">}`)>(token)
  if (m3) {
    return tryResolveSubmodule(token, t<ArkAmbient.$>()[m3.submodule], m3.reference, s, unscanned, $, args, [m3.submodule])
  }
  const m4 = matches<BigintLiteral<Hole<"b">>>(token)
  if (m4) {
    return t<s.setRoot<typeof s, InferredAst<typeof m4.b, typeof token>, typeof unscanned>>()
  }
  if (matches<"keyof">(token)) {
    return t<s.addPrefix<typeof s, "keyof", typeof unscanned>>()
  }
  return unresolvableState(s, token, $, args, [])
}
/* compiles to:
 * export type tryResolve<
 *   s extends StaticState,
 *   unscanned extends string,
 *   token extends string,
 *   $,
 *   args
 * > =
 *   token extends keyof args ? parseResolution<s, unscanned, token, args[token], $, args>
 *   : token extends keyof $ ? parseResolution<s, unscanned, token, $[token], $, args>
 *   : token extends keyof ArkAmbient.$
 *     ? parseResolution<s, unscanned, token, ArkAmbient.$[token], $, args>
 *   : `#${token}` extends keyof $ ? parseResolution<s, unscanned, token, $[`#${token}`], $, args>
 *   : token extends NumberLiteral<infer n> ? s.setRoot<s, InferredAst<n, token>, unscanned>
 *   : token extends `${infer submodule extends keyof $ & string}.${infer reference}`
 *     ? tryResolveSubmodule<token, $[submodule], reference, s, unscanned, $, args, [submodule]>
 *   : token extends `${infer submodule extends keyof ArkAmbient.$ & string}.${infer reference}`
 *     ? tryResolveSubmodule<
 *       token,
 *       ArkAmbient.$[submodule],
 *       reference,
 *       s,
 *       unscanned,
 *       $,
 *       args,
 *       [submodule]
 *     >
 *   : token extends BigintLiteral<infer b> ? s.setRoot<s, InferredAst<b, token>, unscanned>
 *   : token extends 'keyof' ? s.addPrefix<s, 'keyof', unscanned>
 *   : unresolvableState<s, token, $, args, []>
 */

// ✓ tryResolveSubmodule: verified type-identical to the original
/* @scripttype preserveParamNames */
export function tryResolveSubmodule(token: string, resolution, reference: string, s: StaticState, unscanned: string, $, args, submodulePath: string[]): any {
  if (matches<{ [arkKind]: "module"; }>(resolution)) {
    if (reference in resolution) {
      return parseResolution(s, unscanned, token, resolution[reference], $, args)
    }
    const m1 = matches<(`${Hole<"nestedSubmodule", keyof typeof resolution & string>}.${Hole<"nestedReference">}`)>(reference)
    if (m1) {
      return tryResolveSubmodule(token, resolution[m1.nestedSubmodule], m1.nestedReference, s, unscanned, $, args, [...submodulePath, m1.nestedSubmodule])
    }
    return unresolvableState(s, reference, resolution, {}, submodulePath)
  }
  return t<s.error<writeNonSubmoduleDotMessage<lastOf<typeof submodulePath>>>>()
}
/* compiles to:
 * export type tryResolveSubmodule<
 *   token extends string,
 *   resolution,
 *   reference extends string,
 *   s extends StaticState,
 *   unscanned extends string,
 *   $,
 *   args,
 *   submodulePath extends string[]
 * > =
 *   resolution extends { [arkKind]: "module"; }
 *     ? reference extends keyof resolution
 *       ? parseResolution<s, unscanned, token, resolution[reference], $, args>
 *     : reference extends `${infer nestedSubmodule extends keyof resolution & string}.${infer nestedReference}`
 *       ? tryResolveSubmodule<
 *         token,
 *         resolution[nestedSubmodule],
 *         nestedReference,
 *         s,
 *         unscanned,
 *         $,
 *         args,
 *         [...submodulePath, nestedSubmodule]
 *       >
 *     : unresolvableState<s, reference, resolution, {}, submodulePath>
 *     : s.error<writeNonSubmoduleDotMessage<lastOf<submodulePath>>>
 */

// ✗ unresolvableState: does not compile yet
//   Type 'name' does not satisfy the constraint 'string'.
/* @scripttype preserveParamNames */
export function unresolvableState(s: StaticState, token: string, resolutions, args, submodulePath: string[]): any {
  const m1 = matches<[ "", Scanner.shift<"#", Hole<"unscanned">> ]>([token, s['unscanned']])
  if (m1) {
    const m2 = matches<(Scanner.shiftResult<Hole<"name">, string>)>(t<Scanner.shiftUntil<typeof m1.unscanned, TerminatingChar>>())
    if (m2) {
      return t<s.error<writePrefixedPrivateReferenceMessage<typeof m2.name>>>()
    }
    return never
  }
  if (matches<(never)>(validReferenceFromToken(token, resolutions, args, submodulePath))) {
    return t<s.error<writeUnresolvableMessage<qualifiedReference<typeof token, typeof submodulePath>>>>()
  }
  return t<s.completion<`${(typeof s)["scanned"]}${qualifiedReference<validReferenceFromToken<typeof token, typeof resolutions, typeof args, typeof submodulePath>, typeof submodulePath>}`>>()
}
/* compiles to:
 * export type unresolvableState<
 *   s extends StaticState,
 *   token extends string,
 *   resolutions,
 *   args,
 *   submodulePath extends string[]
 * > =
 *   [token, s['unscanned']] extends ['', Scanner.shift<'#', infer unscanned>]
 *     ? Scanner.shiftUntil<unscanned, TerminatingChar> extends Scanner.shiftResult<infer name, string>
 *       ? s.error<writePrefixedPrivateReferenceMessage<name>>
 *       : never
 *   : validReferenceFromToken<token, resolutions, args, submodulePath> extends never
 *     ? s.error<writeUnresolvableMessage<qualifiedReference<token, submodulePath>>>
 *   : s.completion<
 *     `${s['scanned']}${qualifiedReference<validReferenceFromToken<token, resolutions, args, submodulePath>, submodulePath>}`
 *   >
 */

// ✗ qualifiedReference: compiles but is not type-identical yet
//   eq=false
/* @scripttype preserveParamNames */
export function qualifiedReference(reference: string, submodulePath: string[]): any {
  return join([...submodulePath, reference], '.')
}
/* compiles to:
 * export type qualifiedReference<reference extends string, submodulePath extends string[]> = Join<
 *   [...submodulePath, reference],
 *   '.'
 * >
 */

// ✓ validReferenceFromToken: verified type-identical to the original
/* @scripttype preserveParamNames */
export function validReferenceFromToken(token: string, $, args, submodulePath: string[]): any {
  return Extract(matches<0>(submodulePath['length']) ? BaseCompletions($, args) : resolvableReferenceIn($), `${token}${string}`)
}
/* compiles to:
 * export type validReferenceFromToken<
 *   token extends string,
 *   $,
 *   args,
 *   submodulePath extends string[]
 * > =
 *   Extract<
 *     submodulePath['length'] extends 0 ? BaseCompletions<$, args> : resolvableReferenceIn<$>,
 *     `${token}${string}`
 *   >
 */

// ✓ writeMissingRightOperandMessage: verified type-identical to the original
/* @scripttype preserveParamNames */
export function writeMissingRightOperandMessage(token: string, unscanned: string = ''): any {
  return `Token '${token}' requires a right operand${matches<"">(unscanned) ? '' : ` before '${unscanned}'`}`
}
/* compiles to:
 * export type writeMissingRightOperandMessage<
 *   token extends string,
 *   unscanned extends string = ''
 * > =
 *   `Token '${token}' requires a right operand${unscanned extends '' ? '' : ` before '${unscanned}'`}`
 */

// ✓ writeExpressionExpectedMessage: verified type-identical to the original
/* @scripttype preserveParamNames */
export function writeExpressionExpectedMessage(unscanned: string): any {
  return `Expected an expression${matches<"">(unscanned) ? '' : ` before '${unscanned}'`}`
}
/* compiles to:
 * export type writeExpressionExpectedMessage<unscanned extends string> = `Expected an expression${unscanned extends '' ? '' : ` before '${unscanned}'`}`
 */
