/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/List/HasPath.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Key: any
declare const List: any
declare const Match: any
declare const OHasPath: any
declare const ObjectOf: any
type Key<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type List<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Match<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type OHasPath<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type ObjectOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ HasPath: verified type-identical to the original
/* @scripttype preserveParamNames */
export function HasPath(L: List, Path: List<Key>, M: any = any, match: Match = 'default') {
  return OHasPath(ObjectOf(L), Path, M, match)
}
/* compiles to:
 * export type HasPath<L extends List, Path extends List<Key>, M extends any = any, match extends Match = 'default'> = OHasPath<ObjectOf<L>, Path, M, match>
 */
