/**
 * ScriptType for 01-type-level-programming/ts-toolbelt/sources/List/UndefinableKeys.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const List: any
declare const OUndefinableKeys: any
declare const ObjectOf: any
type List<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type OUndefinableKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type ObjectOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ UndefinableKeys: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UndefinableKeys(L: List) {
  return OUndefinableKeys(ObjectOf(L))
}
/* compiles to:
 * export type UndefinableKeys<L extends List> = OUndefinableKeys<ObjectOf<L>>
 */
