/**
 * ScriptType for 04-query-builders-orm/drizzle-orm/drizzle-orm/src/singlestore-core/columns/enum.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const SingleStoreEnumColumnBuilder: any
type SingleStoreEnumColumnBuilder<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ SingleStoreEnumColumnBuilderInitial: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SingleStoreEnumColumnBuilderInitial(TName: string, TEnum: [ string, ...string[] ]) {
  return SingleStoreEnumColumnBuilder({ name: TName, dataType: 'string', columnType: 'SingleStoreEnumColumn', data: TEnum[number], driverParam: string, enumValues: TEnum, generated: Undefined })
}
/* compiles to:
 * export type SingleStoreEnumColumnBuilderInitial<TName extends string, TEnum extends [string, ...string[]]> = SingleStoreEnumColumnBuilder<{ name: TName; dataType: 'string'; columnType: 'SingleStoreEnumColumn'; data: TEnum[number]; driverParam: string; enumValues: TEnum; generated: undefined }>
 */
