/**
 * ScriptType for 02-inference-at-scale/tanstack-query/packages/query-core/src/retryer.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 4 type-level aliases: 4 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const DefaultError: any
type DefaultError<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ RetryValue: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RetryValue(TError) {
  return boolean | number | ShouldRetryFunction(TError)
}
/* compiles to:
 * export type RetryValue<TError> = boolean | number | ShouldRetryFunction<TError>
 */

// ✓ ShouldRetryFunction: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ShouldRetryFunction(TError = DefaultError) {
  return fnType([number, TError], boolean)
}
/* compiles to:
 * export type ShouldRetryFunction<TError = DefaultError> = (a0: number, a1: TError) => boolean
 */

// ✓ RetryDelayValue: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RetryDelayValue(TError) {
  return number | RetryDelayFunction(TError)
}
/* compiles to:
 * export type RetryDelayValue<TError> = number | RetryDelayFunction<TError>
 */

// ✓ RetryDelayFunction: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RetryDelayFunction(TError = DefaultError) {
  return fnType([number, TError], number)
}
/* compiles to:
 * export type RetryDelayFunction<TError = DefaultError> = (a0: number, a1: TError) => number
 */
