/**
 * ScriptType for 07-compiler-internals/typescript/src/compiler/emitter.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 3 type-level aliases: 3 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { Node } from '../../../../../07-compiler-internals/typescript/src/compiler/types.js'
declare const EmitFunction: any
declare const Node: any
declare const OrdinalParentheizerRuleSelector: any
type EmitFunction<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type OrdinalParentheizerRuleSelector<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ ParenthesizerRule: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ParenthesizerRule(T: Node): any {
  return fnType([T], T)
}
/* compiles to:
 * export type ParenthesizerRule<T extends Node> = (a0: T) => T
 */

// ✓ ParenthesizerRuleOrSelector: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ParenthesizerRuleOrSelector(T: Node): any {
  return OrdinalParentheizerRuleSelector(T) | ParenthesizerRule(T)
}
/* compiles to:
 * export type ParenthesizerRuleOrSelector<T extends Node> =
 *   OrdinalParentheizerRuleSelector<T> | ParenthesizerRule<T>
 */

// ✓ EmitListItemFunction: verified type-identical to the original
/* @scripttype preserveParamNames */
export function EmitListItemFunction(T: Node): any {
  return fnType([Node, EmitFunction, anyOf(ParenthesizerRuleOrSelector(T), Undefined), number], voidType())
}
/* compiles to:
 * export type EmitListItemFunction<T extends Node> =
 *   (a0: Node, a1: EmitFunction, a2: ParenthesizerRuleOrSelector<T> | undefined, a3: number) => void
 */
