/**
 * ScriptType for 06-state-and-forms/react-hook-form/src/formStateSubscribe.tsx
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const FieldValues: any
declare const ReactNode: any
declare const UseFormStateProps: any
declare const UseFormStateReturn: any
type FieldValues<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ReactNode<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type UseFormStateProps<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type UseFormStateReturn<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ FormStateProps: verified type-identical to the original
/* @scripttype preserveParamNames */
export function FormStateProps(TFieldValues: FieldValues, TTransformedValues = TFieldValues) {
  return merge(UseFormStateProps(TFieldValues, TTransformedValues), { render: fnType([UseFormStateReturn(TFieldValues)], ReactNode) })
}
/* compiles to:
 * export type FormStateProps<
 *   TFieldValues extends FieldValues,
 *   TTransformedValues = TFieldValues
 * > =
 *   & UseFormStateProps<TFieldValues, TTransformedValues>
 *   & { render: (a0: UseFormStateReturn<TFieldValues>) => ReactNode }
 */

// ✓ FormStateSubscribeProps: verified type-identical to the original
/* @scripttype preserveParamNames */
export function FormStateSubscribeProps(TFieldValues: FieldValues, TTransformedValues = TFieldValues) {
  return FormStateProps(TFieldValues, TTransformedValues)
}
/* compiles to:
 * export type FormStateSubscribeProps<
 *   TFieldValues extends FieldValues,
 *   TTransformedValues = TFieldValues
 * > =
 *   FormStateProps<TFieldValues, TTransformedValues>
 */
