/**
 * ScriptType for 02-inference-at-scale/hono/src/adapter/cloudflare-pages/handler.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 3 type-level aliases: 1 covered, 1 raw, 1 typecheck-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Request: any
declare const RequestInit: any
declare const Response: any
type Request<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type RequestInit<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Response<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ Params: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Params(P: string = any) {
  return Record(P, string | arrayOf(string))
}
/* compiles to:
 * export type Params<P extends string = any> = Record<P, string | string[]>
 */

// ✗ EventContext: uses raw() — language gap, does not count as covered
//   gap: type node TypeQuery
/* @scripttype preserveParamNames */
export function EventContext(Env = {}, P: string = any, Data = Record(string, unknown)) {
  return { request: Request, functionPath: string, waitUntil: fnType([Promise(unknown)], voidType()), passThroughOnException: fnType([], voidType()), props: any, next: fnType([Request | string, RequestInit], Promise(Response)), env: merge(Env, { ASSETS: { fetch: raw('typeof fetch') } }), params: Params(P), data: Data }
}

// ✗ PagesFunction: the ScriptType does not itself typecheck as TypeScript
//   PagesFunction.st.ts(3:63) TS2348: Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
/* @scripttype preserveParamNames */
export function PagesFunction(Env = unknown, Params: string = any, Data: Record<string, unknown> = Record(string, unknown)) {
  return fnType([EventContext(Env, Params, Data)], Response | Promise(Response))
}
/* compiles to:
 * export type PagesFunction<Env = unknown, Params extends string = any, Data extends Record<string, unknown> = Record<string, unknown>> = (a0: EventContext<Env, Params, Data>) => Response | Promise<Response>
 */
