/**
 * ScriptType for 05-functional-effects-hkt/effect/packages/effect/src/unstable/cluster/Envelope.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 typecheck-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const AckChunk: any
declare const Any: any
declare const Interrupt: any
declare const Request: any
declare const Rpc: any
type AckChunk<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Any<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Interrupt<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Request<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Rpc<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ Envelope: the ScriptType does not itself typecheck as TypeScript
//   Envelope.st.ts(2:29) TS2702: 'Rpc' only refers to a type, but is being used as a namespace here.
/* @scripttype preserveParamNames */
export function Envelope(R: Rpc.Any) {
  return Request(R) | AckChunk | Interrupt
}
/* compiles to:
 * export type Envelope<R extends Rpc.Any> = Request<R> | AckChunk | Interrupt
 */
