/**
 * ScriptType for 04-query-builders-orm/drizzle-orm/drizzle-orm/src/pg-core/view.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const ColumnsSelection: any
declare const PgMaterializedView: any
declare const PgView: any
type ColumnsSelection<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type PgMaterializedView<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type PgView<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ PgViewWithSelection: verified type-identical to the original
/* @scripttype preserveParamNames */
export function PgViewWithSelection(TName: string = string, TExisting: boolean = boolean, TSelectedFields: ColumnsSelection = ColumnsSelection) {
  return merge(PgView(TName, TExisting, TSelectedFields), TSelectedFields)
}
/* compiles to:
 * export type PgViewWithSelection<
 *   TName extends string = string,
 *   TExisting extends boolean = boolean,
 *   TSelectedFields extends ColumnsSelection = ColumnsSelection
 * > =
 *   PgView<TName, TExisting, TSelectedFields> & TSelectedFields
 */

// ✓ PgMaterializedViewWithSelection: verified type-identical to the original
/* @scripttype preserveParamNames */
export function PgMaterializedViewWithSelection(TName: string = string, TExisting: boolean = boolean, TSelectedFields: ColumnsSelection = ColumnsSelection) {
  return merge(PgMaterializedView(TName, TExisting, TSelectedFields), TSelectedFields)
}
/* compiles to:
 * export type PgMaterializedViewWithSelection<
 *   TName extends string = string,
 *   TExisting extends boolean = boolean,
 *   TSelectedFields extends ColumnsSelection = ColumnsSelection
 * > =
 *   PgMaterializedView<TName, TExisting, TSelectedFields> & TSelectedFields
 */
