/**
 * ScriptType for 05-functional-effects-hkt/effect/packages/effect/src/Optic.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const IsUnion: any
type IsUnion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ ForbidUnion: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ForbidUnion(A, Message: string) {
  if (matches<true>(IsUnion(A))) {
    return [Message]
  }
  return []
}
/* compiles to:
 * export type ForbidUnion<A, Message extends string> = IsUnion<A> extends true ? [Message] : []
 */
