/**
 * ScriptType for 01-type-level-programming/type-challenges/questions/00529-medium-absolute/template.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ Absolute: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Absolute(T: number | string | bigint): any {
  return any
}
/* compiles to:
 * export type Absolute<T extends number | string | bigint> = any
 */
