/**
 * ScriptType for 02-inference-at-scale/tanstack-router/packages/router-core/src/redirect.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 4 type-level aliases: 4 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { ParsedLocation } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/location.js'
import type { AnyRouter, RegisteredRouter } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/router.js'
declare const AnyRouter: any
declare const HeadersInit: any
declare const NavigateOptions: any
declare const ParsedLocation: any
declare const RegisteredRouter: any
declare const Response: any
type HeadersInit<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type NavigateOptions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Response<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ Redirect: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Redirect(TRouter: AnyRouter = RegisteredRouter, TFrom: string = string, TTo: string | undefined = Undefined, TMaskFrom: string = TFrom, TMaskTo: string = '.'): any {
  return merge(Response, { options: merge(NavigateOptions(TRouter, TFrom, TTo, TMaskFrom, TMaskTo), { _builtLocation: optional(ParsedLocation) }), redirectHandled: optional(boolean) })
}
/* compiles to:
 * export type Redirect<
 *   TRouter extends AnyRouter = RegisteredRouter,
 *   TFrom extends string = string,
 *   TTo extends string | undefined = undefined,
 *   TMaskFrom extends string = TFrom,
 *   TMaskTo extends string = '.'
 * > =
 *   & Response
 *   & {
 *       options: & NavigateOptions<TRouter, TFrom, TTo, TMaskFrom, TMaskTo>
 *       & { _builtLocation?: ParsedLocation }
 *       redirectHandled?: boolean
 *     }
 */

// ✓ RedirectOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RedirectOptions(TRouter: AnyRouter = RegisteredRouter, TFrom: string = string, TTo: string | undefined = Undefined, TMaskFrom: string = TFrom, TMaskTo: string = '.'): any {
  return merge({ href: optional(string), code: optional(number), statusCode: optional(number), throw: optional(any), headers: optional(HeadersInit), _builtLocation: optional(ParsedLocation) }, NavigateOptions(TRouter, TFrom, TTo, TMaskFrom, TMaskTo))
}
/* compiles to:
 * export type RedirectOptions<
 *   TRouter extends AnyRouter = RegisteredRouter,
 *   TFrom extends string = string,
 *   TTo extends string | undefined = undefined,
 *   TMaskFrom extends string = TFrom,
 *   TMaskTo extends string = '.'
 * > =
 *   & {
 *       href?: string
 *       code?: number
 *       statusCode?: number
 *       throw?: any
 *       headers?: HeadersInit
 *       _builtLocation?: ParsedLocation
 *     }
 *   & NavigateOptions<TRouter, TFrom, TTo, TMaskFrom, TMaskTo>
 */

// ✓ ResolvedRedirect: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ResolvedRedirect(TRouter: AnyRouter = RegisteredRouter, TFrom: string = string, TTo: string = '', TMaskFrom: string = TFrom, TMaskTo: string = ''): any {
  return Redirect(TRouter, TFrom, TTo, TMaskFrom, TMaskTo)
}
/* compiles to:
 * export type ResolvedRedirect<
 *   TRouter extends AnyRouter = RegisteredRouter,
 *   TFrom extends string = string,
 *   TTo extends string = '',
 *   TMaskFrom extends string = TFrom,
 *   TMaskTo extends string = ''
 * > =
 *   Redirect<TRouter, TFrom, TTo, TMaskFrom, TMaskTo>
 */

// ✓ RedirectOptionsRoute: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RedirectOptionsRoute(TDefaultFrom: string = string, TRouter: AnyRouter = RegisteredRouter, TTo: string | undefined = Undefined, TMaskTo: string = ''): any {
  return Omit(RedirectOptions(TRouter, TDefaultFrom, TTo, TDefaultFrom, TMaskTo), 'from')
}
/* compiles to:
 * export type RedirectOptionsRoute<
 *   TDefaultFrom extends string = string,
 *   TRouter extends AnyRouter = RegisteredRouter,
 *   TTo extends string | undefined = undefined,
 *   TMaskTo extends string = ''
 * > =
 *   Omit<RedirectOptions<TRouter, TDefaultFrom, TTo, TDefaultFrom, TMaskTo>, 'from'>
 */
