/**
 * ScriptType for 02-inference-at-scale/tanstack-router/packages/router-core/src/router.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 17 type-level aliases: 17 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { HistoryLocation, RouterHistory } from '../../../../../../02-inference-at-scale/tanstack-router/packages/history/src/index.js'
import type { AnyRouteMatch, MakeRouteMatchUnion, MatchRouteOptions } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/Matches.js'
import type { ToOptions } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/link.js'
import type { ParsedLocation } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/location.js'
import type { AnyContext, AnyRoute, AnyRouteWithContext, MakeRemountDepsOptionsUnion } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/route.js'
import type { FullSearchSchema, RouteById } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/routeInfo.js'
import type { AnyRouter, Register, RouterEvent, RouterOptions, TrailingSlashOption } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/router.js'
declare namespace m1 {
  export type TConfig<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type TRouter<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type TSSR<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m2 {
  export type TTypes<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const AnyContext: any
declare const AnyRoute: any
declare const AnyRouteMatch: any
declare const AnyRouteWithContext: any
declare const AnyRouter: any
declare const FullSearchSchema: any
declare const HistoryLocation: any
declare const MakeRemountDepsOptionsUnion: any
declare const MakeRouteMatchUnion: any
declare const MatchRouteOptions: any
declare const NavigateOptions: any
declare const ParsedLocation: any
declare const Register: any
declare const RouteById: any
declare const RouterCore: any
declare const RouterEvent: any
declare const RouterHistory: any
declare const RouterOptions: any
declare const TFrom: any
declare const TMaskFrom: any
declare const TMaskTo: any
declare const TResolved: any
declare const TTo: any
declare const ToOptions: any
declare const TrailingSlashOption: any
type InferRouterContext<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type NavigateOptions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type RouterCore<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TFrom<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TMaskFrom<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TMaskTo<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TResolved<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TTo<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ ControllablePromise: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ControllablePromise(T = any): any {
  return merge(t<Promise<typeof T>>(), { resolve: fnType([T], voidType()), reject: fnType([optElem(any)], voidType()) })
}
/* compiles to:
 * export type ControllablePromise<T = any> =
 *   Promise<T> & { resolve: (a0: T) => void; reject: (a0?: any) => void }
 */

// ✓ RegisteredSsr: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RegisteredSsr(TRegister = Register): any {
  const m1 = matches<{ ssr: Hole<"TSSR">; }>(TRegister)
  if (m1) {
    return m1.TSSR
  }
  return false
}
/* compiles to:
 * export type RegisteredSsr<TRegister = Register> =
 *   TRegister extends { ssr: infer TSSR; } ? TSSR : false
 */

// ✓ RegisteredRouter: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RegisteredRouter(TRegister = Register): any {
  const m1 = matches<{ router: Hole<"TRouter">; }>(TRegister)
  if (m1) {
    return m1.TRouter
  }
  return AnyRouter
}
/* compiles to:
 * export type RegisteredRouter<TRegister = Register> =
 *   TRegister extends { router: infer TRouter; } ? TRouter : AnyRouter
 */

// ✓ RegisteredConfigType: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RegisteredConfigType(TRegister, TKey): any {
  const m1 = matches<{ config: Hole<"TConfig">; }>(TRegister)
  if (m1) {
    const m2 = matches<{ '~types': Hole<"TTypes">; }>(m1.TConfig)
    if (m2) {
      if (TKey in m2.TTypes) {
        return m2.TTypes[TKey]
      }
      return unknown
    }
    return unknown
  }
  return unknown
}
/* compiles to:
 * export type RegisteredConfigType<TRegister, TKey> =
 *   TRegister extends { config: infer TConfig; }
 *     ? TConfig extends { '~types': infer TTypes; }
 *       ? TKey extends keyof TTypes ? TTypes[TKey] : unknown
 *       : unknown
 *     : unknown
 */

// ✓ DefaultRemountDepsFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function DefaultRemountDepsFn(TRouteTree: AnyRoute): any {
  return fnType([MakeRemountDepsOptionsUnion(TRouteTree)], any)
}
/* compiles to:
 * export type DefaultRemountDepsFn<TRouteTree extends AnyRoute> =
 *   (a0: MakeRemountDepsOptionsUnion<TRouteTree>) => any
 */

// ✓ ListenerFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ListenerFn(TEvent: RouterEvent): any {
  return fnType([TEvent], voidType())
}
/* compiles to:
 * export type ListenerFn<TEvent extends RouterEvent> = (a0: TEvent) => void
 */

// ✓ RouterListener: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RouterListener(TRouterEvent: RouterEvent): any {
  return { eventType: TRouterEvent['type'], fn: ListenerFn(TRouterEvent) }
}
/* compiles to:
 * export type RouterListener<TRouterEvent extends RouterEvent> = {
 *   eventType: TRouterEvent['type']
 *   fn: ListenerFn<TRouterEvent>
 * }
 */

// ✓ InferRouterContext: verified type-identical to the original
/* @scripttype preserveParamNames */
export function InferRouterContext(TRouteTree: AnyRoute): any {
  return TRouteTree['types']['routerContext']
}
/* compiles to:
 * export type InferRouterContext<TRouteTree extends AnyRoute> = TRouteTree['types']['routerContext']
 */

// ✓ RouterContextOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RouterContextOptions(TRouteTree: AnyRoute): any {
  if (matches<InferRouterContext<typeof TRouteTree>>(AnyContext)) {
    return { context: optional(InferRouterContext(TRouteTree)) }
  }
  return { context: InferRouterContext(TRouteTree) }
}
/* compiles to:
 * export type RouterContextOptions<TRouteTree extends AnyRoute> =
 *   AnyContext extends InferRouterContext<TRouteTree>
 *     ? { context?: InferRouterContext<TRouteTree> }
 *     : { context: InferRouterContext<TRouteTree> }
 */

// ✓ RouterConstructorOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function RouterConstructorOptions(TRouteTree: AnyRoute, TTrailingSlashOption: TrailingSlashOption, TDefaultStructuralSharingOption: boolean, TRouterHistory: RouterHistory, TDehydrated: Record<string, any>): any {
  return Omit(RouterOptions(TRouteTree, TTrailingSlashOption, TDefaultStructuralSharingOption, TRouterHistory, TDehydrated), anyOf('context', 'serializationAdapters', 'defaultSsr')) & RouterContextOptions(TRouteTree)
}
/* compiles to:
 * export type RouterConstructorOptions<
 *   TRouteTree extends AnyRoute,
 *   TTrailingSlashOption extends TrailingSlashOption,
 *   TDefaultStructuralSharingOption extends boolean,
 *   TRouterHistory extends RouterHistory,
 *   TDehydrated extends Record<string, any>
 * > =
 *   & Omit<
 *       RouterOptions<
 *         TRouteTree,
 *         TTrailingSlashOption,
 *         TDefaultStructuralSharingOption,
 *         TRouterHistory,
 *         TDehydrated
 *       >,
 *       'context' | 'serializationAdapters' | 'defaultSsr'
 *     >
 *   & RouterContextOptions<TRouteTree>
 */

// ✓ PreloadRouteFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function PreloadRouteFn(TRouteTree: AnyRoute, TTrailingSlashOption: TrailingSlashOption, TDefaultStructuralSharingOption: boolean, TRouterHistory: RouterHistory): any {
  return genericFnType(['TFrom extends RoutePaths<TRouteTree> | string = string', 'TTo extends string | undefined = undefined', 'TMaskFrom extends RoutePaths<TRouteTree> | string = TFrom', 'TMaskTo extends string = \'\''], [merge(NavigateOptions(RouterCore(TRouteTree, TTrailingSlashOption, TDefaultStructuralSharingOption, TRouterHistory), TFrom, TTo, TMaskFrom, TMaskTo), { _builtLocation: optional(ParsedLocation) })], t<Promise<Array<AnyRouteMatch> | undefined>>())
}
/* compiles to:
 * export type PreloadRouteFn<
 *   TRouteTree extends AnyRoute,
 *   TTrailingSlashOption extends TrailingSlashOption,
 *   TDefaultStructuralSharingOption extends boolean,
 *   TRouterHistory extends RouterHistory
 * > =
 *   <TFrom extends RoutePaths<TRouteTree> | string = string, TTo extends string | undefined = undefined, TMaskFrom extends RoutePaths<TRouteTree> | string = TFrom, TMaskTo extends string = ''>(
 *     a0: NavigateOptions<RouterCore<TRouteTree, TTrailingSlashOption, TDefaultStructuralSharingOption, TRouterHistory>, TFrom, TTo, TMaskFrom, TMaskTo> & { _builtLocation?: ParsedLocation }
 *   ) => Promise<Array<AnyRouteMatch> | undefined>
 */

// ✓ MatchRouteFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MatchRouteFn(TRouteTree: AnyRoute, TTrailingSlashOption: TrailingSlashOption, TDefaultStructuralSharingOption: boolean, TRouterHistory: RouterHistory): any {
  return genericFnType(['TFrom extends RoutePaths<TRouteTree> = \'/\'', 'TTo extends string | undefined = undefined', 'TResolved = ResolveRelativePath<TFrom, NoInfer<TTo>>'], [ToOptions(RouterCore(TRouteTree, TTrailingSlashOption, TDefaultStructuralSharingOption, TRouterHistory), TFrom, TTo), optElem(MatchRouteOptions)], anyOf(false, RouteById(TRouteTree, TResolved)['types']['allParams']))
}
/* compiles to:
 * export type MatchRouteFn<
 *   TRouteTree extends AnyRoute,
 *   TTrailingSlashOption extends TrailingSlashOption,
 *   TDefaultStructuralSharingOption extends boolean,
 *   TRouterHistory extends RouterHistory
 * > =
 *   <TFrom extends RoutePaths<TRouteTree> = '/', TTo extends string | undefined = undefined, TResolved = ResolveRelativePath<TFrom, NoInfer<TTo>>>(
 *     a0: ToOptions<RouterCore<TRouteTree, TTrailingSlashOption, TDefaultStructuralSharingOption, TRouterHistory>, TFrom, TTo>,
 *     a1?: MatchRouteOptions
 *   ) => false | RouteById<TRouteTree, TResolved>['types']['allParams']
 */

// ✓ UpdateFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UpdateFn(TRouteTree: AnyRoute, TTrailingSlashOption: TrailingSlashOption, TDefaultStructuralSharingOption: boolean, TRouterHistory: RouterHistory, TDehydrated: Record<string, any>): any {
  return fnType([RouterConstructorOptions(TRouteTree, TTrailingSlashOption, TDefaultStructuralSharingOption, TRouterHistory, TDehydrated)], voidType())
}
/* compiles to:
 * export type UpdateFn<
 *   TRouteTree extends AnyRoute,
 *   TTrailingSlashOption extends TrailingSlashOption,
 *   TDefaultStructuralSharingOption extends boolean,
 *   TRouterHistory extends RouterHistory,
 *   TDehydrated extends Record<string, any>
 * > =
 *   (
 *     a0: RouterConstructorOptions<TRouteTree, TTrailingSlashOption, TDefaultStructuralSharingOption, TRouterHistory, TDehydrated>
 *   ) => void
 */

// ✓ InvalidateFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function InvalidateFn(TRouter: AnyRouter): any {
  return fnType([optElem({ filter: optional(fnType([MakeRouteMatchUnion(TRouter)], boolean)), sync: optional(boolean), forcePending: optional(boolean) })], t<Promise<void>>())
}
/* compiles to:
 * export type InvalidateFn<TRouter extends AnyRouter> =
 *   (
 *     a0?: { filter?: (a0: MakeRouteMatchUnion<TRouter>) => boolean; sync?: boolean; forcePending?: boolean }
 *   ) => Promise<void>
 */

// ✓ ParseLocationFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ParseLocationFn(TRouteTree: AnyRoute): any {
  return fnType([HistoryLocation, optElem(ParsedLocation(FullSearchSchema(TRouteTree)))], ParsedLocation(FullSearchSchema(TRouteTree)))
}
/* compiles to:
 * export type ParseLocationFn<TRouteTree extends AnyRoute> =
 *   (a0: HistoryLocation, a1?: ParsedLocation<FullSearchSchema<TRouteTree>>) => ParsedLocation<
 *     FullSearchSchema<TRouteTree>
 *   >
 */

// ✓ ClearCacheFn: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ClearCacheFn(TRouter: AnyRouter): any {
  return fnType([optElem({ filter: optional(fnType([MakeRouteMatchUnion(TRouter)], boolean)) })], voidType())
}
/* compiles to:
 * export type ClearCacheFn<TRouter extends AnyRouter> =
 *   (a0?: { filter?: (a0: MakeRouteMatchUnion<TRouter>) => boolean }) => void
 */

// ✓ AnyRouterWithContext: verified type-identical to the original
/* @scripttype preserveParamNames */
export function AnyRouterWithContext(TContext): any {
  return RouterCore(AnyRouteWithContext(TContext), any, any, any, any)
}
/* compiles to:
 * export type AnyRouterWithContext<TContext> = RouterCore<
 *   AnyRouteWithContext<TContext>,
 *   any,
 *   any,
 *   any,
 *   any
 * >
 */
