/**
 * ScriptType for 02-inference-at-scale/tanstack-router/packages/router-core/src/useLoaderDeps.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { RouteById } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/routeInfo.js'
import type { AnyRouter } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/router.js'
import type { Expand } from '../../../../../../02-inference-at-scale/tanstack-router/packages/router-core/src/utils.js'
declare const AnyRouter: any
declare const Expand: any
declare const RouteById: any
// ✓ ResolveUseLoaderDeps: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ResolveUseLoaderDeps(TRouter: AnyRouter, TFrom): any {
  return Expand(RouteById(TRouter['routeTree'], TFrom)['types']['loaderDeps'])
}
/* compiles to:
 * export type ResolveUseLoaderDeps<TRouter extends AnyRouter, TFrom> = Expand<
 *   RouteById<TRouter['routeTree'], TFrom>['types']['loaderDeps']
 * >
 */

// ✓ UseLoaderDepsResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseLoaderDepsResult(TRouter: AnyRouter, TFrom, TSelected): any {
  if (matches<typeof TSelected>(unknown)) {
    return ResolveUseLoaderDeps(TRouter, TFrom)
  }
  return TSelected
}
/* compiles to:
 * export type UseLoaderDepsResult<TRouter extends AnyRouter, TFrom, TSelected> =
 *   unknown extends TSelected ? ResolveUseLoaderDeps<TRouter, TFrom> : TSelected
 */
