/**
 * ScriptType for 03-schema-and-type-level-parsers/arktype/ark/type/declare.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 10 type-level aliases: 9 covered, 1 raw
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare namespace distill {
  export type Side<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace type {
  export type infer<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type validate<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const DeclareContext: any
declare const ErrorMessage: any
declare const ErrorType: any
declare const OptionalPropertyDefinition: any
declare const Out: any
declare const Side: any
declare const TerminalObjectDefinition: any
declare const ThunkCast: any
declare const TupleExpression: any
declare const Type: any
declare const anyOrNever: any
declare const array: any
declare const bindThis: any
declare const distill: any
declare const inferDefinition: any
declare const optionalKeyOf: any
declare const requiredKeyOf: any
declare const show: any
declare const type: any
declare const unset: any
declare const validate: any
type DeclareContext<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ErrorMessage<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ErrorType<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type OptionalPropertyDefinition<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Out<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Side<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TerminalObjectDefinition<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type ThunkCast<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TupleExpression<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Type<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type anyOrNever<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type array<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type bindThis<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type distill<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type inferDefinition<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type optionalKeyOf<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type requiredKeyOf<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type show<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type type<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type unset<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type validate<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✗ DeclarationParser: uses raw() — language gap, does not count as covered
//   gap: literal type FirstTemplateToken
/* @scripttype preserveParamNames */
export function DeclarationParser($) {
  return genericFnType(['preinferred = unset', 'ctx extends DeclareContext = {}'], [], { type: genericFnType(['const def'], [matches<[ unset ]>([preinferred]) ? (matches<[ anyOrNever ]>([preinferred]) ? validateDeclared(preinferred, def, $, ctx) : ErrorMessage(raw('`declare<ExternalType>() requires a generic argument`'))) : validateDeclared(preinferred, def, $, ctx)], Type(finalizePreinferred(preinferred, def, $, ctx), $)) })
}

// ✓ finalizePreinferred: verified type-identical to the original
/* @scripttype preserveParamNames */
export function finalizePreinferred(preinferred, def, $, ctx: DeclareContext) {
  if (matches<distill.Side>(ctx['side'])) {
    if (matches<"in">(ctx['side'])) {
      return fnType([preinferred], type.infer.Out(def, $))
    }
    return fnType([type.infer.In(def, $)], Out(preinferred))
  }
  return preinferred
}
/* compiles to:
 * export type finalizePreinferred<preinferred, def, $, ctx extends DeclareContext> =
 *   ctx['side'] extends distill.Side
 *     ? ctx['side'] extends 'in'
 *       ? (a0: preinferred) => type.infer.Out<def, $>
 *       : (a0: type.infer.In<def, $>) => Out<preinferred>
 *     : preinferred
 */

// ✓ validateDeclared: verified type-identical to the original
/* @scripttype preserveParamNames */
export function validateDeclared(declared, def, $, ctx: DeclareContext) {
  if (matches<type.validate<typeof def, typeof $>>(def)) {
    return validateInference(def, declared, $, bindThis(def), ctx)
  }
  return type.validate(def, $)
}
/* compiles to:
 * export type validateDeclared<declared, def, $, ctx extends DeclareContext> =
 *   def extends type.validate<def, $>
 *     ? validateInference<def, declared, $, bindThis<def>, ctx>
 *     : type.validate<def, $>
 */

// ✓ validateInference: verified type-identical to the original
/* @scripttype preserveParamNames */
export function validateInference(def, declared, $, args, ctx: DeclareContext) {
  if (matches<TerminalObjectDefinition | ThunkCast | TupleExpression>(def)) {
    if (matches<never>(keyof(def))) {
      return validateObjectInference(def, declared, $, args, ctx)
    }
    return validateShallowInference(inferDefinition(def, $, args), declared, ctx)
  }
  if (matches<array>(def)) {
    return validateArrayInference(def, declared, $, args, ctx)
  }
  if (matches<object>(def)) {
    return validateObjectInference(def, declared, $, args, ctx)
  }
  return validateShallowInference(inferDefinition(def, $, args), declared, ctx)
}
/* compiles to:
 * export type validateInference<def, declared, $, args, ctx extends DeclareContext> =
 *   def extends TerminalObjectDefinition | ThunkCast | TupleExpression
 *     ? keyof def extends never
 *       ? validateObjectInference<def, declared, $, args, ctx>
 *       : validateShallowInference<inferDefinition<def, $, args>, declared, ctx>
 *   : def extends array ? validateArrayInference<def, declared, $, args, ctx>
 *   : def extends object ? validateObjectInference<def, declared, $, args, ctx>
 *   : validateShallowInference<inferDefinition<def, $, args>, declared, ctx>
 */

// ✓ validateArrayInference: verified type-identical to the original
/* @scripttype preserveParamNames */
export function validateArrayInference(def: array, declared, $, args, ctx: DeclareContext) {
  if (matches<array>(declared)) {
    const out = emptyObject
    for (const i in keyof(declared)) {
      out[i] = i in def ? validateInference(def[i], declared[i], $, args, ctx) : declared[i]
    }
    return out
  }
  return show(declarationMismatch(inferDefinition(def, $, args), declared))
}
/* compiles to:
 * export type validateArrayInference<
 *   def extends array,
 *   declared,
 *   $,
 *   args,
 *   ctx extends DeclareContext
 * > =
 *   declared extends array
 *     ? {
 *       [I in keyof declared]: I extends keyof def
 *         ? validateInference<def[I], declared[I], $, args, ctx>
 *         : declared[I]
 *     }
 *     : show<declarationMismatch<inferDefinition<def, $, args>, declared>>
 */

// ✓ validateObjectInference: verified type-identical to the original
/* @scripttype preserveParamNames */
export function validateObjectInference(def: object, declared, $, args, ctx: DeclareContext) {
  const out = emptyObject
  for (const k in keySet(requiredKeyOf(declared))) {
    out[k] = k in def ? validateInference(def[k], declared[k], $, args, ctx) : declared[k]
  }
  const out2 = emptyObject
  for (const k in keySet(optionalKeyOf(declared) & string)) {
    out2[declaredOptionalKeySuggestion(k, def)] = declaredOptionalValueSuggestion(def, k, declared, $, args, ctx)
  }
  return show(out & out2)
}
/* compiles to:
 * export type validateObjectInference<
 *   def extends object,
 *   declared,
 *   $,
 *   args,
 *   ctx extends DeclareContext
 * > =
 *   show<
 *     & {
 *         [K in requiredKeyOf<declared>]: K extends keyof def
 *           ? validateInference<def[K], declared[K], $, args, ctx>
 *           : declared[K]
 *       }
 *     & {
 *         [K1 in optionalKeyOf<declared> & string as declaredOptionalKeySuggestion<K1, def>]: declaredOptionalValueSuggestion<
 *           def,
 *           K1,
 *           declared,
 *           $,
 *           args,
 *           ctx
 *         >
 *       }
 *   >
 */

// ✓ declaredOptionalKeySuggestion: verified type-identical to the original
/* @scripttype preserveParamNames */
export function declaredOptionalKeySuggestion(k: string, def) {
  if (k in def) {
    if (matches<OptionalPropertyDefinition>(def[k])) {
      return k
    }
    return `${k}?`
  }
  return `${k}?`
}
/* compiles to:
 * export type declaredOptionalKeySuggestion<k extends string, def> =
 *   k extends keyof def ? def[k] extends OptionalPropertyDefinition ? k : `${k}?` : `${k}?`
 */

// ✓ declaredOptionalValueSuggestion: verified type-identical to the original
/* @scripttype preserveParamNames */
export function declaredOptionalValueSuggestion(def, k: keyof typeof declared & string, declared, $, args, ctx: DeclareContext) {
  if (k in def) {
    if (matches<OptionalPropertyDefinition>(def[k])) {
      return validateInference(def[k], Required(declared)[k], $, args, ctx)
    }
    return declared[k]
  }
  if (`${k}?` in def) {
    return validateInference(def[`${k}?`], Required(declared)[k], $, args, ctx)
  }
  return declared[k]
}
/* compiles to:
 * export type declaredOptionalValueSuggestion<
 *   def,
 *   k extends keyof declared & string,
 *   declared,
 *   $,
 *   args,
 *   ctx extends DeclareContext
 * > =
 *   k extends keyof def
 *     ? def[k] extends OptionalPropertyDefinition
 *       ? validateInference<def[k], Required<declared>[k], $, args, ctx>
 *       : declared[k]
 *   : `${k}?` extends keyof def
 *     ? validateInference<def[`${k}?`], Required<declared>[k], $, args, ctx>
 *   : declared[k]
 */

// ✓ validateShallowInference: verified type-identical to the original
/* @scripttype preserveParamNames */
export function validateShallowInference(t, declared, ctx: DeclareContext, inferred = matches<distill.Side>(ctx['side']) ? distill(t, ctx['side']) : t) {
  if (matches<true>(equals(inferred, declared))) {
    return unknown
  }
  return show(declarationMismatch(inferred, declared))
}
/* compiles to:
 * export type validateShallowInference<
 *   t,
 *   declared,
 *   ctx extends DeclareContext,
 *   inferred = ctx['side'] extends distill.Side ? distill<t, ctx['side']> : t
 * > =
 *   Equals<inferred, declared> extends true
 *     ? unknown
 *     : show<declarationMismatch<inferred, declared>>
 */

// ✓ declarationMismatch: verified type-identical to the original
/* @scripttype preserveParamNames */
export function declarationMismatch(inferred, declared) {
  return ErrorType({ declared: declared, inferred: inferred })
}
/* compiles to:
 * export type declarationMismatch<inferred, declared> = ErrorType<
 *   { declared: declared; inferred: inferred }
 * >
 */
