/**
 * ScriptType for 02-inference-at-scale/tanstack-router/packages/react-start-client/src/Hydrate.tsx
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const CoreHydrationStrategy: any
declare const HydrateProps: any
declare const HydrationWhen: any
declare const React: any
type CoreHydrationStrategy<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type HydrateProps<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type HydrationWhen<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type React<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ ReactHydrationStrategy: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ReactHydrationStrategy(TWhen: HydrationWhen = HydrationWhen, TCanPrefetch: boolean = boolean) {
  return merge(CoreHydrationStrategy(TWhen, TCanPrefetch), { _h: fnType([ReactHydrationStrategy, HydrateProps], React.JSX.Element) })
}
/* compiles to:
 * export type ReactHydrationStrategy<TWhen extends HydrationWhen = HydrationWhen, TCanPrefetch extends boolean = boolean> = CoreHydrationStrategy<TWhen, TCanPrefetch> & { _h: (a0: ReactHydrationStrategy, a1: HydrateProps) => React.JSX.Element }
 */

// ✓ HydrationStrategy: verified type-identical to the original
/* @scripttype preserveParamNames */
export function HydrationStrategy(TWhen: HydrationWhen = HydrationWhen, TCanPrefetch: boolean = boolean) {
  return ReactHydrationStrategy(TWhen, TCanPrefetch)
}
/* compiles to:
 * export type HydrationStrategy<TWhen extends HydrationWhen = HydrationWhen, TCanPrefetch extends boolean = boolean> = ReactHydrationStrategy<TWhen, TCanPrefetch>
 */
