/**
 * ScriptType for 01-type-level-programming/type-challenges/questions/34857-medium-defined-partial-record/template.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ DefinedPartial: verified type-identical to the original
/* @scripttype preserveParamNames */
export function DefinedPartial(T) {
  return any
}
/* compiles to:
 * export type DefinedPartial<T> = any
 */
