/**
 * ScriptType for 06-state-and-forms/zustand/src/middleware/immer.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 5 type-level aliases: 4 covered, 1 raw
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ Write: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Write(T, U) {
  return Omit(T, keyof(U)) & U
}
/* compiles to:
 * export type Write<T, U> = Omit<T, keyof U> & U
 */

// ✓ SkipTwo: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SkipTwo(T) {
  if (matches<{ length: 0; }>(T)) {
    return []
  }
  if (matches<{ length: 1; }>(T)) {
    return []
  }
  if (matches<{ length: 0 | 1; }>(T)) {
    return []
  }
  const m1 = matches<[ unknown, unknown, ...Hole<"A"> ]>(T)
  if (m1) {
    return m1.A
  }
  const m2 = matches<[ unknown, unknown?, ...Hole<"A"> ]>(T)
  if (m2) {
    return m2.A
  }
  const m3 = matches<[ unknown?, unknown?, ...Hole<"A"> ]>(T)
  if (m3) {
    return m3.A
  }
  return never
}
/* compiles to:
 * export type SkipTwo<T> = T extends { length: 0; } ? [] : T extends { length: 1; } ? [] : T extends { length: 0 | 1; } ? [] : T extends [unknown, unknown, ...infer A] ? A : T extends [unknown, unknown, ...infer A] ? A : T extends [unknown, unknown, ...infer A] ? A : never
 */

// ✓ SetStateType: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SetStateType(T: unknown[]) {
  return Exclude(T[0], fnType([arrayOf(any)], any))
}
/* compiles to:
 * export type SetStateType<T extends unknown[]> = Exclude<T[0], (a0: any[]) => any>
 */

// ✓ WithImmer: verified type-identical to the original
/* @scripttype preserveParamNames */
export function WithImmer(S) {
  return Write(S, StoreImmer(S))
}
/* compiles to:
 * export type WithImmer<S> = Write<S, StoreImmer<S>>
 */

// ✗ StoreImmer: uses raw() — language gap, does not count as covered
//   gap: object member MethodSignature
/* @scripttype preserveParamNames */
export function StoreImmer(S) {
  const m1 = matches<{ setState: Hole<"SetState">; }>(S)
  if (m1) {
    const m2 = matches<{ (...args: Hole<"A1">): Hole<"Sr1">; (...args: Hole<"A2">): Hole<"Sr2">; }>(m1.SetState)
    if (m2) {
      return raw('{ setState(nextStateOrUpdater: SetStateType<A2> | Partial<SetStateType<A2>> | ((state: Draft<SetStateType<A2>>) => void), shouldReplace?: false, ...args: SkipTwo<A1>): Sr1; setState(nextStateOrUpdater: SetStateType<A2> | ((state: Draft<SetStateType<A2>>) => void), shouldReplace: true, ...args: SkipTwo<A2>): Sr2; }')
    }
    return never
  }
  return never
}
