/**
 * ScriptType for 03-schema-and-type-level-parsers/arktype/ark/util/objectKinds.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 8 type-level aliases: 7 covered, 1 compile-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { DescribeOptions } from '../../../../../03-schema-and-type-level-parsers/arktype/ark/util/describe.js'
import type { Fn } from '../../../../../03-schema-and-type-level-parsers/arktype/ark/util/functions.js'
import type { BuiltinObjectKind, GlobalName } from '../../../../../03-schema-and-type-level-parsers/arktype/ark/util/objectKinds.js'
declare namespace m1 {
  export type instance<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type k<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const BuiltinObjectKind: any
declare const DescribeOptions: any
declare const Fn: any
declare const GlobalName: any
declare const builtinConstructors: any
declare const domainDescriptions: any
declare const domainOf: any
declare const objectKindDescriptions: any
type Constructor<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type builtinConstructors<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type domainDescriptions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type domainOf<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type objectKindDescriptions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✗ instantiateConstructors: does not compile yet
//   Cannot use namespace 'globalThis' as a type.
/* @scripttype preserveParamNames */
export function instantiateConstructors(kind: BuiltinObjectKind): any {
  const out = emptyObject
  for (const k in keySet(kind)) {
    out[k] = matches<GlobalName>(k) ? InstanceType(t<typeof globalThis>()[k]) : (matches<GlobalName>(`${k}Constructor`) ? InstanceType(t<typeof globalThis>()[`${k}Constructor`]) : never)
  }
  return out
}
/* compiles to:
 * export type instantiateConstructors<kind extends BuiltinObjectKind> = {
 *   [K in kind]: K extends GlobalName ? InstanceType<globalThis[K]>
 *   : `${K}Constructor` extends GlobalName ? InstanceType<globalThis[`${K}Constructor`]>
 *   : never
 * }
 */

// ✓ objectKindOf: verified type-identical to the original
/* @scripttype preserveParamNames */
export function objectKindOf(data: object): any {
  if (matches<typeof data>(object)) {
    return anyOf(keyof(builtinConstructors), Undefined)
  }
  if (matches<Fn>(data)) {
    return 'Function'
  }
  if (matches<never>(instantiableObjectKind(data))) {
    return Undefined
  }
  return instantiableObjectKind(data)
}
/* compiles to:
 * export type objectKindOf<data extends object> =
 *   object extends data ? keyof builtinConstructors | undefined
 *   : data extends Fn ? 'Function'
 *   : instantiableObjectKind<data> extends never ? undefined
 *   : instantiableObjectKind<data>
 */

// ✓ describeObject: verified type-identical to the original
/* @scripttype preserveParamNames */
export function describeObject(o: object, opts: DescribeOptions = {}): any {
  if (typeof objectKindOf(o) === 'string') {
    if (matches<[ true ]>([opts['includeArticles']])) {
      return objectKindDescriptions[objectKindOf(o)]
    }
    return objectKindOf(o)
  }
  if (matches<[ true ]>([opts['includeArticles']])) {
    return domainDescriptions['object']
  }
  return 'object'
}
/* compiles to:
 * export type describeObject<o extends object, opts extends DescribeOptions = {}> =
 *   objectKindOf<o> extends string
 *     ? [opts['includeArticles']] extends [true]
 *       ? objectKindDescriptions[objectKindOf<o>]
 *       : objectKindOf<o>
 *   : [opts['includeArticles']] extends [true] ? domainDescriptions['object']
 *   : 'object'
 */

// ✓ instantiableObjectKind: verified type-identical to the original
/* @scripttype preserveParamNames */
export function instantiableObjectKind(data: object): any {
  const out = emptyObject
  for (const kind in keyof(builtinConstructors)) {
    out[kind] = matches<(InstanceType<builtinConstructors[typeof kind]>)>(data) ? kind : never
  }
  return out[keyof(builtinConstructors)]
}
/* compiles to:
 * export type instantiableObjectKind<data extends object> =
 *   {
 *     [Kind in keyof builtinConstructors]: data extends InstanceType<builtinConstructors[Kind]>
 *       ? Kind
 *       : never
 *   }[keyof builtinConstructors]
 */

// ✓ objectKindOrDomainOf: verified type-identical to the original
/* @scripttype preserveParamNames */
export function objectKindOrDomainOf(data): any {
  if (matches<object>(data)) {
    if (typeof objectKindOf(data) === 'undefined') {
      return 'object'
    }
    return objectKindOf(data)
  }
  return domainOf(data)
}
/* compiles to:
 * export type objectKindOrDomainOf<data> =
 *   data extends object
 *     ? objectKindOf<data> extends undefined ? 'object' : objectKindOf<data>
 *     : domainOf<data>
 */

// ✓ Constructor: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Constructor(instance = {}): any {
  return ctorType([...arrayOf(never)], instance)
}
/* compiles to:
 * export type Constructor<instance = {}> = new (...a0: never[]) => instance
 */

// ✓ instanceOf: verified type-identical to the original
/* @scripttype preserveParamNames */
export function instanceOf(constructor): any {
  const m1 = matches<Constructor<Hole<"instance">>>(constructor)
  if (m1) {
    return m1.instance
  }
  return never
}
/* compiles to:
 * export type instanceOf<constructor> =
 *   constructor extends Constructor<infer instance> ? instance : never
 */

// ✓ normalizedKeyOf: verified type-identical to the original
/* @scripttype preserveParamNames */
export function normalizedKeyOf(t): any {
  const m1 = matches<Hole<"k">>(keyof(t))
  if (m1) {
    if (typeof m1.k === 'number') {
      return `${m1.k}`
    }
    return m1.k
  }
  return never
}
/* compiles to:
 * export type normalizedKeyOf<t> = keyof t extends infer k ? k extends number ? `${k}` : k : never
 */
