/**
 * ScriptType for 01-type-level-programming/type-challenges/questions/00059-hard-get-optional/template.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ GetOptional: verified type-identical to the original
/* @scripttype preserveParamNames */
export function GetOptional(T): any {
  return any
}
/* compiles to:
 * export type GetOptional<T> = any
 */
