/**
 * ScriptType for 06-state-and-forms/xstate/packages/core/src/graph/types.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 8 type-level aliases: 8 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { SerializationConfig, StatePath, Step, TraversalConfig } from '../../../../../../../06-state-and-forms/xstate/packages/core/src/graph/types.js'
import type { ActorLogic } from '../../../../../../../06-state-and-forms/xstate/packages/core/src/types.js'
declare const ActorLogic: any
declare const EventObject: any
declare const SerializationConfig: any
declare const Snapshot: any
declare const StatePath: any
declare const Step: any
declare const TraversalConfig: any
type EventObject<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type Snapshot<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ JSONSerializable: verified type-identical to the original
/* @scripttype preserveParamNames */
export function JSONSerializable(T: object, U): any {
  return merge(T, { toJSON: fnType([], U) })
}
/* compiles to:
 * export type JSONSerializable<T extends object, U> = T & { toJSON: () => U }
 */

// ✓ Steps: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Steps(TSnapshot: Snapshot<unknown>, TEvent: EventObject): any {
  return arrayOf(Step(TSnapshot, TEvent))
}
/* compiles to:
 * export type Steps<TSnapshot extends Snapshot<unknown>, TEvent extends EventObject> =
 *   Step<TSnapshot, TEvent>[]
 */

// ✓ ExtractEvent: verified type-identical to the original
/* @scripttype preserveParamNames */
/**
 * @param {EventObject} TEvent
 * @param {(typeof TEvent)['type']} TType
 */
export function ExtractEvent(TEvent, TType): any {
  if (matches<{ type: typeof TType; }>(TEvent)) {
    return TEvent
  }
  return never
}
/* compiles to:
 * export type ExtractEvent<TEvent extends EventObject, TType extends TEvent['type']> =
 *   TEvent extends { type: TType; } ? TEvent : never
 */

// ✓ SerializationOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function SerializationOptions(TSnapshot: Snapshot<unknown>, TEvent: EventObject): any {
  return Partial(Pick(SerializationConfig(TSnapshot, TEvent), anyOf('serializeState', 'serializeEvent')))
}
/* compiles to:
 * export type SerializationOptions<
 *   TSnapshot extends Snapshot<unknown>,
 *   TEvent extends EventObject
 * > =
 *   Partial<Pick<SerializationConfig<TSnapshot, TEvent>, 'serializeState' | 'serializeEvent'>>
 */

// ✓ TraversalOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TraversalOptions(TSnapshot: Snapshot<unknown>, TEvent: EventObject, TInput): any {
  return merge({ input: optional(TInput) }, SerializationOptions(TSnapshot, TEvent), Partial(Pick(TraversalConfig(TSnapshot, TEvent), anyOf('events', 'filterEvents', 'limit', 'fromState', 'stopWhen', 'toState'))))
}
/* compiles to:
 * export type TraversalOptions<
 *   TSnapshot extends Snapshot<unknown>,
 *   TEvent extends EventObject,
 *   TInput
 * > =
 *   & { input?: TInput }
 *   & SerializationOptions<TSnapshot, TEvent>
 *   & Partial<
 *       Pick<
 *         TraversalConfig<TSnapshot, TEvent>,
 *         'events' | 'filterEvents' | 'limit' | 'fromState' | 'stopWhen' | 'toState'
 *       >
 *     >
 */

// ✓ Brand: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Brand(T, Tag: string): any {
  return merge(T, { __tag: Tag })
}
/* compiles to:
 * export type Brand<T, Tag extends string> = T & { __tag: Tag }
 */

// ✓ EventExecutor: verified type-identical to the original
/* @scripttype preserveParamNames */
export function EventExecutor(TSnapshot: Snapshot<unknown>, TEvent: EventObject): any {
  return fnType([Step(TSnapshot, TEvent)], t<Promise<any>>() | voidType())
}
/* compiles to:
 * export type EventExecutor<TSnapshot extends Snapshot<unknown>, TEvent extends EventObject> =
 *   (a0: Step<TSnapshot, TEvent>) => Promise<any> | void
 */

// ✓ PathGenerator: verified type-identical to the original
/* @scripttype preserveParamNames */
export function PathGenerator(TSnapshot: Snapshot<unknown>, TEvent: EventObject, TInput): any {
  return fnType([ActorLogic(TSnapshot, TEvent, TInput), TraversalOptions(TSnapshot, TEvent, TInput)], arrayOf(StatePath(TSnapshot, TEvent)))
}
/* compiles to:
 * export type PathGenerator<
 *   TSnapshot extends Snapshot<unknown>,
 *   TEvent extends EventObject,
 *   TInput
 * > =
 *   (
 *     a0: ActorLogic<TSnapshot, TEvent, TInput>,
 *     a1: TraversalOptions<TSnapshot, TEvent, TInput>
 *   ) => StatePath<TSnapshot, TEvent>[]
 */
