/**
 * ScriptType for 04-query-builders-orm/drizzle-orm/drizzle-orm/src/gel-core/view.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const ColumnsSelection: any
declare const GelMaterializedView: any
declare const GelView: any
type ColumnsSelection<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type GelMaterializedView<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type GelView<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ GelViewWithSelection: verified type-identical to the original
/* @scripttype preserveParamNames */
export function GelViewWithSelection(TName: string = string, TExisting: boolean = boolean, TSelectedFields: ColumnsSelection = ColumnsSelection) {
  return merge(GelView(TName, TExisting, TSelectedFields), TSelectedFields)
}
/* compiles to:
 * export type GelViewWithSelection<TName extends string = string, TExisting extends boolean = boolean, TSelectedFields extends ColumnsSelection = ColumnsSelection> = GelView<TName, TExisting, TSelectedFields> & TSelectedFields
 */

// ✓ GelMaterializedViewWithSelection: verified type-identical to the original
/* @scripttype preserveParamNames */
export function GelMaterializedViewWithSelection(TName: string = string, TExisting: boolean = boolean, TSelectedFields: ColumnsSelection = ColumnsSelection) {
  return merge(GelMaterializedView(TName, TExisting, TSelectedFields), TSelectedFields)
}
/* compiles to:
 * export type GelMaterializedViewWithSelection<TName extends string = string, TExisting extends boolean = boolean, TSelectedFields extends ColumnsSelection = ColumnsSelection> = GelMaterializedView<TName, TExisting, TSelectedFields> & TSelectedFields
 */
