/**
 * ScriptType for 01-type-level-programming/type-challenges/questions/02857-hard-isrequiredkey/template.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ IsRequiredKey: verified type-identical to the original
/* @scripttype preserveParamNames */
/**
 * @param {keyof typeof T} K
 */
export function IsRequiredKey(T, K): any {
  return any
}
/* compiles to:
 * export type IsRequiredKey<T, K extends keyof T> = any
 */
