/**
 * ScriptType for 04-query-builders-orm/drizzle-orm/drizzle-orm/src/mysql-core/indexes.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { AnyMySqlColumn } from '../../../../../../04-query-builders-orm/drizzle-orm/drizzle-orm/src/mysql-core/columns/common.js'
declare namespace m1 {
  export type TTableName<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const AnyMySqlColumn: any
// ✓ GetColumnsTableName: verified type-identical to the original
/* @scripttype preserveParamNames */
export function GetColumnsTableName(TColumns): any {
  const m1 = matches<AnyMySqlColumn<{ tableName: Hole<"TTableName", string>; }> | AnyMySqlColumn<{ tableName: Hole<"TTableName", string>; }>[]>(TColumns)
  if (m1) {
    return m1.TTableName
  }
  return never
}
/* compiles to:
 * export type GetColumnsTableName<TColumns> =
 *   TColumns extends AnyMySqlColumn<{ tableName: infer TTableName extends string; }> | AnyMySqlColumn<{ tableName: infer TTableName extends string; }>[]
 *     ? TTableName
 *     : never
 */
