/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/engine/helpers/keys.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 compile-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const TLiteralValue: any
declare const m1: any
declare const m2: any
declare const m3: any
declare const m4: any
declare const m5: any
type TLiteralValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type m1<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type m2<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type m3<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type m4<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type m5<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ TConvertToIntegerKey: does not compile yet
//   Cannot find name 'm1'.
/* @scripttype preserveParamNames */
export function TConvertToIntegerKey(Value: TLiteralValue, Normal: string = `${Value}`, Result: TLiteralValue = m1 ? Normal : (m2 ? Normal : (m3 ? Normal : (m4 ? Normal : (m5 ? m5.Value : Value))))) {
  return Result
}
/* compiles to:
 * export type TConvertToIntegerKey<Value extends TLiteralValue, Normal extends string = `${Value}`, Result extends TLiteralValue = m1 extends true ? Normal : m2 extends true ? Normal : m3 extends true ? Normal : m4 extends true ? Normal : m5 extends true ? m5.Value : Value> = Result
 */
