/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/extends/tuple.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 10 type-level aliases: 10 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { TInstantiateElements, TState } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/engine/instantiate.js'
import type { TExtendsLeft } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/extends/extends_left.js'
import type { TExtendsRight } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/extends/extends_right.js'
import type { TInferTupleResult, TInferUnionResult, TInferable, TTryInferable, TTryRestInferable } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/extends/inference.js'
import type { TExtendsFalse, TExtendsTrue, TExtendsTrueLike } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/extends/result.js'
import type { TArray } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/types/array.js'
import type { TSchema } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/types/schema.js'
import type { TTuple } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/types/tuple.js'
declare namespace Result {
  export type TExtendsFalse<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type TExtendsTrue<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type TExtendsTrueLike<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type unshift<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m1 {
  export type CheckInferred<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Head<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Left<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Right<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Tail<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Types<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m2 {
  export type Inferred<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Type<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const TArray: any
declare const TExtendsFalse: any
declare const TExtendsLeft: any
declare const TExtendsRight: any
declare const TExtendsTrue: any
declare const TExtendsTrueLike: any
declare const TInferTupleResult: any
declare const TInferUnionResult: any
declare const TInferable: any
declare const TInstantiateElements: any
declare const TProperties: any
declare const TSchema: any
declare const TState: any
declare const TTryInferable: any
declare const TTryRestInferable: any
declare const TTuple: any
type TProperties<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ TReverse: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TReverse(Types: TSchema[]): any {
  let Result: any[] = []
  let types = Types
  while (true) {
    const m1 = matches<[ Hole<"Left", TSchema>, ...Hole<"Right", TSchema[]> ]>(types)
    if (!m1) {
      break
    }
    types = m1.Right
    Result.unshift(m1.Left)
  }
  return Result
}
/* compiles to:
 * export type TReverse<Types extends TSchema[]> = TReverse__loop<Types, []>
 * type TReverse__loop<Types extends TSchema[], Result extends any[]> =
 *   Types extends [infer Left extends TSchema, ...infer Right extends TSchema[]]
 *     ? TReverse__loop<Right, [Left, ...Result]>
 *     : Result
 */

// ✓ TApplyReverse: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TApplyReverse(Types: TSchema[], Reversed: boolean): any {
  if (matches<true>(Reversed)) {
    return TReverse(Types)
  }
  return Types
}
/* compiles to:
 * export type TApplyReverse<Types extends TSchema[], Reversed extends boolean> =
 *   Reversed extends true ? TReverse<Types> : Types
 */

// ✓ TReversed: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TReversed__v1(Types): any {
  const m1 = matches<[ Hole<"Left", TSchema>, ...Hole<"_", TSchema[]> ]>(Types)
  if (m1) {
    return m1.Left
  }
  return Undefined
}
export function TReversed(Types: TSchema[], First: TSchema | undefined = TReversed__v1(Types), Inferable: TSchema | undefined = matches<TSchema>(First) ? TTryRestInferable(First) : Undefined, Result: boolean = matches<TSchema>(Inferable) ? true : false): any {
  return Result
}
/* compiles to:
 * export type TReversed__v1<Types> =
 *   Types extends [infer Left extends TSchema, ...TSchema[][]] ? Left : undefined
 * export type TReversed<
 *   Types extends TSchema[],
 *   First extends TSchema | undefined = TReversed__v1<Types>,
 *   Inferable extends TSchema | undefined = First extends TSchema ? TTryRestInferable<First> : undefined,
 *   Result extends boolean = Inferable extends TSchema ? true : false
 * > =
 *   Result
 */

// ✓ TElementsCompare: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TElementsCompare(Inferred: TProperties, Reversed: boolean, Left: TSchema, LeftRest: TSchema[], Right: TSchema, RightRest: TSchema[]): any {
  const m1 = matches<Result.TExtendsTrueLike<Hole<"CheckInferred", TProperties>>>(TExtendsLeft(Inferred, Left, Right))
  if (m1) {
    return TElements(m1.CheckInferred, Reversed, LeftRest, RightRest)
  }
  return t<Result.TExtendsFalse>()
}
/* compiles to:
 * export type TElementsCompare<
 *   Inferred extends TProperties,
 *   Reversed extends boolean,
 *   Left extends TSchema,
 *   LeftRest extends TSchema[],
 *   Right extends TSchema,
 *   RightRest extends TSchema[]
 * > =
 *   TExtendsLeft<Inferred, Left, Right> extends Result.TExtendsTrueLike<infer CheckInferred extends TProperties>
 *     ? TElements<CheckInferred, Reversed, LeftRest, RightRest>
 *     : Result.TExtendsFalse
 */

// ✓ TElementsLeft: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TElementsLeft(Inferred: TProperties, Reversed: boolean, LeftRest: TSchema[], Right: TSchema, RightRest: TSchema[], Inferable: TInferable | undefined = TTryRestInferable(Right)): any {
  if (matches<TInferable>(Inferable)) {
    return TInferTupleResult(Inferred, Inferable['name'], TApplyReverse(LeftRest, Reversed), Inferable['type'])
  }
  const m1 = matches<[ Hole<"Head", TSchema>, ...Hole<"Tail", TSchema[]> ]>(LeftRest)
  if (m1) {
    return TElementsCompare(Inferred, Reversed, m1.Head, m1.Tail, Right, RightRest)
  }
  return t<Result.TExtendsFalse>()
}
/* compiles to:
 * export type TElementsLeft<
 *   Inferred extends TProperties,
 *   Reversed extends boolean,
 *   LeftRest extends TSchema[],
 *   Right extends TSchema,
 *   RightRest extends TSchema[],
 *   Inferable extends TInferable | undefined = TTryRestInferable<Right>
 * > =
 *   Inferable extends TInferable
 *     ? TInferTupleResult<
 *       Inferred,
 *       Inferable['name'],
 *       TApplyReverse<LeftRest, Reversed>,
 *       Inferable['type']
 *     >
 *   : LeftRest extends [infer Head extends TSchema, ...infer Tail extends TSchema[]]
 *     ? TElementsCompare<Inferred, Reversed, Head, Tail, Right, RightRest>
 *   : Result.TExtendsFalse
 */

// ✓ TElementsRight: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TElementsRight(Inferred: TProperties, Reversed: boolean, LeftRest: TSchema[], RightRest: TSchema[]): any {
  const m1 = matches<[ Hole<"Head", TSchema>, ...Hole<"Tail", TSchema[]> ]>(RightRest)
  if (m1) {
    return TElementsLeft(Inferred, Reversed, LeftRest, m1.Head, m1.Tail)
  }
  if (matches<0>(LeftRest['length'])) {
    return t<Result.TExtendsTrue<typeof Inferred>>()
  }
  return t<Result.TExtendsFalse>()
}
/* compiles to:
 * export type TElementsRight<
 *   Inferred extends TProperties,
 *   Reversed extends boolean,
 *   LeftRest extends TSchema[],
 *   RightRest extends TSchema[]
 * > =
 *   RightRest extends [infer Head extends TSchema, ...infer Tail extends TSchema[]]
 *     ? TElementsLeft<Inferred, Reversed, LeftRest, Head, Tail>
 *   : LeftRest['length'] extends 0 ? Result.TExtendsTrue<Inferred>
 *   : Result.TExtendsFalse
 */

// ✓ TElements: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TElements(Inferred: TProperties, Reversed: boolean, LeftRest: TSchema[], RightRest: TSchema[]): any {
  return TElementsRight(Inferred, Reversed, LeftRest, RightRest)
}
/* compiles to:
 * export type TElements<
 *   Inferred extends TProperties,
 *   Reversed extends boolean,
 *   LeftRest extends TSchema[],
 *   RightRest extends TSchema[]
 * > =
 *   TElementsRight<Inferred, Reversed, LeftRest, RightRest>
 */

// ✓ TExtendsTupleToTuple: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TExtendsTupleToTuple(Inferred: TProperties, Left: TSchema[], Right: TSchema[], InstantiatedRight: TSchema[] = TInstantiateElements(Inferred, TState([], []), Right), Reversed: boolean = TReversed(InstantiatedRight)): any {
  return TElements(Inferred, Reversed, TApplyReverse(Left, Reversed), TApplyReverse(InstantiatedRight, Reversed))
}
/* compiles to:
 * export type TExtendsTupleToTuple<
 *   Inferred extends TProperties,
 *   Left extends TSchema[],
 *   Right extends TSchema[],
 *   InstantiatedRight extends TSchema[] = TInstantiateElements<Inferred, TState<[], []>, Right>,
 *   Reversed extends boolean = TReversed<InstantiatedRight>
 * > =
 *   TElements<
 *     Inferred,
 *     Reversed,
 *     TApplyReverse<Left, Reversed>,
 *     TApplyReverse<InstantiatedRight, Reversed>
 *   >
 */

// ✓ TExtendsTupleToArray: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TExtendsTupleToArray(Inferred: TProperties, Left: TSchema[], Right: TSchema, Inferrable: TInferable | undefined = TTryInferable(Right)): any {
  if (matches<TInferable>(Inferrable)) {
    return TInferUnionResult(Inferred, Inferrable['name'], Left, Inferrable['type'])
  }
  const m1 = matches<[ Hole<"Head", TSchema>, ...Hole<"Tail", TSchema[]> ]>(Left)
  if (m1) {
    const m2 = matches<Result.TExtendsTrueLike<Hole<"Inferred", TProperties>>>(TExtendsLeft(Inferred, m1.Head, Right))
    if (m2) {
      return TExtendsTupleToArray(m2.Inferred, m1.Tail, Right)
    }
    return t<Result.TExtendsFalse>()
  }
  return t<Result.TExtendsTrue<typeof Inferred>>()
}
/* compiles to:
 * export type TExtendsTupleToArray<
 *   Inferred extends TProperties,
 *   Left extends TSchema[],
 *   Right extends TSchema,
 *   Inferrable extends TInferable | undefined = TTryInferable<Right>
 * > =
 *   Inferrable extends TInferable
 *     ? TInferUnionResult<Inferred, Inferrable['name'], Left, Inferrable['type']>
 *   : Left extends [infer Head extends TSchema, ...infer Tail extends TSchema[]]
 *     ? TExtendsLeft<Inferred, Head, Right> extends Result.TExtendsTrueLike<infer Inferred extends TProperties>
 *       ? TExtendsTupleToArray<Inferred, Tail, Right>
 *       : Result.TExtendsFalse
 *   : Result.TExtendsTrue<Inferred>
 */

// ✓ TExtendsTuple: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TExtendsTuple(Inferred: TProperties, Left: TSchema[], Right: TSchema, InstantiatedLeft: TSchema[] = TInstantiateElements(Inferred, TState([], []), Left)): any {
  const m1 = matches<TTuple<Hole<"Types", TSchema[]>>>(Right)
  if (m1) {
    return TExtendsTupleToTuple(Inferred, InstantiatedLeft, m1.Types)
  }
  const m2 = matches<TArray<Hole<"Type", TSchema>>>(Right)
  if (m2) {
    return TExtendsTupleToArray(Inferred, InstantiatedLeft, m2.Type)
  }
  return TExtendsRight(Inferred, TTuple(InstantiatedLeft), Right)
}
/* compiles to:
 * export type TExtendsTuple<
 *   Inferred extends TProperties,
 *   Left extends TSchema[],
 *   Right extends TSchema,
 *   InstantiatedLeft extends TSchema[] = TInstantiateElements<Inferred, TState<[], []>, Left>
 * > =
 *   Right extends TTuple<infer Types extends TSchema[]>
 *     ? TExtendsTupleToTuple<Inferred, InstantiatedLeft, Types>
 *   : Right extends TArray<infer Type extends TSchema>
 *     ? TExtendsTupleToArray<Inferred, InstantiatedLeft, Type>
 *   : TExtendsRight<Inferred, TTuple<InstantiatedLeft>, Right>
 */
