/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/extends/unknown.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const Result: any
declare const TAny: any
declare const TExtendsRight: any
declare const TInfer: any
declare const TProperties: any
declare const TSchema: any
declare const TUnknown: any
type Result<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TAny<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TExtendsRight<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TInfer<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TProperties<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TSchema<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TUnknown<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✓ TExtendsUnknown: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TExtendsUnknown(Inferred: TProperties, Left: TUnknown, Right: TSchema) {
  if (matches<TInfer>(Right)) {
    return TExtendsRight(Inferred, Left, Right)
  }
  if (matches<TAny>(Right)) {
    return Result.TExtendsTrue(Inferred)
  }
  if (matches<TUnknown>(Right)) {
    return Result.TExtendsTrue(Inferred)
  }
  return Result.TExtendsFalse
}
/* compiles to:
 * export type TExtendsUnknown<Inferred extends TProperties, Left extends TUnknown, Right extends TSchema> = Right extends TInfer ? TExtendsRight<Inferred, Left, Right> : Right extends TAny ? Result.TExtendsTrue<Inferred> : Right extends TUnknown ? Result.TExtendsTrue<Inferred> : Result.TExtendsFalse
 */
