/**
 * ScriptType for 06-state-and-forms/redux-toolkit/packages/toolkit/src/query/react/buildHooks.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 65 type-level aliases: 65 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { BaseQueryFn } from '../../../../../../../../06-state-and-forms/redux-toolkit/packages/toolkit/src/query/baseQueryTypes.js'
import type { InfiniteData, InfiniteQueryDirection, InfiniteQuerySubState, QuerySubState, SubscriptionOptions } from '../../../../../../../../06-state-and-forms/redux-toolkit/packages/toolkit/src/query/core/apiState.js'
import type { InfiniteQueryActionCreatorResult, MutationActionCreatorResult, QueryActionCreatorResult } from '../../../../../../../../06-state-and-forms/redux-toolkit/packages/toolkit/src/query/core/buildInitiate.js'
import type { MutationResultSelectorResult, SkipToken } from '../../../../../../../../06-state-and-forms/redux-toolkit/packages/toolkit/src/query/core/buildSelectors.js'
import type { InfiniteQueryArgFrom, InfiniteQueryDefinition, MutationDefinition, PageParamFrom, QueryArgFrom, QueryDefinition, ResultTypeFrom } from '../../../../../../../../06-state-and-forms/redux-toolkit/packages/toolkit/src/query/endpointDefinitions.js'
import type { UseQuerySubscriptionOptions } from '../../../../../../../../06-state-and-forms/redux-toolkit/packages/toolkit/src/query/react/buildHooks.js'
import type { UninitializedValue } from '../../../../../../../../06-state-and-forms/redux-toolkit/packages/toolkit/src/query/react/constants.js'
declare namespace QueryStatus {
  export type uninitialized<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const BaseQueryFn: any
declare const InfiniteData: any
declare const InfiniteQueryActionCreatorResult: any
declare const InfiniteQueryArgFrom: any
declare const InfiniteQueryDefinition: any
declare const InfiniteQueryDirection: any
declare const InfiniteQuerySubState: any
declare const MutationActionCreatorResult: any
declare const MutationDefinition: any
declare const MutationResultSelectorResult: any
declare const PageParamFrom: any
declare const QueryActionCreatorResult: any
declare const QueryArgFrom: any
declare const QueryDefinition: any
declare const QueryStatus: any
declare const QuerySubState: any
declare const ResultTypeFrom: any
declare const SkipToken: any
declare const SubscriptionOptions: any
declare const TSHelpersId: any
declare const TSHelpersOverride: any
declare const UninitializedValue: any
declare const UseQuerySubscriptionOptions: any
declare const uninitialized: any
type QueryStatus<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TSHelpersId<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TSHelpersOverride<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type uninitialized<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ QueryHooks: verified type-identical to the original
/* @scripttype preserveParamNames */
export function QueryHooks(Definition: QueryDefinition<any, any, any, any, any>): any {
  return { useQuery: UseQuery(Definition), useLazyQuery: UseLazyQuery(Definition), useQuerySubscription: UseQuerySubscription(Definition), useLazyQuerySubscription: UseLazyQuerySubscription(Definition), useQueryState: UseQueryState(Definition) }
}
/* compiles to:
 * export type QueryHooks<Definition extends QueryDefinition<any, any, any, any, any>> = {
 *   useQuery: UseQuery<Definition>
 *   useLazyQuery: UseLazyQuery<Definition>
 *   useQuerySubscription: UseQuerySubscription<Definition>
 *   useLazyQuerySubscription: UseLazyQuerySubscription<Definition>
 *   useQueryState: UseQueryState<Definition>
 * }
 */

// ✓ InfiniteQueryHooks: verified type-identical to the original
/* @scripttype preserveParamNames */
export function InfiniteQueryHooks(Definition: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return { useInfiniteQuery: UseInfiniteQuery(Definition), useInfiniteQuerySubscription: UseInfiniteQuerySubscription(Definition), useInfiniteQueryState: UseInfiniteQueryState(Definition) }
}
/* compiles to:
 * export type InfiniteQueryHooks<
 *   Definition extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   {
 *     useInfiniteQuery: UseInfiniteQuery<Definition>
 *     useInfiniteQuerySubscription: UseInfiniteQuerySubscription<Definition>
 *     useInfiniteQueryState: UseInfiniteQueryState<Definition>
 *   }
 */

// ✓ MutationHooks: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MutationHooks(Definition: MutationDefinition<any, any, any, any, any>): any {
  return { useMutation: UseMutation(Definition) }
}
/* compiles to:
 * export type MutationHooks<Definition extends MutationDefinition<any, any, any, any, any>> = {
 *   useMutation: UseMutation<Definition>
 * }
 */

// ✓ UseQuery: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQuery(D: QueryDefinition<any, any, any, any>): any {
  return genericFnType(['R extends Record<string, any> = UseQueryStateDefaultResult<D>'], [QueryArgFrom(D) | SkipToken, optElem(UseQuerySubscriptionOptions & UseQueryStateOptions(D, R))], UseQueryHookResult(D, R))
}
/* compiles to:
 * export type UseQuery<D extends QueryDefinition<any, any, any, any>> =
 *   <R extends Record<string, any> = UseQueryStateDefaultResult<D>>(
 *     a0: QueryArgFrom<D> | SkipToken,
 *     a1?: UseQuerySubscriptionOptions & UseQueryStateOptions<D, R>
 *   ) => UseQueryHookResult<D, R>
 */

// ✓ TypedUseQuery: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseQuery(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return UseQuery(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseQuery<ResultType, QueryArg, BaseQuery extends BaseQueryFn> = UseQuery<
 *   QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>
 * >
 */

// ✓ UseQueryHookResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryHookResult(D: QueryDefinition<any, any, any, any>, R = UseQueryStateDefaultResult(D)): any {
  return UseQueryStateResult(D, R) & UseQuerySubscriptionResult(D)
}
/* compiles to:
 * export type UseQueryHookResult<
 *   D extends QueryDefinition<any, any, any, any>,
 *   R = UseQueryStateDefaultResult<D>
 * > =
 *   UseQueryStateResult<D, R> & UseQuerySubscriptionResult<D>
 */

// ✓ TypedUseQueryHookResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseQueryHookResult(ResultType, QueryArg, BaseQuery: BaseQueryFn, R = UseQueryStateDefaultResult(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))): any {
  return TypedUseQueryStateResult(ResultType, QueryArg, BaseQuery, R) & TypedUseQuerySubscriptionResult(ResultType, QueryArg, BaseQuery)
}
/* compiles to:
 * export type TypedUseQueryHookResult<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn,
 *   R = UseQueryStateDefaultResult<QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 * > =
 *   & TypedUseQueryStateResult<ResultType, QueryArg, BaseQuery, R>
 *   & TypedUseQuerySubscriptionResult<ResultType, QueryArg, BaseQuery>
 */

// ✓ UseQuerySubscription: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQuerySubscription(D: QueryDefinition<any, any, any, any>): any {
  return fnType([QueryArgFrom(D) | SkipToken, optElem(UseQuerySubscriptionOptions)], UseQuerySubscriptionResult(D))
}
/* compiles to:
 * export type UseQuerySubscription<D extends QueryDefinition<any, any, any, any>> =
 *   (a0: QueryArgFrom<D> | SkipToken, a1?: UseQuerySubscriptionOptions) => UseQuerySubscriptionResult<
 *     D
 *   >
 */

// ✓ TypedUseQuerySubscription: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseQuerySubscription(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return UseQuerySubscription(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseQuerySubscription<ResultType, QueryArg, BaseQuery extends BaseQueryFn> = UseQuerySubscription<
 *   QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>
 * >
 */

// ✓ UseQuerySubscriptionResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQuerySubscriptionResult(D: QueryDefinition<any, any, any, any>): any {
  return Pick(QueryActionCreatorResult(D), 'refetch')
}
/* compiles to:
 * export type UseQuerySubscriptionResult<D extends QueryDefinition<any, any, any, any>> = Pick<
 *   QueryActionCreatorResult<D>,
 *   'refetch'
 * >
 */

// ✓ TypedUseQuerySubscriptionResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseQuerySubscriptionResult(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return UseQuerySubscriptionResult(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseQuerySubscriptionResult<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn
 * > =
 *   UseQuerySubscriptionResult<QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 */

// ✓ UseLazyQueryLastPromiseInfo: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseLazyQueryLastPromiseInfo(D: QueryDefinition<any, any, any, any>): any {
  return { lastArg: QueryArgFrom(D) }
}
/* compiles to:
 * export type UseLazyQueryLastPromiseInfo<D extends QueryDefinition<any, any, any, any>> = {
 *   lastArg: QueryArgFrom<D>
 * }
 */

// ✓ UseLazyQuery: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseLazyQuery(D: QueryDefinition<any, any, any, any>): any {
  return genericFnType(['R extends Record<string, any> = UseQueryStateDefaultResult<D>'], [optElem(SubscriptionOptions & Omit(UseQueryStateOptions(D, R), 'skip'))], [LazyQueryTrigger(D), UseLazyQueryStateResult(D, R), UseLazyQueryLastPromiseInfo(D)])
}
/* compiles to:
 * export type UseLazyQuery<D extends QueryDefinition<any, any, any, any>> =
 *   <R extends Record<string, any> = UseQueryStateDefaultResult<D>>(
 *     a0?: SubscriptionOptions & Omit<UseQueryStateOptions<D, R>, 'skip'>
 *   ) => [LazyQueryTrigger<D>, UseLazyQueryStateResult<D, R>, UseLazyQueryLastPromiseInfo<D>]
 */

// ✓ TypedUseLazyQuery: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseLazyQuery(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return UseLazyQuery(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseLazyQuery<ResultType, QueryArg, BaseQuery extends BaseQueryFn> = UseLazyQuery<
 *   QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>
 * >
 */

// ✓ UseLazyQueryStateResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseLazyQueryStateResult(D: QueryDefinition<any, any, any, any>, R = UseQueryStateDefaultResult(D)): any {
  return merge(UseQueryStateResult(D, R), { reset: fnType([], voidType()) })
}
/* compiles to:
 * export type UseLazyQueryStateResult<
 *   D extends QueryDefinition<any, any, any, any>,
 *   R = UseQueryStateDefaultResult<D>
 * > =
 *   UseQueryStateResult<D, R> & { reset: () => void }
 */

// ✓ TypedUseLazyQueryStateResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseLazyQueryStateResult(ResultType, QueryArg, BaseQuery: BaseQueryFn, R = UseQueryStateDefaultResult(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))): any {
  return UseLazyQueryStateResult(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string), R)
}
/* compiles to:
 * export type TypedUseLazyQueryStateResult<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn,
 *   R = UseQueryStateDefaultResult<QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 * > =
 *   UseLazyQueryStateResult<QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>, R>
 */

// ✓ LazyQueryTrigger: verified type-identical to the original
/* @scripttype preserveParamNames */
export function LazyQueryTrigger(D: QueryDefinition<any, any, any, any>): any {
  return { ...callSig([QueryArgFrom(D), optElem(boolean)], QueryActionCreatorResult(D)) }
}
/* compiles to:
 * export type LazyQueryTrigger<D extends QueryDefinition<any, any, any, any>> = {
 *   (a0: QueryArgFrom<D>, a1?: boolean): QueryActionCreatorResult<D>
 * }
 */

// ✓ TypedLazyQueryTrigger: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedLazyQueryTrigger(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return LazyQueryTrigger(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedLazyQueryTrigger<ResultType, QueryArg, BaseQuery extends BaseQueryFn> = LazyQueryTrigger<
 *   QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>
 * >
 */

// ✓ UseLazyQuerySubscription: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseLazyQuerySubscription(D: QueryDefinition<any, any, any, any>): any {
  return fnType([optElem(SubscriptionOptions)], asReadonly([LazyQueryTrigger(D), QueryArgFrom(D) | UninitializedValue, { reset: fnType([], voidType()) }]))
}
/* compiles to:
 * export type UseLazyQuerySubscription<D extends QueryDefinition<any, any, any, any>> =
 *   (a0?: SubscriptionOptions) => readonly [
 *     LazyQueryTrigger<D>,
 *     QueryArgFrom<D> | UninitializedValue,
 *     { reset: () => void }
 *   ]
 */

// ✓ TypedUseLazyQuerySubscription: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseLazyQuerySubscription(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return UseLazyQuerySubscription(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseLazyQuerySubscription<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn
 * > =
 *   UseLazyQuerySubscription<QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 */

// ✓ QueryStateSelector: verified type-identical to the original
/* @scripttype preserveParamNames */
export function QueryStateSelector(R: Record<string, any>, D: QueryDefinition<any, any, any, any>): any {
  return fnType([UseQueryStateDefaultResult(D)], R)
}
/* compiles to:
 * export type QueryStateSelector<
 *   R extends Record<string, any>,
 *   D extends QueryDefinition<any, any, any, any>
 * > =
 *   (a0: UseQueryStateDefaultResult<D>) => R
 */

// ✓ TypedQueryStateSelector: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedQueryStateSelector(ResultType, QueryArgumentType, BaseQueryFunctionType: BaseQueryFn, SelectedResultType: Record<string, any> = UseQueryStateDefaultResult(QueryDefinition(QueryArgumentType, BaseQueryFunctionType, string, ResultType, string))): any {
  return QueryStateSelector(SelectedResultType, QueryDefinition(QueryArgumentType, BaseQueryFunctionType, string, ResultType, string))
}
/* compiles to:
 * export type TypedQueryStateSelector<
 *   ResultType,
 *   QueryArgumentType,
 *   BaseQueryFunctionType extends BaseQueryFn,
 *   SelectedResultType extends Record<string, any> = UseQueryStateDefaultResult<QueryDefinition<QueryArgumentType, BaseQueryFunctionType, string, ResultType, string>>
 * > =
 *   QueryStateSelector<
 *     SelectedResultType,
 *     QueryDefinition<QueryArgumentType, BaseQueryFunctionType, string, ResultType, string>
 *   >
 */

// ✓ UseQueryState: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryState(D: QueryDefinition<any, any, any, any>): any {
  return genericFnType(['R extends Record<string, any> = UseQueryStateDefaultResult<D>'], [QueryArgFrom(D) | SkipToken, optElem(UseQueryStateOptions(D, R))], UseQueryStateResult(D, R))
}
/* compiles to:
 * export type UseQueryState<D extends QueryDefinition<any, any, any, any>> =
 *   <R extends Record<string, any> = UseQueryStateDefaultResult<D>>(
 *     a0: QueryArgFrom<D> | SkipToken,
 *     a1?: UseQueryStateOptions<D, R>
 *   ) => UseQueryStateResult<D, R>
 */

// ✓ TypedUseQueryState: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseQueryState(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return UseQueryState(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseQueryState<ResultType, QueryArg, BaseQuery extends BaseQueryFn> = UseQueryState<
 *   QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>
 * >
 */

// ✓ UseQueryStateOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateOptions(D: QueryDefinition<any, any, any, any>, R: Record<string, any>): any {
  return { skip: optional(boolean), selectFromResult: optional(QueryStateSelector(R, D)) }
}
/* compiles to:
 * export type UseQueryStateOptions<
 *   D extends QueryDefinition<any, any, any, any>,
 *   R extends Record<string, any>
 * > =
 *   { skip?: boolean; selectFromResult?: QueryStateSelector<R, D> }
 */

// ✓ TypedUseQueryStateOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseQueryStateOptions(ResultType, QueryArg, BaseQuery: BaseQueryFn, SelectedResult: Record<string, any> = UseQueryStateDefaultResult(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))): any {
  return UseQueryStateOptions(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string), SelectedResult)
}
/* compiles to:
 * export type TypedUseQueryStateOptions<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn,
 *   SelectedResult extends Record<string, any> = UseQueryStateDefaultResult<QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 * > =
 *   UseQueryStateOptions<
 *     QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>,
 *     SelectedResult
 *   >
 */

// ✓ UseQueryStateResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateResult(_: QueryDefinition<any, any, any, any>, R): any {
  return R
}
/* compiles to:
 * export type UseQueryStateResult<_ extends QueryDefinition<any, any, any, any>, R> = R
 */

// ✓ TypedUseQueryStateResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseQueryStateResult(ResultType, QueryArg, BaseQuery: BaseQueryFn, R = UseQueryStateDefaultResult(QueryDefinition(QueryArg, BaseQuery, string, ResultType, string))): any {
  return R
}
/* compiles to:
 * export type TypedUseQueryStateResult<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn,
 *   R = UseQueryStateDefaultResult<QueryDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 * > =
 *   R
 */

// ✓ UseQueryStateBaseResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateBaseResult(D: QueryDefinition<any, any, any, any>): any {
  return merge(QuerySubState(D), { currentData: optional(ResultTypeFrom(D)), isUninitialized: false, isLoading: false, isFetching: false, isSuccess: false, isError: false })
}
/* compiles to:
 * export type UseQueryStateBaseResult<D extends QueryDefinition<any, any, any, any>> =
 *   & QuerySubState<D>
 *   & {
 *       currentData?: ResultTypeFrom<D>
 *       isUninitialized: false
 *       isLoading: false
 *       isFetching: false
 *       isSuccess: false
 *       isError: false
 *     }
 */

// ✓ UseQueryStateUninitialized: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateUninitialized(D: QueryDefinition<any, any, any, any>): any {
  return TSHelpersOverride(Extract(UseQueryStateBaseResult(D), { status: t<QueryStatus.uninitialized>() }), { isUninitialized: true })
}
/* compiles to:
 * export type UseQueryStateUninitialized<D extends QueryDefinition<any, any, any, any>> = TSHelpersOverride<
 *   Extract<UseQueryStateBaseResult<D>, { status: QueryStatus.uninitialized }>,
 *   { isUninitialized: true }
 * >
 */

// ✓ UseQueryStateLoading: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateLoading(D: QueryDefinition<any, any, any, any>): any {
  return TSHelpersOverride(UseQueryStateBaseResult(D), { isLoading: true, isFetching: boolean, data: Undefined })
}
/* compiles to:
 * export type UseQueryStateLoading<D extends QueryDefinition<any, any, any, any>> = TSHelpersOverride<
 *   UseQueryStateBaseResult<D>,
 *   { isLoading: true; isFetching: boolean; data: undefined }
 * >
 */

// ✓ UseQueryStateSuccessFetching: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateSuccessFetching(D: QueryDefinition<any, any, any, any>): any {
  return TSHelpersOverride(UseQueryStateBaseResult(D), merge({ isSuccess: true, isFetching: true, error: Undefined }, { data: ResultTypeFrom(D) }, Required(Pick(UseQueryStateBaseResult(D), 'fulfilledTimeStamp'))))
}
/* compiles to:
 * export type UseQueryStateSuccessFetching<D extends QueryDefinition<any, any, any, any>> = TSHelpersOverride<
 *   UseQueryStateBaseResult<D>,
 *   & { isSuccess: true; isFetching: true; error: undefined }
 *   & { data: ResultTypeFrom<D> }
 *   & Required<Pick<UseQueryStateBaseResult<D>, 'fulfilledTimeStamp'>>
 * >
 */

// ✓ UseQueryStateSuccessNotFetching: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateSuccessNotFetching(D: QueryDefinition<any, any, any, any>): any {
  return TSHelpersOverride(UseQueryStateBaseResult(D), merge({ isSuccess: true, isFetching: false, error: Undefined }, { data: ResultTypeFrom(D), currentData: ResultTypeFrom(D) }, Required(Pick(UseQueryStateBaseResult(D), 'fulfilledTimeStamp'))))
}
/* compiles to:
 * export type UseQueryStateSuccessNotFetching<D extends QueryDefinition<any, any, any, any>> = TSHelpersOverride<
 *   UseQueryStateBaseResult<D>,
 *   & { isSuccess: true; isFetching: false; error: undefined }
 *   & { data: ResultTypeFrom<D>; currentData: ResultTypeFrom<D> }
 *   & Required<Pick<UseQueryStateBaseResult<D>, 'fulfilledTimeStamp'>>
 * >
 */

// ✓ UseQueryStateError: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateError(D: QueryDefinition<any, any, any, any>): any {
  return TSHelpersOverride(UseQueryStateBaseResult(D), merge({ isError: true }, Required(Pick(UseQueryStateBaseResult(D), 'error'))))
}
/* compiles to:
 * export type UseQueryStateError<D extends QueryDefinition<any, any, any, any>> = TSHelpersOverride<
 *   UseQueryStateBaseResult<D>,
 *   { isError: true } & Required<Pick<UseQueryStateBaseResult<D>, 'error'>>
 * >
 */

// ✓ UseQueryStateDefaultResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseQueryStateDefaultResult(D: QueryDefinition<any, any, any, any>): any {
  return merge(TSHelpersId(anyOf(UseQueryStateUninitialized(D), UseQueryStateLoading(D), UseQueryStateSuccessFetching(D), UseQueryStateSuccessNotFetching(D), UseQueryStateError(D))), { status: QueryStatus })
}
/* compiles to:
 * export type UseQueryStateDefaultResult<D extends QueryDefinition<any, any, any, any>> =
 *   & TSHelpersId<
 *       | UseQueryStateUninitialized<D>
 *       | UseQueryStateLoading<D>
 *       | UseQueryStateSuccessFetching<D>
 *       | UseQueryStateSuccessNotFetching<D>
 *       | UseQueryStateError<D>
 *     >
 *   & { status: QueryStatus }
 */

// ✓ LazyInfiniteQueryTrigger: verified type-identical to the original
/* @scripttype preserveParamNames */
export function LazyInfiniteQueryTrigger(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return { ...callSig([QueryArgFrom(D), InfiniteQueryDirection], InfiniteQueryActionCreatorResult(D)) }
}
/* compiles to:
 * export type LazyInfiniteQueryTrigger<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   { (a0: QueryArgFrom<D>, a1: InfiniteQueryDirection): InfiniteQueryActionCreatorResult<D> }
 */

// ✓ TypedLazyInfiniteQueryTrigger: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedLazyInfiniteQueryTrigger(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn): any {
  return LazyInfiniteQueryTrigger(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedLazyInfiniteQueryTrigger<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn
 * > =
 *   LazyInfiniteQueryTrigger<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>
 *   >
 */

// ✓ UseInfiniteQuerySubscriptionOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQuerySubscriptionOptions(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return merge(SubscriptionOptions, { skip: optional(boolean), refetchOnMountOrArgChange: optional(boolean | number), initialPageParam: optional(PageParamFrom(D)), refetchCachedPages: optional(boolean) })
}
/* compiles to:
 * export type UseInfiniteQuerySubscriptionOptions<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   & SubscriptionOptions
 *   & {
 *       skip?: boolean
 *       refetchOnMountOrArgChange?: boolean | number
 *       initialPageParam?: PageParamFrom<D>
 *       refetchCachedPages?: boolean
 *     }
 */

// ✓ TypedUseInfiniteQuerySubscription: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseInfiniteQuerySubscription(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn): any {
  return UseInfiniteQuerySubscription(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseInfiniteQuerySubscription<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn
 * > =
 *   UseInfiniteQuerySubscription<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>
 *   >
 */

// ✓ UseInfiniteQuerySubscriptionResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQuerySubscriptionResult(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return { refetch: fnType([optElem(Pick(UseInfiniteQuerySubscriptionOptions(D), 'refetchCachedPages'))], InfiniteQueryActionCreatorResult(D)), trigger: LazyInfiniteQueryTrigger(D), fetchNextPage: fnType([], InfiniteQueryActionCreatorResult(D)), fetchPreviousPage: fnType([], InfiniteQueryActionCreatorResult(D)) }
}
/* compiles to:
 * export type UseInfiniteQuerySubscriptionResult<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   {
 *     refetch: (a0?: Pick<UseInfiniteQuerySubscriptionOptions<D>, 'refetchCachedPages'>) => InfiniteQueryActionCreatorResult<
 *       D
 *     >
 *     trigger: LazyInfiniteQueryTrigger<D>
 *     fetchNextPage: () => InfiniteQueryActionCreatorResult<D>
 *     fetchPreviousPage: () => InfiniteQueryActionCreatorResult<D>
 *   }
 */

// ✓ TypedUseInfiniteQuerySubscriptionResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseInfiniteQuerySubscriptionResult(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn): any {
  return UseInfiniteQuerySubscriptionResult(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseInfiniteQuerySubscriptionResult<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn
 * > =
 *   UseInfiniteQuerySubscriptionResult<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>
 *   >
 */

// ✓ InfiniteQueryStateSelector: verified type-identical to the original
/* @scripttype preserveParamNames */
export function InfiniteQueryStateSelector(R: Record<string, any>, D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return fnType([UseInfiniteQueryStateDefaultResult(D)], R)
}
/* compiles to:
 * export type InfiniteQueryStateSelector<
 *   R extends Record<string, any>,
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   (a0: UseInfiniteQueryStateDefaultResult<D>) => R
 */

// ✓ TypedInfiniteQueryStateSelector: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedInfiniteQueryStateSelector(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn, SelectedResult: Record<string, any> = UseInfiniteQueryStateDefaultResult(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))): any {
  return InfiniteQueryStateSelector(SelectedResult, InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedInfiniteQueryStateSelector<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn,
 *   SelectedResult extends Record<string, any> = UseInfiniteQueryStateDefaultResult<InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>>
 * > =
 *   InfiniteQueryStateSelector<
 *     SelectedResult,
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>
 *   >
 */

// ✓ UseInfiniteQuery: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQuery(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return genericFnType(['R extends Record<string, any> = UseInfiniteQueryStateDefaultResult<D>'], [InfiniteQueryArgFrom(D) | SkipToken, optElem(UseInfiniteQuerySubscriptionOptions(D) & UseInfiniteQueryStateOptions(D, R))], UseInfiniteQueryHookResult(D, R) & Pick(UseInfiniteQuerySubscriptionResult(D), anyOf('fetchNextPage', 'fetchPreviousPage')))
}
/* compiles to:
 * export type UseInfiniteQuery<D extends InfiniteQueryDefinition<any, any, any, any, any>> =
 *   <R extends Record<string, any> = UseInfiniteQueryStateDefaultResult<D>>(
 *     a0: InfiniteQueryArgFrom<D> | SkipToken,
 *     a1?: UseInfiniteQuerySubscriptionOptions<D> & UseInfiniteQueryStateOptions<D, R>
 *   ) => & UseInfiniteQueryHookResult<D, R>
 *   & Pick<UseInfiniteQuerySubscriptionResult<D>, 'fetchNextPage' | 'fetchPreviousPage'>
 */

// ✓ TypedUseInfiniteQuery: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseInfiniteQuery(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn): any {
  return UseInfiniteQuery(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseInfiniteQuery<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn
 * > =
 *   UseInfiniteQuery<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>
 *   >
 */

// ✓ UseInfiniteQueryState: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryState(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return genericFnType(['R extends Record<string, any> = UseInfiniteQueryStateDefaultResult<D>'], [InfiniteQueryArgFrom(D) | SkipToken, optElem(UseInfiniteQueryStateOptions(D, R))], UseInfiniteQueryStateResult(D, R))
}
/* compiles to:
 * export type UseInfiniteQueryState<D extends InfiniteQueryDefinition<any, any, any, any, any>> =
 *   <R extends Record<string, any> = UseInfiniteQueryStateDefaultResult<D>>(
 *     a0: InfiniteQueryArgFrom<D> | SkipToken,
 *     a1?: UseInfiniteQueryStateOptions<D, R>
 *   ) => UseInfiniteQueryStateResult<D, R>
 */

// ✓ TypedUseInfiniteQueryState: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseInfiniteQueryState(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn): any {
  return UseInfiniteQueryState(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseInfiniteQueryState<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn
 * > =
 *   UseInfiniteQueryState<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>
 *   >
 */

// ✓ UseInfiniteQuerySubscription: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQuerySubscription(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return fnType([InfiniteQueryArgFrom(D) | SkipToken, optElem(UseInfiniteQuerySubscriptionOptions(D))], UseInfiniteQuerySubscriptionResult(D))
}
/* compiles to:
 * export type UseInfiniteQuerySubscription<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   (a0: InfiniteQueryArgFrom<D> | SkipToken, a1?: UseInfiniteQuerySubscriptionOptions<D>) => UseInfiniteQuerySubscriptionResult<
 *     D
 *   >
 */

// ✓ UseInfiniteQueryHookResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryHookResult(D: InfiniteQueryDefinition<any, any, any, any, any>, R = UseInfiniteQueryStateDefaultResult(D)): any {
  return UseInfiniteQueryStateResult(D, R) & Pick(UseInfiniteQuerySubscriptionResult(D), anyOf('refetch', 'fetchNextPage', 'fetchPreviousPage'))
}
/* compiles to:
 * export type UseInfiniteQueryHookResult<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>,
 *   R = UseInfiniteQueryStateDefaultResult<D>
 * > =
 *   & UseInfiniteQueryStateResult<D, R>
 *   & Pick<
 *       UseInfiniteQuerySubscriptionResult<D>,
 *       'refetch' | 'fetchNextPage' | 'fetchPreviousPage'
 *     >
 */

// ✓ TypedUseInfiniteQueryHookResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseInfiniteQueryHookResult(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn, R: Record<string, any> = UseInfiniteQueryStateDefaultResult(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))): any {
  return UseInfiniteQueryHookResult(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string), R)
}
/* compiles to:
 * export type TypedUseInfiniteQueryHookResult<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn,
 *   R extends Record<string, any> = UseInfiniteQueryStateDefaultResult<InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>>
 * > =
 *   UseInfiniteQueryHookResult<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>,
 *     R
 *   >
 */

// ✓ UseInfiniteQueryStateOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryStateOptions(D: InfiniteQueryDefinition<any, any, any, any, any>, R: Record<string, any>): any {
  return { skip: optional(boolean), selectFromResult: optional(InfiniteQueryStateSelector(R, D)) }
}
/* compiles to:
 * export type UseInfiniteQueryStateOptions<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>,
 *   R extends Record<string, any>
 * > =
 *   { skip?: boolean; selectFromResult?: InfiniteQueryStateSelector<R, D> }
 */

// ✓ TypedUseInfiniteQueryStateOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseInfiniteQueryStateOptions(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn, SelectedResult: Record<string, any> = UseInfiniteQueryStateDefaultResult(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))): any {
  return UseInfiniteQueryStateOptions(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string), SelectedResult)
}
/* compiles to:
 * export type TypedUseInfiniteQueryStateOptions<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn,
 *   SelectedResult extends Record<string, any> = UseInfiniteQueryStateDefaultResult<InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>>
 * > =
 *   UseInfiniteQueryStateOptions<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>,
 *     SelectedResult
 *   >
 */

// ✓ UseInfiniteQueryStateResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryStateResult(D: InfiniteQueryDefinition<any, any, any, any, any>, R = UseInfiniteQueryStateDefaultResult(D)): any {
  return R
}
/* compiles to:
 * export type UseInfiniteQueryStateResult<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>,
 *   R = UseInfiniteQueryStateDefaultResult<D>
 * > =
 *   R
 */

// ✓ TypedUseInfiniteQueryStateResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseInfiniteQueryStateResult(ResultType, QueryArg, PageParam, BaseQuery: BaseQueryFn, R = UseInfiniteQueryStateDefaultResult(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string))): any {
  return UseInfiniteQueryStateResult(InfiniteQueryDefinition(QueryArg, PageParam, BaseQuery, string, ResultType, string), R)
}
/* compiles to:
 * export type TypedUseInfiniteQueryStateResult<
 *   ResultType,
 *   QueryArg,
 *   PageParam,
 *   BaseQuery extends BaseQueryFn,
 *   R = UseInfiniteQueryStateDefaultResult<InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>>
 * > =
 *   UseInfiniteQueryStateResult<
 *     InfiniteQueryDefinition<QueryArg, PageParam, BaseQuery, string, ResultType, string>,
 *     R
 *   >
 */

// ✓ UseInfiniteQueryStateBaseResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryStateBaseResult(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return merge(InfiniteQuerySubState(D), { currentData: optional(InfiniteData(ResultTypeFrom(D), PageParamFrom(D))), isUninitialized: false, isLoading: false, isFetching: false, isSuccess: false, isError: false, hasNextPage: boolean, hasPreviousPage: boolean, isFetchingNextPage: boolean, isFetchingPreviousPage: boolean })
}
/* compiles to:
 * export type UseInfiniteQueryStateBaseResult<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   & InfiniteQuerySubState<D>
 *   & {
 *       currentData?: InfiniteData<ResultTypeFrom<D>, PageParamFrom<D>>
 *       isUninitialized: false
 *       isLoading: false
 *       isFetching: false
 *       isSuccess: false
 *       isError: false
 *       hasNextPage: boolean
 *       hasPreviousPage: boolean
 *       isFetchingNextPage: boolean
 *       isFetchingPreviousPage: boolean
 *     }
 */

// ✓ UseInfiniteQueryStateDefaultResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseInfiniteQueryStateDefaultResult(D: InfiniteQueryDefinition<any, any, any, any, any>): any {
  return merge(TSHelpersId(anyOf(TSHelpersOverride(Extract(UseInfiniteQueryStateBaseResult(D), { status: t<QueryStatus.uninitialized>() }), { isUninitialized: true }), TSHelpersOverride(UseInfiniteQueryStateBaseResult(D), anyOf({ isLoading: true, isFetching: boolean, data: Undefined }, merge({ isSuccess: true, isFetching: true, error: Undefined }, Required(Pick(UseInfiniteQueryStateBaseResult(D), anyOf('data', 'fulfilledTimeStamp')))), merge({ isSuccess: true, isFetching: false, error: Undefined }, Required(Pick(UseInfiniteQueryStateBaseResult(D), anyOf('data', 'fulfilledTimeStamp', 'currentData')))), merge({ isError: true }, Required(Pick(UseInfiniteQueryStateBaseResult(D), 'error'))))))), { status: QueryStatus })
}
/* compiles to:
 * export type UseInfiniteQueryStateDefaultResult<
 *   D extends InfiniteQueryDefinition<any, any, any, any, any>
 * > =
 *   & TSHelpersId<
 *       | TSHelpersOverride<
 *           Extract<UseInfiniteQueryStateBaseResult<D>, { status: QueryStatus.uninitialized }>,
 *           { isUninitialized: true }
 *         >
 *       | TSHelpersOverride<
 *           UseInfiniteQueryStateBaseResult<D>,
 *           | { isLoading: true; isFetching: boolean; data: undefined }
 *           | & { isSuccess: true; isFetching: true; error: undefined }
 *             & Required<Pick<UseInfiniteQueryStateBaseResult<D>, 'data' | 'fulfilledTimeStamp'>>
 *           | & { isSuccess: true; isFetching: false; error: undefined }
 *             & Required<
 *                 Pick<
 *                   UseInfiniteQueryStateBaseResult<D>,
 *                   'data' | 'fulfilledTimeStamp' | 'currentData'
 *                 >
 *               >
 *           | { isError: true } & Required<Pick<UseInfiniteQueryStateBaseResult<D>, 'error'>>
 *         >
 *     >
 *   & { status: QueryStatus }
 */

// ✓ MutationStateSelector: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MutationStateSelector(R: Record<string, any>, D: MutationDefinition<any, any, any, any>): any {
  return fnType([MutationResultSelectorResult(D)], R)
}
/* compiles to:
 * export type MutationStateSelector<
 *   R extends Record<string, any>,
 *   D extends MutationDefinition<any, any, any, any>
 * > =
 *   (a0: MutationResultSelectorResult<D>) => R
 */

// ✓ UseMutationStateOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseMutationStateOptions(D: MutationDefinition<any, any, any, any>, R: Record<string, any>): any {
  return { selectFromResult: optional(MutationStateSelector(R, D)), fixedCacheKey: optional(string) }
}
/* compiles to:
 * export type UseMutationStateOptions<
 *   D extends MutationDefinition<any, any, any, any>,
 *   R extends Record<string, any>
 * > =
 *   { selectFromResult?: MutationStateSelector<R, D>; fixedCacheKey?: string }
 */

// ✓ TypedUseMutationStateOptions: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseMutationStateOptions(ResultType, QueryArg, BaseQuery: BaseQueryFn, SelectedResult: Record<string, any> = MutationResultSelectorResult(MutationDefinition(QueryArg, BaseQuery, string, ResultType, string))): any {
  return UseMutationStateOptions(MutationDefinition(QueryArg, BaseQuery, string, ResultType, string), SelectedResult)
}
/* compiles to:
 * export type TypedUseMutationStateOptions<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn,
 *   SelectedResult extends Record<string, any> = MutationResultSelectorResult<MutationDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 * > =
 *   UseMutationStateOptions<
 *     MutationDefinition<QueryArg, BaseQuery, string, ResultType, string>,
 *     SelectedResult
 *   >
 */

// ✓ UseMutationStateResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseMutationStateResult(D: MutationDefinition<any, any, any, any>, R): any {
  return merge(R, { originalArgs: optional(QueryArgFrom(D)), reset: fnType([], voidType()) })
}
/* compiles to:
 * export type UseMutationStateResult<D extends MutationDefinition<any, any, any, any>, R> =
 *   R & { originalArgs?: QueryArgFrom<D>; reset: () => void }
 */

// ✓ TypedUseMutationResult: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseMutationResult(ResultType, QueryArg, BaseQuery: BaseQueryFn, R = MutationResultSelectorResult(MutationDefinition(QueryArg, BaseQuery, string, ResultType, string))): any {
  return UseMutationStateResult(MutationDefinition(QueryArg, BaseQuery, string, ResultType, string), R)
}
/* compiles to:
 * export type TypedUseMutationResult<
 *   ResultType,
 *   QueryArg,
 *   BaseQuery extends BaseQueryFn,
 *   R = MutationResultSelectorResult<MutationDefinition<QueryArg, BaseQuery, string, ResultType, string>>
 * > =
 *   UseMutationStateResult<MutationDefinition<QueryArg, BaseQuery, string, ResultType, string>, R>
 */

// ✓ UseMutation: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UseMutation(D: MutationDefinition<any, any, any, any>): any {
  return genericFnType(['R extends Record<string, any> = MutationResultSelectorResult<D>'], [optElem(UseMutationStateOptions(D, R))], asReadonly([MutationTrigger(D), UseMutationStateResult(D, R)]))
}
/* compiles to:
 * export type UseMutation<D extends MutationDefinition<any, any, any, any>> =
 *   <R extends Record<string, any> = MutationResultSelectorResult<D>>(
 *     a0?: UseMutationStateOptions<D, R>
 *   ) => readonly [MutationTrigger<D>, UseMutationStateResult<D, R>]
 */

// ✓ TypedUseMutation: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedUseMutation(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return UseMutation(MutationDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedUseMutation<ResultType, QueryArg, BaseQuery extends BaseQueryFn> = UseMutation<
 *   MutationDefinition<QueryArg, BaseQuery, string, ResultType, string>
 * >
 */

// ✓ MutationTrigger: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MutationTrigger(D: MutationDefinition<any, any, any, any>): any {
  return { ...callSig([QueryArgFrom(D)], MutationActionCreatorResult(D)) }
}
/* compiles to:
 * export type MutationTrigger<D extends MutationDefinition<any, any, any, any>> = {
 *   (a0: QueryArgFrom<D>): MutationActionCreatorResult<D>
 * }
 */

// ✓ TypedMutationTrigger: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TypedMutationTrigger(ResultType, QueryArg, BaseQuery: BaseQueryFn): any {
  return MutationTrigger(MutationDefinition(QueryArg, BaseQuery, string, ResultType, string))
}
/* compiles to:
 * export type TypedMutationTrigger<ResultType, QueryArg, BaseQuery extends BaseQueryFn> = MutationTrigger<
 *   MutationDefinition<QueryArg, BaseQuery, string, ResultType, string>
 * >
 */
