/**
 * ScriptType for 02-inference-at-scale/trpc/packages/client/src/links/httpLink.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 typecheck-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const AnyClientTypes: any
declare const HTTPHeaders: any
declare const HTTPLinkBaseOptions: any
declare const Operation: any
type AnyClientTypes<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type HTTPHeaders<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type HTTPLinkBaseOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type Operation<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ HTTPLinkOptions: the ScriptType does not itself typecheck as TypeScript
//   HTTPLinkOptions.st.ts(3:120) TS2348: Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
/* @scripttype preserveParamNames */
export function HTTPLinkOptions(TRoot: AnyClientTypes) {
  return merge(HTTPLinkBaseOptions(TRoot), { headers: optional(HTTPHeaders | fnType([{ op: Operation }], HTTPHeaders | Promise(HTTPHeaders))) })
}
/* compiles to:
 * export type HTTPLinkOptions<TRoot extends AnyClientTypes> = HTTPLinkBaseOptions<TRoot> & { headers?: HTTPHeaders | ((a0: { op: Operation }) => HTTPHeaders | Promise<HTTPHeaders>) }
 */
