/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/action/_add_readonly.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const TAddReadonlyAction: any
declare const TDeferred: any
declare const TSchema: any
type TAddReadonlyAction<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TDeferred<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TSchema<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ TAddReadonlyDeferred: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TAddReadonlyDeferred(Type: TSchema) {
  return TDeferred('AddReadonly', [Type])
}
/* compiles to:
 * export type TAddReadonlyDeferred<Type extends TSchema> = TDeferred<'AddReadonly', [Type]>
 */

// ✓ TAddReadonly: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TAddReadonly(Type: TSchema) {
  return TAddReadonlyAction(Type)
}
/* compiles to:
 * export type TAddReadonly<Type extends TSchema> = TAddReadonlyAction<Type>
 */
