/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/action/with.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 2 type-level aliases: 2 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { TDeferred } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/types/deferred.js'
import type { TSchema } from '../../../../../../03-schema-and-type-level-parsers/typebox/src/type/types/schema.js'
declare const TDeferred: any
declare const TSchema: any
// ✓ TWithDeferred: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TWithDeferred(Type: TSchema, Options: TSchema): any {
  return TDeferred('With', [Type, Options])
}
/* compiles to:
 * export type TWithDeferred<Type extends TSchema, Options extends TSchema> = TDeferred<
 *   'With',
 *   [Type, Options]
 * >
 */

// ✓ TWith: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TWith(Type: TSchema, Options: TSchema): any {
  return merge(Type, Options)
}
/* compiles to:
 * export type TWith<Type extends TSchema, Options extends TSchema> = Type & Options
 */
