/**
 * ScriptType for 03-schema-and-type-level-parsers/abitype/playgrounds/functions/src/types.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 12 type-level aliases: 12 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { Abi, AbiFunction, AbiParameter, AbiStateMutability, Address } from '../../../../../../03-schema-and-type-level-parsers/abitype/packages/abitype/src/abi.js'
import type { ResolvedRegister } from '../../../../../../03-schema-and-type-level-parsers/abitype/packages/abitype/src/register.js'
import type { AbiParametersToPrimitiveTypes, ExtractAbiFunction, ExtractAbiFunctionNames } from '../../../../../../03-schema-and-type-level-parsers/abitype/packages/abitype/src/utils.js'
declare namespace m1 {
  export type I<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type L<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Val<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type abiFunction_<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type primitiveType<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m2 {
  export type abiFunctions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const Abi: any
declare const AbiFunction: any
declare const AbiParameter: any
declare const AbiParametersToPrimitiveTypes: any
declare const AbiStateMutability: any
declare const Address: any
declare const ExtractAbiFunction: any
declare const ExtractAbiFunctionNames: any
declare const ResolvedRegister: any
declare const abiFunctions: any
type abiFunctions<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ ContractParameters: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ContractParameters(abi: Abi | readonly unknown[] = Abi, functionName: string = string, abiStateMutability: AbiStateMutability = AbiStateMutability, args: readonly unknown[] | undefined = asReadonly([]), functionNames: string = matches<Abi>(abi) ? ExtractAbiFunctionNames(abi, abiStateMutability) : string): any {
  return merge({ functionName: anyOf(functionNames, matches<typeof functionNames>(functionName) ? functionName : never, matches<typeof abi>(Abi) ? string : never) }, GetArgs(abi, functionName, args))
}
/* compiles to:
 * export type ContractParameters<
 *   abi extends Abi | readonly unknown[] = Abi,
 *   functionName extends string = string,
 *   abiStateMutability extends AbiStateMutability = AbiStateMutability,
 *   args extends readonly unknown[] | undefined = readonly [],
 *   functionNames extends string = abi extends Abi ? ExtractAbiFunctionNames<abi, abiStateMutability> : string
 * > =
 *   & {
 *       functionName: | functionNames
 *       | (functionName extends functionNames ? functionName : never)
 *       | (Abi extends abi ? string : never)
 *     }
 *   & GetArgs<abi, functionName, args>
 */

// ✓ GetArgs: verified type-identical to the original
/* @scripttype preserveParamNames */
export function GetArgs(abi: Abi | readonly unknown[] = Abi, functionName: string = string, args: readonly unknown[] | undefined = asReadonly([]), abiFunction: AbiFunction = matches<Abi>(abi) ? ExtractAbiFunction(abi, functionName) : AbiFunction, primitiveTypes = AbiParametersToPrimitiveTypes(abiFunction['inputs'], 'inputs', true), args_ = primitiveTypes | (matches<Abi>(abi) ? (matches<typeof primitiveTypes>(args) ? (matches<typeof args>(primitiveTypes) ? ReadonlyWiden(args) : never) : never) : never) | (matches<typeof abi>(Abi) ? readonlyArrayOf(unknown) : never)): any {
  return MaybePartialBy({ args: args_ }, matches<typeof primitiveTypes>(asReadonly([])) ? 'args' : (matches<typeof abi>(Abi) ? 'args' : string))
}
/* compiles to:
 * export type GetArgs<
 *   abi extends Abi | readonly unknown[] = Abi,
 *   functionName extends string = string,
 *   args extends readonly unknown[] | undefined = readonly [],
 *   abiFunction extends AbiFunction = abi extends Abi ? ExtractAbiFunction<abi, functionName> : AbiFunction,
 *   primitiveTypes = AbiParametersToPrimitiveTypes<abiFunction['inputs'], 'inputs', true>,
 *   args_ = primitiveTypes | (abi extends Abi ? args extends primitiveTypes ? primitiveTypes extends args ? ReadonlyWiden<args> : never : never : never) | (Abi extends abi ? readonly unknown[] : never)
 * > =
 *   MaybePartialBy<
 *     { args: args_ },
 *     readonly [] extends primitiveTypes ? 'args' : Abi extends abi ? 'args' : string
 *   >
 */

// ✓ ContractReturnType: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ContractReturnType__v1(abi, functionName, args): any {
  const m1 = matches<Hole<"abiFunction_", AbiFunction>>(matches<Abi>(abi) ? ExtractAbiFunction(abi, functionName) : AbiFunction)
  if (m1) {
    if (matches<true>(IsUnion(m1.abiFunction_))) {
      const m2 = matches<Hole<"abiFunctions", readonly AbiFunction[]>>(UnionToTuple(m1.abiFunction_))
      if (m2) {
        const out = emptyObject
        for (const K in keyof(m2.abiFunctions)) {
          out[K] = matches<AbiParametersToPrimitiveTypes<(typeof m2.abiFunctions)[typeof K]['inputs'], 'inputs'>>(matches<typeof args>(anyOf(readonlyArrayOf(unknown), Undefined)) ? asReadonly([]) : args) ? m2.abiFunctions[K] : never
        }
        return out[number]
      }
      return never
    }
    return m1.abiFunction_
  }
  return never
}
export function ContractReturnType(abi: Abi | readonly unknown[] = Abi, functionName: string = string, args: readonly unknown[] | undefined = anyOf(readonlyArrayOf(unknown), Undefined), abiFunction: AbiFunction = ContractReturnType__v1(abi, functionName, args), outputs: readonly AbiParameter[] = abiFunction['outputs'], primitiveTypes: readonly unknown[] = AbiParametersToPrimitiveTypes(outputs, 'outputs', true)): any {
  if (matches<[ never ]>([abiFunction])) {
    return unknown
  }
  if (matches<typeof primitiveTypes>(readonlyArrayOf(unknown))) {
    return unknown
  }
  if (matches<readonly [ ]>(primitiveTypes)) {
    return voidType()
  }
  const m1 = matches<readonly [ Hole<"primitiveType"> ]>(primitiveTypes)
  if (m1) {
    return m1.primitiveType
  }
  return primitiveTypes
}
/* compiles to:
 * export type ContractReturnType__v1<abi, functionName, args> =
 *   (abi extends Abi ? ExtractAbiFunction<abi, functionName> : AbiFunction) extends (infer abiFunction_ extends AbiFunction)
 *     ? IsUnion<abiFunction_> extends true
 *       ? UnionToTuple<abiFunction_> extends (infer abiFunctions extends readonly AbiFunction[])
 *         ? {
 *           [K in keyof abiFunctions]: (readonly unknown[] | undefined extends args ? readonly [] : args) extends AbiParametersToPrimitiveTypes<abiFunctions[K]['inputs'], 'inputs'>
 *             ? abiFunctions[K]
 *             : never
 *         }[number]
 *         : never
 *       : abiFunction_
 *     : never
 * export type ContractReturnType<
 *   abi extends Abi | readonly unknown[] = Abi,
 *   functionName extends string = string,
 *   args extends readonly unknown[] | undefined = readonly unknown[] | undefined,
 *   abiFunction extends AbiFunction = ContractReturnType__v1<abi, functionName, args>,
 *   outputs extends readonly AbiParameter[] = abiFunction['outputs'],
 *   primitiveTypes extends readonly unknown[] = AbiParametersToPrimitiveTypes<outputs, 'outputs', true>
 * > =
 *   [abiFunction] extends [never] ? unknown
 *   : readonly unknown[] extends primitiveTypes ? unknown
 *   : primitiveTypes extends readonly [] ? void
 *   : primitiveTypes extends readonly [infer primitiveType] ? primitiveType
 *   : primitiveTypes
 */

// ✓ IsUnion: verified type-identical to the original
/* @scripttype preserveParamNames */
export function IsUnion(T, C = T): any {
  if (matches<typeof C>(T)) {
    if (matches<[ typeof T ]>([C])) {
      return false
    }
    return true
  }
  return never
}
/* compiles to:
 * export type IsUnion<T, C = T> = T extends C ? [C] extends [T] ? false : true : never
 */

// ✓ UnionToTuple: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UnionToTuple(U, Last = LastInUnion(U)): any {
  if (matches<[ never ]>([U])) {
    return []
  }
  return [...UnionToTuple(Exclude(U, Last)), Last]
}
/* compiles to:
 * export type UnionToTuple<U, Last = LastInUnion<U>> =
 *   [U] extends [never] ? [] : [...UnionToTuple<Exclude<U, Last>>, Last]
 */

// ✓ LastInUnion: verified type-identical to the original
/* @scripttype preserveParamNames */
export function LastInUnion(U): any {
  const m1 = matches<(x: Hole<"L">) => 0>(UnionToIntersection(matches<unknown>(U) ? fnType([U], 0) : never))
  if (m1) {
    return m1.L
  }
  return never
}
/* compiles to:
 * export type LastInUnion<U> =
 *   UnionToIntersection<U extends unknown ? (a0: U) => 0 : never> extends (x: infer L) => 0
 *     ? L
 *     : never
 */

// ✓ UnionToIntersection: verified type-identical to the original
/* @scripttype preserveParamNames */
export function UnionToIntersection(U): any {
  const m1 = matches<(arg: Hole<"I">) => 0>(matches<unknown>(U) ? fnType([U], 0) : never)
  if (m1) {
    return m1.I
  }
  return never
}
/* compiles to:
 * export type UnionToIntersection<U> =
 *   (U extends unknown ? (a0: U) => 0 : never) extends (arg: infer I) => 0 ? I : never
 */

// ✓ PartialBy: verified type-identical to the original
/* @scripttype preserveParamNames */
/**
 * @param {keyof typeof TType} TKeys
 */
export function PartialBy(TType, TKeys): any {
  return ExactPartial(Pick(TType, TKeys)) & Omit(TType, TKeys)
}
/* compiles to:
 * export type PartialBy<TType, TKeys extends keyof TType> =
 *   ExactPartial<Pick<TType, TKeys>> & Omit<TType, TKeys>
 */

// ✓ ExactPartial: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ExactPartial(T): any {
  const out = emptyObject
  for (const K in keyof(T)) {
    out[K] = optional(anyOf(T[K], Undefined))
  }
  return out
}
/* compiles to:
 * export type ExactPartial<T> = { [K in keyof T]?: T[K] | undefined }
 */

// ✓ MaybePartialBy: verified type-identical to the original
/* @scripttype preserveParamNames */
export function MaybePartialBy(TType, TKeys: string): any {
  if (TKeys in TType) {
    return PartialBy(TType, TKeys)
  }
  return TType
}
/* compiles to:
 * export type MaybePartialBy<TType, TKeys extends string> =
 *   TKeys extends keyof TType ? PartialBy<TType, TKeys> : TType
 */

// ✓ ReadonlyWiden: verified type-identical to the original
/* @scripttype preserveParamNames */
export function ReadonlyWiden(TType): any {
  const out = emptyObject
  for (const K in keyof(TType)) {
    out[K] = ReadonlyWiden(TType[K])
  }
  const out2 = emptyObject
  for (const K in keyof(TType)) {
    out2[K] = ReadonlyWiden(TType[K])
  }
  const m1 = matches<Hole<"Val", unknown[]>>(out2)
  return (matches<Function>(TType) ? TType : never) | (matches<ResolvedRegister['bigIntType']>(TType) ? bigint : never) | (typeof TType === 'boolean' ? boolean : never) | (matches<ResolvedRegister['intType']>(TType) ? number : never) | (typeof TType === 'string' ? (matches<Address>(TType) ? Address : (matches<ResolvedRegister['bytesType']['inputs']>(TType) ? ResolvedRegister['bytesType'] : string)) : never) | (matches<readonly [ ]>(TType) ? asReadonly([]) : never) | (matches<Record<string, unknown>>(TType) ? out : never) | (matches<{ length: number; }>(TType) ? (m1 ? asReadonly([...m1.Val]) : never) : never)
}
/* compiles to:
 * export type ReadonlyWiden<TType> =
 *   | (TType extends Function ? TType : never)
 *   | (TType extends ResolvedRegister['bigIntType'] ? bigint : never)
 *   | (TType extends boolean ? boolean : never)
 *   | (TType extends ResolvedRegister['intType'] ? number : never)
 *   | (
 *       TType extends string
 *         ? TType extends Address ? Address
 *         : TType extends ResolvedRegister['bytesType']['inputs'] ? ResolvedRegister['bytesType']
 *         : string
 *         : never
 *     )
 *   | (TType extends readonly [] ? readonly [] : never)
 *   | (
 *       TType extends Record<string, unknown>
 *         ? { [K in keyof TType]: ReadonlyWiden<TType[K]> }
 *         : never
 *     )
 *   | (
 *       TType extends { length: number; }
 *         ? { [K1 in keyof TType]: ReadonlyWiden<TType[K1]> } extends (infer Val extends unknown[])
 *           ? readonly [...Val]
 *           : never
 *         : never
 *     )
 */

// ✓ DeepPartial: verified type-identical to the original
/* @scripttype preserveParamNames */
export function DeepPartial(T, MaxDepth: number, Depth: readonly number[] = []): any {
  if (matches<typeof MaxDepth>(Depth['length'])) {
    return T
  }
  if (matches<object>(T)) {
    const out = emptyObject
    for (const P in keyof(T)) {
      out[P] = optional(anyOf(DeepPartial(T[P], MaxDepth, [...Depth, 1]), Undefined))
    }
    return out
  }
  return T
}
/* compiles to:
 * export type DeepPartial<T, MaxDepth extends number, Depth extends readonly number[] = []> =
 *   Depth['length'] extends MaxDepth ? T
 *   : T extends object
 *     ? { [P in keyof T]?: DeepPartial<T[P], MaxDepth, [...Depth, 1]> | undefined }
 *   : T
 */
