/**
 * ScriptType for 05-functional-effects-hkt/fp-ts/src/Identity.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 1 type-level aliases: 1 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// ✓ Identity: verified type-identical to the original
/* @scripttype preserveParamNames */
export function Identity(A) {
  return A
}
/* compiles to:
 * export type Identity<A> = A
 */
