/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/engine/extract/operation.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 3 type-level aliases: 2 typecheck-error, 1 compile-error
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Names this file references but does not define: types from elsewhere in the
// library, and local functions used in type position. Declared so the generated
// ScriptType typechecks standalone. They carry no runtime meaning.
declare const ExtendsResult: any
declare const TEvaluateType: any
declare const TEvaluateUnion: any
declare const TExtends: any
declare const TExtendsTrueLike: any
declare const TResult: any
declare const TSchema: any
type ExtendsResult<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TEvaluateType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TEvaluateUnion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TExtends<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TExtendsTrueLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TResult<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
type TSchema<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any> = any
// ✗ TExtractType: the ScriptType does not itself typecheck as TypeScript
//   TExtractType.st.ts(2:68) TS2702: 'ExtendsResult' only refers to a type, but is being used as a namespace here.
/* @scripttype preserveParamNames */
export function TExtractType(Left: TSchema, Right: TSchema, Check: ExtendsResult.TResult = TExtends({}, Left, Right), Result: TSchema[] = matches<ExtendsResult.TExtendsTrueLike>(Check) ? [Left] : []) {
  return Result
}
/* compiles to:
 * export type TExtractType<Left extends TSchema, Right extends TSchema, Check extends ExtendsResult.TResult = TExtends<{}, Left, Right>, Result extends TSchema[] = Check extends ExtendsResult.TExtendsTrueLike ? [Left] : []> = Result
 */

// ✗ TExtractUnion: the ScriptType does not itself typecheck as TypeScript
//   TExtractUnion.st.ts(11:5) TS2322: Type 'any[]' is not assignable to type 'never[]'.   Type 'any' is not assignable to type 'never'.
/* @scripttype preserveParamNames */
export function TExtractUnion(Types: TSchema[], Right: TSchema) {
  let Result = []
  let types = Types
  while (true) {
    const m1 = matches<[ Hole<"Head", TSchema>, ...Hole<"Tail", TSchema[]> ]>(types)
    if (!m1) {
      break
    }
    types = m1.Tail
    Result = [...Result, ...TExtractType(m1.Head, Right)]
  }
  return Result
}
/* compiles to:
 * export type TExtractUnion<Types extends TSchema[], Right extends TSchema> = TExtractUnion__loop<Types, [], Right>
 * type TExtractUnion__loop<Types extends TSchema[], Result extends readonly unknown[], Right extends TSchema> = Types extends [infer Head extends TSchema, ...(infer Tail extends TSchema[])] ? TExtractUnion__loop<Tail, [...Result, ...TExtractType<Head, Right>], Right> : Result
 */

// ✗ TExtractOperation: does not compile yet
//   Cannot find name 'm1'.
/* @scripttype preserveParamNames */
export function TExtractOperation(Left: TSchema, Right: TSchema, Evaluated: TSchema = TEvaluateType(Left), Canonical: TSchema[] = m1 ? m1.Types : [Evaluated], Remaining: TSchema[] = TExtractUnion(Canonical, Right), Result: TSchema = TEvaluateUnion(Remaining)) {
  return Result
}
/* compiles to:
 * export type TExtractOperation<Left extends TSchema, Right extends TSchema, Evaluated extends TSchema = TEvaluateType<Left>, Canonical extends TSchema[] = m1 extends true ? m1.Types : [Evaluated], Remaining extends TSchema[] = TExtractUnion<Canonical, Right>, Result extends TSchema = TEvaluateUnion<Remaining>> = Result
 */
