/**
 * ScriptType for 03-schema-and-type-level-parsers/typebox/src/type/engine/extract/operation.ts
 *
 * Generated by the ScriptType decompiler from the corpus source above, then verified
 * by recompiling and comparing to the original with the TypeScript checker.
 * 3 type-level aliases: 3 covered
 *
 * Do not edit: regenerate with `tsx src/materialize.ts`.
 */
// Types this file references but does not define. Those whose declaration could be
// found are imported, so the check is against the real type rather than `any`; the
// rest are stubbed. Each also gets a value declaration, because ScriptType applies
// types in call position and a type-only import binds nothing in value space.
import type { TEvaluateType, TEvaluateUnion } from '../../../../../../../03-schema-and-type-level-parsers/typebox/src/type/engine/evaluate/evaluate.js'
import type { TExtendsTrueLike } from '../../../../../../../03-schema-and-type-level-parsers/typebox/src/type/extends/result.js'
import type { TSchema } from '../../../../../../../03-schema-and-type-level-parsers/typebox/src/type/types/schema.js'
import type { TUnion } from '../../../../../../../03-schema-and-type-level-parsers/typebox/src/type/types/union.js'
declare namespace ExtendsResult {
  export type TExtendsTrueLike<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type TResult<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare namespace m1 {
  export type Head<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Tail<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
  export type Types<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
}
declare const ExtendsResult: any
declare const TEvaluateType: any
declare const TEvaluateUnion: any
declare const TExtends: any
declare const TExtendsTrueLike: any
declare const TResult: any
declare const TSchema: any
declare const TUnion: any
type ExtendsResult<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TExtends<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
type TResult<T1 = any, T2 = any, T3 = any, T4 = any, T5 = any, T6 = any, T7 = any, T8 = any, T9 = any, T10 = any, T11 = any, T12 = any, T13 = any, T14 = any, T15 = any, T16 = any> = any
// ✓ TExtractType: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TExtractType(Left: TSchema, Right: TSchema, Check: ExtendsResult.TResult = TExtends({}, Left, Right), Result: TSchema[] = matches<ExtendsResult.TExtendsTrueLike>(Check) ? [Left] : []): any {
  return Result
}
/* compiles to:
 * export type TExtractType<
 *   Left extends TSchema,
 *   Right extends TSchema,
 *   Check extends ExtendsResult.TResult = TExtends<{}, Left, Right>,
 *   Result extends TSchema[] = Check extends ExtendsResult.TExtendsTrueLike ? [Left] : []
 * > =
 *   Result
 */

// ✓ TExtractUnion: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TExtractUnion(Types: TSchema[], Right: TSchema): any {
  let Result: any[] = []
  let types = Types
  while (true) {
    const m1 = matches<[ Hole<"Head", TSchema>, ...Hole<"Tail", TSchema[]> ]>(types)
    if (!m1) {
      break
    }
    types = m1.Tail
    Result = [...Result, ...TExtractType(m1.Head, Right)]
  }
  return Result
}
/* compiles to:
 * export type TExtractUnion<Types extends TSchema[], Right extends TSchema> = TExtractUnion__loop<
 *   Types,
 *   [],
 *   Right
 * >
 * type TExtractUnion__loop<
 *   Types extends TSchema[],
 *   Result extends any[],
 *   Right extends TSchema
 * > =
 *   Types extends [infer Head extends TSchema, ...infer Tail extends TSchema[]]
 *     ? TExtractUnion__loop<Tail, [...Result, ...TExtractType<Head, Right>], Right>
 *     : Result
 */

// ✓ TExtractOperation: verified type-identical to the original
/* @scripttype preserveParamNames */
export function TExtractOperation__v1(Evaluated): any {
  const m1 = matches<TUnion<Hole<"Types", TSchema[]>>>(Evaluated)
  if (m1) {
    return m1.Types
  }
  return [Evaluated]
}
export function TExtractOperation(Left: TSchema, Right: TSchema, Evaluated: TSchema = TEvaluateType(Left), Canonical: TSchema[] = TExtractOperation__v1(Evaluated), Remaining: TSchema[] = TExtractUnion(Canonical, Right), Result: TSchema = TEvaluateUnion(Remaining)): any {
  return Result
}
/* compiles to:
 * export type TExtractOperation__v1<Evaluated> =
 *   Evaluated extends TUnion<infer Types extends TSchema[]> ? Types : [Evaluated]
 * export type TExtractOperation<
 *   Left extends TSchema,
 *   Right extends TSchema,
 *   Evaluated extends TSchema = TEvaluateType<Left>,
 *   Canonical extends TSchema[] = TExtractOperation__v1<Evaluated>,
 *   Remaining extends TSchema[] = TExtractUnion<Canonical, Right>,
 *   Result extends TSchema = TEvaluateUnion<Remaining>
 * > =
 *   Result
 */
